### ISSUE TITLE
[Enhancement] abbility to scale subpictures when exporting to vobsub

### ISSUE THREAD

**Issue by m-audio91** [SubtitleEdit/subtitleedit#1322]
Hello

**feature request:**
Can you please add ability to scale subpictures (horizontally or vertically) when exporting to vobsub (sub|idx)?
I'm not talking about soft flags.

Thanks.

**Comment by aaaxx** [comment]
Do you mean for anamorphic DVDs?

**Comment by m-audio91** [comment]
Yes, aaaxx.

**Comment by aaaxx** [comment]
These are the needed values, if somebody decides to implement it:
```
PAL
     4:3    width / (16/15)    OR    width * (15/16)
    16:9    width / (64/45)    OR    width * (45/64)

NTSC
     4:3    width / (8/9)      OR    width * (9/8)
    16:9    width / (32/27)    OR    width * (27/32)
```
And note that even the subs on 4:3 DVDs (i.e. non-anamorphic) need distortion because DVDs don't store image in 4:3 (1.33) or 16:9 (1.77). For example, PAL is in 720/576 = 1.25:1 aspect ratio, and gets stretched on playback even for the so-called *non*-anamorphic 4:3 DVDs.
