### ISSUE TITLE
Impossible to do a visual sync

### ISSUE THREAD

**Issue by LotusFlower1** [SubtitleEdit/subtitleedit#1369]
OS : Win 10
The error occurs each time I clic on the button Sync, with every subtitles (srt) or videos (mkv).

![untitled](https://cloud.githubusercontent.com/assets/14893361/10380590/955942a4-6e0c-11e5-89fb-da75881993f7.png)

However no problem with the portable version ^^

**Comment by jdpurcell** [comment]
Are you using the latest version? (3.4.10)

**Comment by xylographe** [comment]
Could this be related to the installer running ngen. Perhaps, skip that when installing on Win10?

**Comment by LotusFlower1** [comment]
@jdpurcell Yes the lastest version, but I tried older version and it's the same :(

@xylographe What can I do ? I tried 3 different versions. 
Do you think it's a problem with Win 10 ?

**Comment by niksedk** [comment]
@LotusFlower1: Could you try this version: http://www.nikse.dk/SubtitleEditDebug.zip (portable test version)
It should supply a line number in the error message.

**Comment by xylographe** [comment]
Try [SubtitleEdit-3.4.10-no-ngen-setup](https://www.dropbox.com/s/ga4944i3k9in9gx/SubtitleEdit-3.4.10-no-ngen-setup.exe?dl=1)﻿: not running ngen while installing is the only difference.

**Comment by LotusFlower1** [comment]
@niksedk As I said the portable version works very well

@xylographe Thanks it works perfectly !!

Thanks to all :)

**Comment by xylographe** [comment]
@LotusFlower1
Could you, please, try [SubtitleEdit-3.4.10.33-ngen2-setup](https://www.dropbox.com/s/2uxydug5ydhe36w/SubtitleEdit-3.4.10.33-ngen2-setup.exe?dl=1).

If that *doesn't* work, please, try [SubtitleEdit-3.4.10.33-ngen3-setup](https://www.dropbox.com/s/48w9o01r3xm7frj/SubtitleEdit-3.4.10.33-ngen3-setup.exe?dl=1).

I would expect both to work, but I cannot test them myself, because I cannot reproduce this problem.

**Comment by LotusFlower1** [comment]
@xylographe Why do I need to try an other one ? The first one you gave to me works very well :)
