### ISSUE TITLE
EBU TTM import/export missing whitespaces/linebreaks

### ISSUE THREAD

**Issue by Chanipie** [SubtitleEdit/subtitleedit#1398]
The following subtitles: http://www.ardmediathek.de/subtitle/36220 get imported perfectly fine into Subtitle Edit. After exporting to .srt however, the subtitles are missing whitespaces/linebreaks.

Example:
```
<tt:span style="textWhite">Live-Untertitelung: ARD Text</tt:span>
<tt:br/>
<tt:span style="textWhite">im Auftrag des SWR</tt:span>
```
In this case the `<tt:br/>` line is omitted when exporting.

**Comment by niksedk** [comment]
Thx for then info :)
Should be fixed in a recent commit: https://github.com/SubtitleEdit/subtitleedit/commit/c021a2902cee0ee84fb3ea145507e932d985ab36

You can verify it via this version: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.10/SubtitleEditBetaTest.zip (beta, portable version without installer)

**Comment by Chanipie** [comment]
Thank you! Fixed indeed.

**Comment by niksedk** [comment]
Thx for verifying!
