### ISSUE TITLE
Support for export to non-standard 23.976 EBU-STL

### ISSUE THREAD

**Issue by mrother** [SubtitleEdit/subtitleedit#1400]
Hi,

I'm having trouble exporting subtitles to EBU-STL to non-standard 23.976 framerate.
Is it possible to add this to SE?

Aegisub support this, but it has a bug that doubles every space in sub's text.
When exporting to 23.976 framerate, the Disk Format Code is set to "STL24.01", but the timecodes are calculated according to framerate.

I've attached the Aegisub's Save Dialog for reference.

Mauricio
![ebu-stl export](https://cloud.githubusercontent.com/assets/10717418/10807773/9070352c-7dca-11e5-82ba-8e0c1df41c0b.png)

**Comment by niksedk** [comment]
Could you test this version: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.10/SubtitleEditBetaTest.zip

**Comment by aaaxx** [comment]
You can also submit Aegisub bug report here: http://devel.aegisub.org/wiki/Bugs

**Comment by mauriciorother** [comment]
Hi, thanks for your feedback.

It doesn't worked, the header is correct (24.01), but the framerate seems incorrect (by the end of the video, ~40min, the subtitle delay is about 2 seconds.

I'm testing using Spot (trial, of course!), as I do not found a player who reads STL.

Also, just FYI, exporting to EBU (instead of saving) the header is wrong, 30.01 when I set to 24.01. Saving seems ok.

I'm attaching two STL files, saved with SE and with Aegisub, with the same format/framerate for comparision. Also, some screenshots of the delay (sort of...) in Spot.

If you need the video for testing, I'll upload somewhere and send a link for you.

Thank you very much

Mauricio

https://www.dropbox.com/s/103z9x0fkpa8vi5/ebu_subtitleedit.zip?dl=0

**Comment by niksedk** [comment]
SE uses TIME as the base - frame rate is only for output, so the only place you can change frame rate through out the subtitle is in the Sync menu.

I could not re-create the 30.1 vs 24.01 issue... will test a bit more though...

**Comment by niksedk** [comment]
I've tested and found a bug when saving in 23.1 (was saved as 30.1) - new version here:  https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.10/SubtitleEditBetaTest.zip

@mrother: OK now?

**Comment by niksedk** [comment]
Presumed fixed with commit 63c37dec8403d8805441a618f47cefdf9513ec46
