### ISSUE TITLE
read start time,end time code from jpeg file

### ISSUE THREAD

**Issue by heforfree** [SubtitleEdit/subtitleedit#1433]
read start time,end time code from jpeg file when import image.
0_00_01_042__0_00_03_919_01.jpeg 00:01:48,820
0_00_04_045__0_00_05_087_01.jpeg
0_00_05_213__0_00_06_630_01.jpeg
0_00_06_756__0_00_10_759_01.jpeg
0_00_06_756__0_00_10_759_02.jpeg
so i want auto import timecode like this
starttime            end time
00:00:01,042    00:00:03,919
00:00:04,045    00:00:05,087
00:00:05,213    00:00:06,630
00:00:06,756    00:00:10,759
00:00:06,756    00:00:10,759

so you may ask why so i tell you why.there is a tool called VideoSubFinder
i t can extract hardsub from video very good.but problem is when you want create sub program will
crashed.created image will remain in TXTImages folder.so i can import to SE but problem is time code
please if you can add reading timecode from file name as soon as possible.
also seem SE wont read jpeg format so i must rename to jpg
thank you very much

**Comment by aaaxx** [comment]
Until then, you can copy the filenames to a text editor that supports [regular expressions](https://en.wikipedia.org/wiki/Regular_expression) or column editing (for example [Notepad++](https://notepad-plus-plus.org/)), clean them up and create an empty subtitle file.

There's a neat trick in Windows to get the filenames: select your files (or "Ctrl + A" to select all), press and hold Shift, right-click **the first file** and select "Copy as path", then paste in a text editor.

You'll get something like this:
```text
"C:\Program Files\VideoSubFinder\TXTImages\0_00_01_042__0_00_03_919_01.jpeg"
"C:\Program Files\VideoSubFinder\TXTImages\0_00_04_045__0_00_05_087_01.jpeg"
...
```
If you don't know how to use regular expressions, paste the list into [Pastebin](http://pastebin.com/) and post the link here so that somebody can help you.
<hr/>
Nikse, if you decide to implement this, it would be a good idea to add it not just to "Import images..." but also to "Import plain text..." (for "Multiple files" mode).

**Comment by niksedk** [comment]
OK, could you test this version: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.10/SubtitleEditBetaTest.zip ? (or compile from latest source code)

**Comment by heforfree** [comment]
thank you so much working I appreciate that for adding this
so i guess to close it

**Comment by heforfree** [comment]
one crash imported image was large pc freezed
https://gist.github.com/heforfree/be387162b59a7e0822ee#file-gistfile1-txt

**Comment by heforfree** [comment]
hello
also there is other tool called AVISubDetector it hard to load video on this and i try video that can not load in VideoSubFinder, it have different method manual  automatic ocr. ocr and manual  take time.
but with automatic  it generate a bmp file and when it finish create sub file like below
if user selected bitmap path

1
00:00:00,041 --> 00:00:00,417
C:\te\SubPic\iCopy.orig.00000.bmp

2
00:00:00,417 --> 00:00:01,835
C:\te\SubPic\iCopy.orig.00001.bmp

3
00:00:03,628 --> 00:00:04,796
C:\te\SubPic\iCopy.orig.00002.bmp

4
00:00:04,963 --> 00:00:07,048
C:\te\SubPic\iCopy.orig.00003.bmp

5
00:00:07,173 --> 00:00:09,426
C:\te\SubPic\iCopy.orig.00004.bmp

6
00:00:09,551 --> 00:00:10,051
C:\te\SubPic\iCopy.orig.00005.bmp
C:\te\SubPic\iCopy.orig.00006.bmp


as excepted SE prompt for import OCR bluray
but problem is Tesseract can not detect very well since image not fully like sub idx file
(remove .txt at the end of attachment it is bmp file to see what i mean)
can you add something like drop differences below for red green blue sum like are in AVISubDetector
so first this apply then Tesseract apply?

[iCopy.orig.00006.bmp.txt](https://github.com/SubtitleEdit/subtitleedit/files/53961/iCopy.orig.00006.bmp.txt)

thankyou

**Comment by aaaxx** [comment]
I don't know how easy or difficult this would be to implement, so if it doesn't get added here's an alternative.

You could make an action in Photoshop and run it on the whole folder. [The first post here](http://forum.doom9.org/showthread.php?t=171519) describes what I usually do. If you don't have Photoshop you can probably do the same thing in Gimp, but some of the commands might be named differently.

Also, ABBYY FineReader gives much better OCR results, but it's not cheap. It could be worth it, though, if you do this kind of thing a lot. Or you could just check certain websites, I suppose :wink:.

And another, thing. Here's [a program](https://dl.dropboxusercontent.com/u/11379791/KG/Forum/VideoSubFinder%20and%20ABBFR/Timings%20Cleaner%20by%2054.rar) that will merge duplicate screenshots' timings and keep the text of only the first one. You just have to mark every duplicate screenshot after the first one with an asterisk while you're cleaning up your OCR output (just put * instead of the text, or at the beggining of the first line of text) and then just run it through the program when done.

It was written to automatically clean up AVISubDetector's output SRT since it uses asterisks to mark lines that were detected as minor changes in the same subtitle, as opposed to an entirely new subtitle. But AVISubDetector is unreliable in this and, since you have to clean up the OCRed text anyway and somehow mark the duplicates so you can get rid of them later, this is an easy way to do it.

Here's how it works:
<blockquote>
<p>It will delete all the subtitles starting with an asterisk (*) after copying their end-times to the previous subtitle and renumber the file.</p>

<ol>
<li>click “Open...” (when SRT is opened it automatically copies timings and deletes lines)</li>
<li>click “Save” (saves the file with “-fixed” appended to filename; never overwrites the original file)</li>
</ol>

<p>And that’s it!</p>

<p>The app also has some optional checkboxes, which you can disregard:</p>

<ul>
<li>“Save timings only” keeps only timings and removes all text</li>
<li>“Highlight with #” marks all subtitles with short timings (default minimum value is 1000 ms)</li>
<li>“Limited preview” shows only the subtitles with short timings (default minimum value is 1000 ms)</li>
</ul>
</blockquote>

**Comment by aaaxx** [comment]
Nikse, I thought you were gonna make the timecode format customizable. It would be useful for something other than VideoSubFinder.

**Comment by heforfree** [comment]
@aaaxx thank you for putting your time for helping me and tutorial.
 i don't have ABBYY FineReader and it have huge size too so i dont use it.
and thanks for you tool i will use it.
also i found that method that you use with Photoshop can be done with AVISubDetector itself.
i found that but luck:)
just in settings tab tick a preprocessing colors.
the final srt linked to bitmap is like this "iCopy.orig.00002.bmp", this can not ocr
but there are image on that folder like  "iCopy.post.00002.bmp "
so it is similar your  Photoshop method and can be ocr,and must find and replace in notepad
orig replaced with post.with this way almost of them can be ocr
thank you again
[iCopy.orig.00002.bmp.txt](https://github.com/SubtitleEdit/subtitleedit/files/55484/iCopy.orig.00002.bmp.txt)
[iCopy.post.00002.bmp.txt](https://github.com/SubtitleEdit/subtitleedit/files/55485/iCopy.post.00002.bmp.txt)

@Nikse
here another crash report
untick auto transparent background cause crash
https://gist.github.com/heforfree/c6218c35c8fa632c540d

**Comment by niksedk** [comment]
I don't think I can fix that crash... it's probably due to the underlying system :(

**Comment by heforfree** [comment]
ok thank you both above log can not fixed? can be auto ignored i mean no crash dialog?
there is new crash i get
save all image with html index.
https://gist.github.com/heforfree/34938615ed7a11341275

also please add option to export text with time code in import ocr/vobsub window
so i can get them import later with import text with matching time code

**Comment by xylographe** [comment]
@heforfree 
You could try re-installing the *Microsoft .NET Framework* (probably [Microsoft .NET Framework 4.6.1](https://www.microsoft.com/en-us/download/details.aspx?id=49981) or [Microsoft .NET Framework 4.5.2](https://www.microsoft.com/en-us/download/details.aspx?id=42643)).

**Comment by heforfree** [comment]
now installed .net 4.6.1 still same

**Comment by nikse** [comment]
i'm gonna have to start reporting you guys everytime you include me in this thread. it is unbelievably frustrating and has been going on for FAR TOO LONG

STOP FOR CHRISTS SAKE

**Comment by xylographe** [comment]
@heforfree 
`SE-3.4.10.227-crash3.7z` in [this folder](https://www.dropbox.com/sh/thgk5507tteg6ze/AABgb8jgWBnz9LLgDHsECfika?dl=0) might fix [crash3](https://gist.github.com/heforfree/34938615ed7a11341275).

**Comment by heforfree** [comment]
@xylographe
thank you fixed

**Comment by xylographe** [comment]
@heforfree 
`SE-3.4.10.227-crash4.7z` in [this folder](https://www.dropbox.com/sh/thgk5507tteg6ze/AABgb8jgWBnz9LLgDHsECfika?dl=0) might fix [crash4](https://gist.github.com/heforfree/9d931891b74bb8d17464).

**Comment by heforfree** [comment]
@xylographe thankyou i can not reproduce maybe fixed.it happen on performing ocr
in a different part of subidx file.perhaps fixed
