### ISSUE TITLE
NetFlix subtitle support

### ISSUE THREAD

**Issue by agabrielluz** [SubtitleEdit/subtitleedit#1511]
I'd like SubtitleEdit to be able to edit DFXP or maybe save it to SRT. DFXP is the format used for subtitles on NetFlix platform. Important: DFXP is NOT a proprietary format since is actually an internet standard.

DFXP subtitles information (https://en.wikipedia.org/wiki/Timed_Text_Markup_Language)
Script to convert NetFlix subtitles to SRT
https://github.com/isaacbernat/netflix-to-srt

**Comment by niksedk** [comment]
Have you tried "Time Text 1.0" ?

**Comment by agabrielluz** [comment]
No, I will give it a go as soon as I get home. :) Don't close it now, please.

**Comment by niksedk** [comment]
@agabrielluz: Did you get a chance to test it?

**Comment by agabrielluz** [comment]
I`m gonna test it right now :)

**Comment by agabrielluz** [comment]
Sorry. Can't test it. It looks like NetFlix subs are now encrypted, so I can't test it. You can close it now.

**Comment by felagund** [comment]
Well, the difference between timed text and dfxp is that dfxp timecode goes like this:

<p style="style.default" region="region.after.center" begin="00:00:04:23" end="00:00:06:14">Owene, co na něj říkáš?</p>

Timed text goes like this:
 <p begin="4.962s" xml:id="p2" end="6.589s" region="region.after.center" style="style.default">Owene, co na něj říkáš?</p>

so instead of 00:dd:mm:ss:ff it uses decimal seconds. I am not sure if it is important or not.

**Comment by felagund** [comment]
(other differnce is inclusion of xml:id="p2" part in the timed text )
