### ISSUE TITLE
Multiple Replace

### ISSUE THREAD

**Issue by ivandrofly** [SubtitleEdit/subtitleedit#1590]
I think there should be a message prompt (Confirmation) to notify user when Remove all (Replace Expressions) is clicked

**Comment by xylographe** [comment]
Should you click "Remove all" by mistake, you can click "Cancel", and re-open MR.
But don't use the close box, because that would copy the new empty list.

**Comment by ivandrofly** [comment]
> Should you click "Remove all" by mistake, you can click "Cancel", and re-open MR.
> But don't use the close box, because that would copy the new (empty) list.

Oh yeah, I know you can do that, I just think it would be nicer to have a confirmation dialogue-box...

**Comment by aaaxx** [comment]
Among other things, a lot of ambiguities like this one could be solved by using action verbs on buttons like it's done on Mac, instead of OK/Yes/No.

This "OK" button could be renamed to "Replace".

![save_dialogs 1](https://cloud.githubusercontent.com/assets/6186480/14537778/bd5cac2c-0278-11e6-87bb-bf1bfaf03565.png)

**Comment by xylographe** [comment]
@ivandrofly 
It would be rather inconvenient when you want to replace all rules ("Remove all" + "Import").

@aaaxx 
Agreed. "Replace" would be better than "OK".

“No thank you” to Mac. I don't want to be treated like a five year old by a computer program. :)
But, the layout of buttons (the destructive one separated from the others) is a real improvement.
