### ISSUE TITLE
[BUG] Language parsing in idx/sub: files with only handpicked tracks extracted

### ISSUE THREAD

**Issue by aaaxx** [SubtitleEdit/subtitleedit#1676]
When loading idx/sub files that contain only some of the subtitle tracks that were present on the DVD, all tracks except the first one or the first few consecutive ones are marked as "Unknown language" (by "first" I mean as they are ordered on the source DVD, not in the extracted file). [Here's a test sample](https://app.box.com/s/8bjxgqtanqhhz2z0enb52qqw8odsbz61).

**Comment by xylographe** [comment]
I think this happens because the [Idx parser](https://github.com/SubtitleEdit/subtitleedit/blob/master/libse/VobSub/Idx.cs#L10) ignores language indices. In [line 68](https://github.com/SubtitleEdit/subtitleedit/blob/master/libse/VobSub/Idx.cs#L68) it should probably use the language index from the idx file i/o `Languages.Count`.

**Comment by xylographe** [comment]
I think [SubtitleEdit-3.4.12.117-issue1676.7z](https://www.dropbox.com/s/m9crn2sfmcf2zzq/SubtitleEdit-3.4.12.117-issue1676.7z?dl=0) should fix it. But I only did a quick test with your test sample. More extensive testing would be welcome.

**Comment by xylographe** [comment]
BTW assuming you are using Croatian translation, you should see “Nepoznat Jezik”. Anything else would be another bug. :)

**Comment by aaaxx** [comment]
I tried it with a few more files and it seems to be working fine.
