### ISSUE TITLE
Request: Idea for an advanced auto sync

### ISSUE THREAD

**Issue by solipsist01** [SubtitleEdit/subtitleedit#1697]
Imagine the following feature :)

Subtitle edit can open a videofile, and makes a srt file based on voice recognition.
This file will have correct timings, but the text it created will be far from perfect. Like 20% of the words and sentences will be right.

There exists an SRT file with the right translation, but incorrect timings.

Subtitle edit will compare both SRT files, and will find similarity in the translations.
It will sync the incorrect timings of SRT file, based on the timings of the autocreated SRT file.

In my opinion, syncing automatically this way would have a perfection ratio of 100%

**Comment by aaaxx** [comment]
YouTube can do this right now. Upload a low-quality private video and add a transcript, and YouTube should automatically sync it with the video.

**Comment by niksedk** [comment]
It would be a nice feature... does anybody know if Google is using an open source project?

**Comment by kaegi** [comment]
I've uploaded a project called [aligner](https://github.com/kaegi/aligner), which automatically syncs a subtitle to a reference subtitle. It will find offsets and where to set/remove advertisement breaks. It has a sophisticated algorithm, and will not choke on missing lines, extra lines or splitted lines. The algorithm does not use context information (only timestamps) and therefore works for any language or even image-based subtitles.

FFmpeg can do a scene/cut detection with

```bash
ffmpeg -i $VIDEO_FILE  -filter:v "select='gt(scene,0.4)',showinfo"  -f null  -
```

and if these timestamps are feeded to `aligner`, the corrected subtitle will probably right in most cases (the ffmpeg+aligner part is not tested though).

The project is written in Rust, but the library API is [very minimalistic](https://docs.rs/aligner/0.1.1/aligner/fn.align.html), so that writing a C/C# interface shouldn't take long for the developers here.
