### ISSUE TITLE
OCR screens need redesign

### ISSUE THREAD

**Issue by adem0x** [SubtitleEdit/subtitleedit#171]
I couldn't think of a better subject line; I am sorry if it came across a little harsh.

Please spare some time to with the OCR screens.

First problem: OCR image is displayed in all sorts of shapes and sizes. Could you not make sure the OCR image stretches to fit the available image are --as opposed to current behavior of the form expanding to fit the OCR image.

Second problem: The OCR'ed text (memo) box is usually too small. Plus, it uses a font that is also too small for my eyes. I would love to be able to change the font, and have a large enough text (memo) box. It needs to be able to show all the OCR'ed text even if it is more than a few lines.

Finally, a dialog that comes up for correcting OCR mistakes/errors is rather annoying. Couldn't you make it part of the main OCR window?

**Comment by taxen** [comment]
I would rather use this thread since this is still open.

I do not totally understand what the first problem of adem0x is, but here is mine.

When OCR hits a characters like (",), it often separate (") into (') and (').
There is no way to expand backward, not expand forward or shrink backward. The start point is fixed.
This is problematic. When OCR recognize (",) as (') + (',), then the only option is to shrink (',) to (') and (,).
There is no way to combine the first (') and the second (') to make one (").

I want to have three buttons here.
Shrink Selection, Expand Selection, and Move back.
Or... in better order, Expand Backward, Shrink Selection, and Expand Forward.

![se02](https://user-images.githubusercontent.com/3875423/63815230-cc23e200-c96e-11e9-88be-6b3d8c8a2bb1.png)
When hit such case, the only way to edit is go further right

![se03](https://user-images.githubusercontent.com/3875423/63815239-d645e080-c96e-11e9-9e6f-5a4bd500f7a6.png)

like this... or shrink the right edge to the left.

![se01](https://user-images.githubusercontent.com/3875423/63815250-dd6cee80-c96e-11e9-89a2-3b866d28aa4b.png)

There is no way to move the left edge to fix the bad recognition.

**Comment by darnn** [comment]
Yeah, this is a problem with Hebrew (and presumably other RTL languages) as well.

**Comment by niksedk** [comment]
Good idea with the "move back" button - I normally close the dialog, double click on the line, and fix it from the inspect window or a sub window (but that's a workaround)

**Comment by taxen** [comment]
Yes, I do so too sometimes. It fixes the problem for the time being, at least for the characters at the moment. But, eventually, the workaround comes to a point where the fix does not work. This is because separated data is also registered after a while. For example, when (",) is registered as one character in Edit DB window, it works for (",) for a while. But when (') is registered and matches a part of (",) (which often does), (",) is again recognized as (') + (',). So, maybe my proposal does not mean much. Even so, I think it better to have "move back" button in the window.

BTW, why italic characters are so hard to be separated especially after "r" and "f" ? I have made lots of "their***" -> "their ***" and "of***" -> "of ***" OCR fix list. This problem is not solved by adjusting No of pixels in space. I usually set it 11. When set smaller than 11, like even 8, the un-separated words still un-separated, while should-not-be-separated words separated. I know it is hard to deal with the problem, because I once made my own OCR program. So, here is my suggestion. Right now, vertically straight frame to cut out each character is used even for italics, I think. Why not using properly tilt frame for italics or modifying image to normal?
