### ISSUE TITLE
Extracting subtitles from VOB

### ISSUE THREAD

**Issue by einthusan** [SubtitleEdit/subtitleedit#1867]
When I play the DVD (vob files) on VLC or Media Player classic, the subtitles are synced correctly. When I try to extract the subtitles from the VOB in order to create a .SRT file, which does work, however, adding that subtitle track back into VLC while playing the original VOB file does not sync correctly.

I have even tried using many other softwares to encode the DVD to mp4 and tried adding the ripped .SRT file, but as usual, the sync is totally off.

Is this a known issue and if not, what are the next steps?

**Comment by niksedk** [comment]
You could sync the srt file with the VOB file e.g. via Sync -> Visual Sync...

If you could supply the VOB file someone could look at the file. The DVD stuff can be pretty complicated.

**Comment by aaaxx** [comment]
This is actually an issue with the MPEG-2 format that DVDs use. It has some weird way of keeping track of frames or timecodes internally which seems to trip up video players and they can't keep external files in sync. In my experience, they usually start all right and get progressively out of sync as the film goes on or get completely messed up if you jump to different points.

This is also why you can't time subs directly to a DVD in most cases and need to work with a transcode instead.

I don't know why it didn't work for you with MP4, though. Could it be that you just muxed it without actually encoding, since MP4 is just a container format?

What usually works for me is ripping the DVD to MKV using [MakeMKV](http://www.makemkv.com/) (you need a [key from their forum](http://www.makemkv.com/forum2/viewtopic.php?f=5&t=1053), and they occasionally update it). It somehow manages to solve the sync issues, unlike MKVToolNix and other muxers.

**Comment by einthusan** [comment]
@niksedk I am trying to avoid having to do manual syncing (visual sync) unless that is automated.. I haven't tried assuming it was manual sync process. My theory is that if the DVD player can show the original video with properly synced subtitles, then why are "extracted" subs not syncing with either the original VOB or my muxed MP4 file.

**Comment by einthusan** [comment]
@aaaxx Thanks for your detailed reply. I was actually starting to believe that this is a DVD player glitch that DVD distribution companies are using to circumvent ripping of the movie subtitles. Your answer somewhat supports that theory.

I have been encoding MP4 for several years. I am pretty sure it's not an error on my end. From over 200 DVDs I have archived, only a few have this issue.

Will MakeMKV covert a full DVD into an MKV file including subtitles (I am assuming it will correctly be synced once done).

**Comment by aaaxx** [comment]
It will repackage the DVD into MKV and [you can choose which tracks to keep](http://www.makemkv.com/images/sshot-s2-web.png), including the subs, but they will obviously be image based like they are on the DVD. The sync has always turned out fine for me with this method, as I mentioned in my previous comment.

If you want to add external subs, you'll have to add them separately to the resulting MKV file (using MKVToolNix or something).

**Comment by einthusan** [comment]
@aaaxx thanks :) will try and update soon. Really helpful.
