### ISSUE TITLE
Some fonts mess up and weird when export to blu-ray sup and vobsub

### ISSUE THREAD

**Issue by marb99** [SubtitleEdit/subtitleedit#1918]
Some fonts mess up and weird when export to blu-ray sup or vobsub

fonts like "Calibri"

look for the letters "ti", "fi"

this problem of bonded letters does not happen using the same font "Calibri" in other applications like Word or notepad or using ffmpeg to hardcode subs "ass"

tested in SE 3.4.13, build 281

![1](https://cloud.githubusercontent.com/assets/7856897/17903957/4793e40c-6965-11e6-87de-96f0d1d4efa1.PNG)

![2](https://cloud.githubusercontent.com/assets/7856897/17903966/4fd5e228-6965-11e6-8d05-bdf5898aa75c.PNG)

**Comment by niksedk** [comment]
I don't think SE has anything to do with this...

**Comment by marb99** [comment]
but only happens with SE

is this problem of VS Studio or c# language?

**Comment by aaaxx** [comment]
They're not messed up; those are typographic details called [ligaures](https://en.wikipedia.org/wiki/Typographic_ligature). They're an OpenType feature in professional fonts, so, @niksedk, whatever library you use for rendering, seems to have them on by default.

Generally, it's best to leave them turned on because they prevent awkward letter clashes. But if you ever add a letterspacing option (also called "tracking") they must be disabled for non-default spacing.

**Comment by marb99** [comment]
@aaaxx 

thanks for the info ;)

@niksedk 

please can you explain how to disable ligatures on calibri font?
