### ISSUE TITLE
Any way to auto translate/replace quote symbols?

### ISSUE THREAD

**Issue by rhazor** [SubtitleEdit/subtitleedit#2192]
E.g. default quotes are known as simple "word", but e.g. Lithuanian quotes are „word“ and it is well known that e.g. in software like Microsoft Word language-related editions (e.g. in Lithuanian Word edition) the quotes are auto-replaced to native.

Would be nice same to be possible in CTRL+Shift+F with Lithuanian language selected. That it would find all opening and closing "word" quotes and replace them to „word“.

Keyboard shortcuts for Lithuanian quote symbols are ALT+0132 (opening „) and ALT+0147 (closing “).

Same would apply to Lithuanian dash ALT+0150: – (not -). But in this case it should have to somehow ignore the dashes that contain multiple line dialogs that open with a dash. I'm OK finding them and replacing manually, but then again, somehow CTRL+F also needs to ignore the opening dashes for faster search :)

Cheers

**Comment by aaaxx** [comment]
I've got a few regexes that I use for this kind of stuff. Will post them when I get home.

**Comment by aaaxx** [comment]
Sorry about the delay.

For double quotation marks, go to <b>Edit → Multiple replace…</b> and add this to a new group called, for example, “Curly quotes – Lithuanian”:

Find what | Replace with | Search type
--- | --- | ---
`(?<=(^|[ \n]))((<[ibu]>)*)"` | `$2„` | Regular expression
`"(?=([.:,;!?]+|(</[ibu]>)+)*([ \r\n]|$))` | `“` | Regular expression

The first one will replace a straight double quote that is either at the beginning of a line or comes after a space (and is optionally preceded by any combination of SRT tags `<i>`, `<b>`, `<u>`).

The second one will replace those that are either followed by a space or are at the end of a line (also optionally followed by any combination of SRT tags and `.:,;!?` punctuation).

**This will *not* find and replace all possible occurrences of quotation marks, but it will most. So, after applying it, find the remaining straight quotes and fix them manually.** If you want to be thorough, then instead of just searching for straight quotes, use this regular expression to also find the newly replaced curly quotes that are not next to a letter:

`"|„(?![A-Za-zĄČĘĖĮŠŲŪŽąčęėįšųūž])|(?<![A-Za-zĄČĘĖĮŠŲŪŽąčęėįšųūž])“`

This will find cases where, for example, a closing quote follows a number and might actually be an inch or arcsecond mark (you'd use a double [prime symbol](https://en.wikipedia.org/wiki/Prime_(symbol)) for those, or a straight qoute if your font doesn't include primes, which most don't – never a curly quote).

**Comment by aaaxx** [comment]
What about single quotes? [Wikipedia's list](https://en.wikipedia.org/wiki/Quotation_mark#Summary_table) doesn't mention them. Does Lithuanian use them for things like apostrophes and quotes inside of quotes?

And can you clarify what you want to do with the en-dashes? If you're going to go to the trouble of using proper typography, why would you leave dialogues marked with a hyphen instead of also use an en-dash or even an em-dash?

**Comment by rhazor** [comment]
Because the default dash is still used as a subtraction symbol and also used in physical books also for dialogs  and Lithuanian dash is used in grammar like explained before. So yeah, we use at least 2 types of dashes.

No, we don't use single quotes, so yeah single quotes also needs replacing.

**Comment by Yamato-ua** [comment]
Would this still work fine if I use it for Cyrillic quotes? 
Is it ok if I just replace „“ with «»?
And could you help me integrate also preceding {\an2} and {\an8} SRT tags in there?

Would appreciate it so much.
