### ISSUE TITLE
[request] compare subtitles more options

### ISSUE THREAD

**Issue by marb99** [SubtitleEdit/subtitleedit#225]
Hi...

is possible to add more options to compare subtitles.

example:
- be possible to copy text.
- transfer text from a sub to another (from side to side)
- move up and down lines
- edit both subtitles in place.

Compare subtitles is a great tool but is very limited.

I hope you can add more options to this great tool in SE

Thanks

**Comment by darkred** [comment]
Some more things:

- to be able to insert a line before/after a given line ( in either side)
- the 'Text' column to appear as the first of the right side, i.e. immediately after the 'Text' column of the left side
- the separator between the two side to become draggable, so that to be able to display the two 'Text' columns as close as possible.
