### ISSUE TITLE
Feature request: [List View] Moving Line Up/Down

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#2252]
Based on a much similar old open request #406, I may appreciatively request the feature to allow moving line up and down (I mean texts only, no time codes changed).

This is very useful for the workflow that first import texts then tweak timings, because sometimes the text order of two adjacent lines really need to be re-ordered or switched due to negligence on raw scripts.

The real pain here is: Each time that I want to switch the texts between two lines, I have to first cut all texts in one line, then append it into another, then cut  the texts in this second line then paste back to the first line. Yeah, believe me, it's a real pain.

So I wish we could have a **Move Selected Line Up/Down** on the context menu, or, even better, expose it as a customizable shortcut setting. That would be a holy moly time saver! :1st_place_medal:

**Comment by darnn** [comment]
Wait, so, just out of curiosity: Are you importing plain text, and using the "generate time codes" option? Or are you working with timed subtitles where somehow one subtitle has the timing on the next and vice versa?
If it's the former, and the timings are basically rudimentary, you can save yourself some work by switching the focus to list view, cutting (via ctrl+x) the subtitle you want, moving two subtitles up and pasting it:
![se subtitle move1](https://cloud.githubusercontent.com/assets/19672444/23344521/b7c928e0-fc86-11e6-8d0d-35329f73a4e0.gif)

If for some strange reason it's the latter, I can suggest a temporary (and convoluted) workaround. I use a text expander that can also send keystrokes (specifically, Breevy) to achieve what I describe here: https://github.com/SubtitleEdit/subtitleedit/issues/2249
So if you're on Windows (since I can't vouch for this elsewhere), and you can be bothered to buy and install Breevy, you can create an "abbreviation" that would be, e.g., "space, A, A, space", so something you wouldn't necessarily expect to type, and which would send the series of keystrokes to select all the text in the text field, cut it, move to the subtitle above, go to the beginning, paste, then select everything from the cursor to the end of the subtitle, cut, move to the subtitle below and paste. For reference, here's the sequence of keys I send in order to bring a word up from the second line of a subtitle to the first:
%(Key Down)%(Key Home) %(Key Up)%(Key End)%(Key Delete)%(KeyDown LCtrl+LShift)%(Key Right)%(KeyUp LCtrl+LShift)%(Key Right)%(Key Delete)%(Key Enter)%(Key Up)%(KeyDown LCtrl+LShift)%(Key Left)%(Key Right)%(KeyUp LCtrl+LShift)%(Key BkSp)%(Key Down)%(Key End)
(Although bear in mind that it is suited to Hebrew, which is right-to-left, and doesn't work with any language that's left-to-right.)

**Comment by LeonCheung** [comment]
Thank you for the idea. Yeah, the workflow is to import texts first, then coding times while playing. I just thought this can be a must-have feature, and seems not that hard to implement, doesn't it? I just made a prototype demo:

![666](https://cloud.githubusercontent.com/assets/494788/23347338/ac717fc8-fcdc-11e6-8ba0-8f65625f6fa5.gif)

NOTE: It should make sense to only move texts, and no timing things changed. That's it.  :)

**Comment by LeonCheung** [comment]
Btw, some sub software uses method like this:
![aa](https://cloud.githubusercontent.com/assets/494788/23387542/31525224-fd98-11e6-9296-ae8cea094ad7.gif)
Not sure if it is better or possible in SE. Anyway, just a quick note here.
