### ISSUE TITLE
Feature request: Import .html from ABBYY FineReader 9/11/12 in .srt

### ISSUE THREAD

**Issue by Elheym** [SubtitleEdit/subtitleedit#2267]
Source pgs, samples, and blanks - https://cloud.mail.ru/public/LNrc/HwDvCugd9
Video with some examples/explanations - https://cloud.mail.ru/public/JF24/pv92MCdwT

In all cases, we need the ability to use two modes: single file and "Multiple files - one file is one subtitle" like in the form "Import plain text" but yet with uploading timings.

**Comment by darnn** [comment]
Wait, can I ask what you're even trying to achieve by OCRing the file through ABBYY? Why not just use, say, SupRip? http://exar.ch/suprip/

**Comment by Elheym** [comment]
@darnn : Improve the quality of recognition, of course. Moreover, I use it everyday. So for me it's so important, in order not to lose a lot of time.
SupRip? You must be kidding... In most cases, it is inferior to FineReader. FineReader more precisely (especially in italics), faster as it automatically detects, has the support of the dictionary and therefore do not have to spend a lot of time to fix "I" & "L". These benefits I have to use FineReader and not ancient SupRip. :)

**Comment by darnn** [comment]
It always seemed to me to be more trouble than it was worth to convert the sup file, import the results into ABBYY and then export the text, but to each his own. But then, what is it that you want Subtitle Edit to do, other than to support "one file is one subtitle" mode? It seems like it already does everything else you'd need, doesn't it?

**Comment by Elheym** [comment]
Actually, no, not doing all that is necessary. Otherwise what's the point to ask something that is already there... ready to get subtitles you need to use three different programs. One extracts the timings and image, and the other recognizes, and the third combines the recognized text and the timings. You think this is comfortable?..
@niksedk : What do you say?

**Comment by darnn** [comment]
Oh, I just mean, like, I don't think that's comfortable, but you'd still need to do all that even if Subtitle Edit could parse FineReader HTML. You still have to extract the images and the timings, and you still have to OCR in FineReader. Also, you don't seem to be preserving any of the formatting (italics, etc.) using the method you demonstrate in the video, so I don't understand why you don't just save your FineReader document as plain text and import that directly. I'm not trying to be critical, I'm really just trying to understand the benefit of Subtitle Edit parsing FineReader HTML versus just importing the plain text which you can obtain from FineReader.

**Comment by niksedk** [comment]
The Import plain text now also supports input as html - so if a .html file is dropped only the text will be imported (it's not specific for ABBYY FineReader html but hopefully it works too).
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.2/SubtitleEditBeta.zip

**Comment by niksedk** [comment]
And the beta was updated due to a missing new line - see e964b720dd4bed8cab8da1c3d4c4e0741d185da7

**Comment by niksedk** [comment]
@Elheym: Did you have a change to try the above beta?

**Comment by Elheym** [comment]
@niksedk : yep, I have a try, thank you so much! In general, all is well. Sometimes confused by the formatting of rows: number of rows is different from the original. But yet this is not critical. Thanks again!

**Comment by Elheym** [comment]
Test for some time and was confronted... with the disparity between the number of rows.
Video: https://cloud.mail.ru/public/6gtr/eynUzu31p
Source: https://cloud.mail.ru/public/9Jzy/YAtPc15Y4

**Comment by niksedk** [comment]
Did you use "Split at blank lines"?

**Comment by Elheym** [comment]
Yes, tried each of the options. Unfortunately none of them gave the desired result. If you use "Split at blank lines", it turns out 1554 whereas in the source code 1325. I can't even imagine how there are 229 additional lines.

**Comment by darnn** [comment]
What's happening is that SE is parsing everything enclosed in `<p>` tags as a single subtitle, but that's not what's actually happening in Finereader's HTML output. Subtitles like this are fine:

`<p><font face="Arial" size="4">MAN: Get in front<br>of that wall!</font></p>`

Because the line break is represented by a BR tag, but subtitles like this are not:
```
<p><font face="Arial" size="4">My arm!</font></p>
<p><font face="Arial" size="4">I've been shot!</font></p>
```
Since that's supposed to be one subtitle with two lines, and not two separate subtitles.

Like I said above, if you're stripping all the tags when you're importing the file into SE anyway, I don't see why you don't just save your Finereader file as plain text to begin with, since it would be much easier to import it that way.
If you want to keep the italics, bold, etc., you can just use this one regular expression that will strip all the rest but keep those:
`<p>|</p>|<font.+?>|</font>|<hr>`
(I'm not a big regex expert, this works in EditPad, but I'm sure you see what I did there and could adjust it to your text editor if need be.) Then you just need to remove the HTML from the top and the bottom of the file, and replace the BR tags with actual line breaks, and you can import what's left through "import plain text" the regular way:
![sehor](https://cloud.githubusercontent.com/assets/19672444/24337025/bf1e99f6-12a0-11e7-97ad-e4dd62df620d.png)
And here's the actual file:
https://www.dropbox.com/s/59ahshbmrsk0au8/testt.html?dl=1

**Comment by Elheym** [comment]
@darnn Thank you for the explanation. Necessary to clean the text from unnecessary until only the text italic. Exactly. The regular expression performs all necessary. Yeah, I know that you can save a "plain text". No matter how fast you do it, SE can do it almost instantly. Therefore to save time is equally important. I hope you will understand me. =)

**Comment by Elheym** [comment]
@niksedk Would you like to make some corrections/additions to the existing code. For example, as suggested by @darnn :  
` <p><|p>|<font.+?>|</font>|<hr>`

What do you think?
