### ISSUE TITLE
Some paragraphs flickers in video preview

### ISSUE THREAD

**Issue by ghost** [SubtitleEdit/subtitleedit#2468]
Problem:
Some paragraphs flicker in video previews.
Solution:
In UiUtil.cs:
In ShowSubtitle Methode
change:
string text = p.Text.Replace("|", Environment.NewLine);
To:
string text = p.Text.Replace("|", Environment.NewLine).TrimEnd ('\n', '\r', ' ');

This prevents  the condition videoPlayerContainer.SubtitleText != text
From being true just because there is some empty lines in the end of the paragraph.

Once again:
I made many changes, fixed bugs, and added new features. I want to share the modified code with you. How?

**Comment by niksedk** [comment]
@MohammadHamdyGhanem: Hi, sorry about the late answer. 
You can clone the source code via Git (download Git for windows) and make a branch + a pull request for each feature/fix. For more info Google "Git" and also see here: https://help.github.com/articles/creating-a-pull-request/

If you made the above change as a PR (pull request) then ppl could/would review it and make suggestions - e.g. I would suggest just using "TrimEnd();" for the above fix.

Note that not all features are wanted in SE - if a feature it too far out of scope then a plugin can be considered. E.g. video editing is out of scope for the main SE repository.

Hope this helps - and do write if you have problems with Git.

**Comment by MohammadHamdyGhanem** [comment]
Thanks for your reply:
I needed to modify the previewed text on the video player, not just to trim empty lines, but also to adjust some symbols to fit right-to-left displayed text (Some subtitle makers write punctuation symbols in opposite direction in order to look correct in video players). This causes the flicker again. I found that the solution is to create a property called LastText in the VideoPlayerContainer class, and assign to it the actual paragraph text before any modification. In UiUtil.ShowSubtitle I used this property like this:
else if (videoPlayerContainer.LastText != text)                                videoPlayerContainer.SetSubtitleText(text, p, subtitle);

About Editing the Video:
I found it very logical to add this function, because the ability to modify the subtitle with the edited video. I was suffering to adjust subtitles manually in a separate step to synchronize it to the new modified video. So, I modified you app to give me all in one:
1- An easy and enjoyable video player:
    I add new buttons and keyboard shortcuts to control panel to control play rate and other functionality. I changed the way you go on or off Full screen mode to make the transition faster and smooth. I added an easy fast way to sync. current video position to current selected paragraph in the list. When user presses Ctrl+Y and confirms the warning message, I calculate the time difference and  apply it to the selected paragraph and next ones until the end of selection (or end of the List if there is only one selected item). And many other changes.
To achieve these goals, I hade to rebuild the controls panels in an OOP fashion. I created a class to represent controls-panel buttons and another to represent control bars . This makes code shorter, clearer, and easier to modify. This allowed me to add new 6 buttons to control panel with minimal code.
I also needed to make the subtitle panel background transparent, not to hide a large portion of the video. Then I needed to draw a black background behind each line so the eye can recognize it on bright video. Download the new RTFViewer from here:
http://www.mediafire.com/file/az6ed6pzbb5oesx/TransRTFViewer.zip 
2- An easy and time saver video editor to allow user to put and modify cut markers while watching the video.
3- Your comprehensive subtitle editor, that allow users to modify and correct subtitle while watching the video, and save modified subtitle with the edited video.
By the way, I created a new customizable TimespanPicker control that can replace your TimeUpDown control. Download it from here:
http://www.mediafire.com/file/kaz78uo7acm2uuo/TimeSpanPicker.zip

I will be happy to collaborate with you if you want to adapt any of these modifications. An app that can booth edit subtitle and video is a new one.
Thanks.
