### ISSUE TITLE
Is it possible to compile the project on Linux?

### ISSUE THREAD

**Issue by lucobe** [SubtitleEdit/subtitleedit#2510]
Hello, I want to develop a plugin to perform translation and synchronization of subtitles, but I use Linux Mint currently, is it possible to compile this project in Linux?

**Comment by niksedk** [comment]
Have you tried Mono develop?

**Comment by hlcb91** [comment]
Hello, I was going to open this issue because some errors happened when trying to compile with MonoDevelop, I needed to perform some additional steps to be able to compile successfully.

1 - Download the **NuGet.exe** file and put it inside the .nuget folder
2 - Correct the name of 3 files that are wrong (**AddWaveform.cs**, **AddWaveform.resx**, **AddWaveform.Designer.cs**)
3 - The bat file **build_helpers.bat** in Linux does not work, however if you edit the file and put the string `wine cmd / c` before the bat file execute correctly

The folder of the subtitle edit repository in my system is located in /home/gaia/tmp/git/subtitleedit_/, inside that folder I created a shell script **linux_fix.sh** and then execute it like this:

`bash /home/gaia/tmp/git/subtitleedit_/linux_fix.sh`

```
#!/bin/bash

main_folder=$(dirname "$0")
src_folder="${main_folder}/src"
src_dot_nuget_folder="${src_folder}/.nuget"

mkdir -p "${src_dot_nuget_folder}"
cd "${src_dot_nuget_folder}"
wget -c "http://nuget.org/nuget.exe"
rm -f "NuGet.exe"
mv "nuget.exe" "NuGet.exe"
chmod +x "NuGet.exe"

cd "${main_folder}"

sed -i -- 's/AddWaveform\.cs/AddWaveForm\.cs/g' "${src_folder}/SubtitleEdit.csproj"
sed -i -- 's/AddWaveform\.resx/AddWaveForm\.resx/g' "${src_folder}/SubtitleEdit.csproj"
sed -i -- 's/AddWaveform\.Designer\.cs/AddWaveForm\.Designer\.cs/g' "${src_folder}/SubtitleEdit.csproj"

sed -i -- 's/Command\=\"%22\$(SolutionDir)\.\.\\build_helpers\.bat/Command\=\"wine cmd \/c %22\$(SolutionDir)\.\.\\build_helpers\.bat/g' "libse/LibSE.csproj"
sed -i -- 's/Command\=\"%22\$(SolutionDir)\.\.\\build_helpers\.bat/Command\=\"wine cmd \/c %22\$(SolutionDir)\.\.\\build_helpers\.bat/g' "src/SubtitleEdit.csproj"
sed -i -- 's/Command\=\"%22\$(SolutionDir)\.\.\\build_helpers\.bat/Command\=\"wine cmd \/c %22\$(SolutionDir)\.\.\\build_helpers\.bat/g' "src/Win32Resources/Win32Resources.vcxproj"

chmod --recursive +x *.bat
chmod --recursive +x *.exe
```

This shell script file when executed performs all the steps I mentioned above.

Below I'll leave screenshots of 2 errors that happened to me before I figured out how to fix it, maybe this would help @niksedk  to fix it.

The first error happened when I fixed the names of the files but I did not put them to run through wine cmd.

![screenshot_2017-08-10_18-25-21](https://user-images.githubusercontent.com/13703681/29193056-28403ea2-7dfa-11e7-87d6-518be0b07f53.png)

The second error happened after I edit it to run by wine cmd, then I ran the build_helpers manually by passing the "rev" and "Release", i created the file **build_helpers_rev_release.sh**:

```
#!/bin/bash

main_folder=$(dirname "$0")

wine cmd /c "${main_folder}/build_helpers.bat" "rev" "Release"
```

![screenshot_2017-08-10_18-27-43](https://user-images.githubusercontent.com/13703681/29193637-9090f6b6-7dfc-11e7-9579-61c015e438c0.png)

Note 1: I am using Linux Mint 18.2 and using MonoDevelop in version 5.10 of the official repository and I can now compile normally after running the script **linux_fix.sh**
Note 2: When trying to use the latest version 7.0.1 (build 24) that is made available through Flatpak I could NOT... because wine is not found in the PATH, I probably need to install wine within the MonoDevelop environment on Flatpak

**Comment by niksedk** [comment]
It's possible to compile with Mono develop - some project file editing is needed (remove .bat files)
Also see https://nikse.dk/SubtitleEdit/Help#compile
