### ISSUE TITLE
Translation Mode Shortcut not working

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2514]
Not really an issue.
More to a question. 
Is Translator Mode the same as Translation mode? 
And when I use the shortcut for "Toggle translation mode" shouldn't it let me select a file or is there a specific condition to it?

**Comment by darnn** [comment]
I'm not Nik, but fwiw, the keyboard shortcut has been broken for some time (see https://github.com/SubtitleEdit/subtitleedit/issues/2200). Use file->open original subtitle in the meanwhile.
Also, if you want to avoid issues of disparities between the original subtitle and the translated subtitle, the best thing to do right now is to open the original, select all, right-click on the subtitles in list view, and click column->delete text (or use the keyboard shortcut). Save the resulting file that has the same timings but no text, and then open the original file with "open original subtitle". Otherwise things like what I describe here (https://github.com/SubtitleEdit/subtitleedit/issues/2201) can arise under certain circumstances.

**Comment by OmrSi** [comment]
Shouldn't the shortcut just let you select a file? 
Now when I press it, it doesn't do anything at all.

**Comment by darnn** [comment]
I assume you're still talking about the keyboard shortcut. And yeah, it should, and it used to, but some change along the way made it stop functioning properly (as far as I can tell). Right now you just have to use "open original subtitle". It's a bit of a hassle to do it each time, but so it goes.

**Comment by OmrSi** [comment]
Yeah, I used to do that. 
Then u saw the shortcut and I tried to use it and it didn't work.

**Comment by OmrSi** [comment]
Is this a hard thing to fix?

**Comment by niksedk** [comment]
New beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip
