### ISSUE TITLE
Add Up - Down In Subtitle join

### ISSUE THREAD

**Issue by NoRRt** [SubtitleEdit/subtitleedit#2534]
Tools ---> Subtitle join ---> Select 2 subtitle in this section --- <Can not override subtitles (raise the subtitle to the first instead of replacing the first subtitle instead of the second subtitle)

See : http://i.imgur.com/TZdVIAi.png
Link 2 : https://image.ibb.co/mUkQ45/Untitled.png

**Comment by niksedk** [comment]
I'm not really sure why you need this... ?
Joining subtitles already in sync should not need this and if you have to combine two subtitles you should probably use Tools -> Sort by start time, after joining them.

**Comment by NoRRt** [comment]
To arrange subtitles

**Comment by 791** [comment]
This is still needed. There is no way to select the order. That alone renders this dialog useless. Worse it defaults to the least line text first which is second in order. It always adds them backwards and there's no way to fix order regardless of changing the titles. Please add a way to move the file order.

**Comment by LeonCheung** [comment]
@791 I guess you are requesting kinda " join and auto offset" feature. I don't think this is of much use since normally you cannot be sure that the 2nd sub starts right after the end of the 1st one, right? So, manual adjustment/offset can be unavoidable.

If you want to append subtitle file to the current one with expected offset, you can try set the cursor in waveform first, then right lick and choose "Insert subtitle here...".

**Comment by ridwan47** [comment]
Why is this still not implemented? This is absolutely annoying you havet get a different app to join subtitle competently.

https://i.imgur.com/XSLzYC5.png
