### ISSUE TITLE
Automatically add closed Bracket

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2555]
So, this is a little stupid. 
Maybe too much for a Subtitling program .
But,  here it is. 
Can you let it automatically add a closed bracket when opening one. 
These two tag bracket for example "{" and "<"
When you write { it adds }
I think you get the idea, like some programming programs.

**Comment by aaaxx** [comment]
This is tricky to get right, because the simple "dumb" implementation will bite you in the ass more than you think. I remember using Notepad++ before they used smarter bracket handling, and it was usually more annoying than helpful.

The way I see it, the very minimum for a useful implementation would be to restrict it to only the cases when there's a space or end of line after the caret. Oh, and manually typing the closing bracket should then probably be ignored, since most people will still do it by reflex.

For anything more complex than that, it would be a good idea to look at a few text editors, and see how they handle it.
