### ISSUE TITLE
List view focus color.

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2561]
when using RTL and pressing in the text box or wave form
you can't know which line is selected in the list because the color isn't clear.
![untitled](https://user-images.githubusercontent.com/20923700/30164535-8daa39fe-93e5-11e7-8768-c1562c2c06a4.png)

**Comment by niksedk** [comment]
Hm, I'm unable to make the list view behave better than this... if anyone can fix it, a PR is welcome :)

**Comment by darnn** [comment]
Oh, I'm sorry, I meant to reply to this sooner: Is there no way to change the background color itself into the color from LTR mode?
![se-color](https://user-images.githubusercontent.com/19672444/30378063-a2fe282e-989a-11e7-9f43-8360a0a3a938.jpg)

If not, maybe it would help to include a toggle for the two different ways of displaying colors? You turned off the LTR way in RTL mode at my request because it was messing up the layout: https://github.com/SubtitleEdit/subtitleedit/issues/2182

But maybe if the first way of displaying colors is helpful to some, it could be turned on/off?

**Comment by OmrSi** [comment]
I guess this is better than the original one.
