### ISSUE TITLE
original color changed

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2623]
so, i don't know if this is a future or a bug
i recently bought a laptop with 1050Ti Nvidia.
when i select a subtitle, the original text color changes is list view.
but the color disappears if i do any action, like deleting a line.
![screenshot 2](https://user-images.githubusercontent.com/20923700/32250066-c2d62f88-be93-11e7-96c1-f8aff746de12.png)

**Comment by darnn** [comment]
Okay, so, I understand what you mean now, and yes, that's been happening to me for months. I believe it was introduced with this (https://github.com/SubtitleEdit/subtitleedit/issues/2182) along with a bunch of other syntax coloring things, but it improved overall usability for me so much I didn't feel the need to say anything. Especially since, because the coloring is now handled totally differently, I assume it would be hard to get everything to behave the exact way it does with LTR mode's listview display.

**Comment by OmrSi** [comment]
It was fixed in latest betas, don't know how...
