### ISSUE TITLE
Request: "Add pair to OCR replace list" functionality to spell check part

### ISSUE THREAD

**Issue by Boulder08** [SubtitleEdit/subtitleedit#2678]
It would really be useful to have the option to add the correction you do to a list of automated corrections. Usually the same errors appear every now and then if you have similar subtitles like a seven-season TV series to process.

**Comment by darnn** [comment]
I haven't really done a lot of OCR through SE, so I don't really know if this is what you want, but check out settings->word lists->OCR fix list.

**Comment by Boulder08** [comment]
What I'm looking for is to be able to add the word pairs to that list while spell checking. Much faster and more convenient, and you don't need to remember the word pairs after you spell check some subtitle :)

**Comment by niksedk** [comment]
Is that the "OCR spell check" during the OCR process or the normal spell check ?

**Comment by Boulder08** [comment]
The normal spell check. There is the possibility to use the correction every time, but it applies only to the current subtitle.

**Comment by Ranger327** [comment]
I second this! There have been many times when I've wished I could easily add something the the OCR replace list while going through the spell check.

**Comment by Boulder08** [comment]
What about just like it is now, but add a new button to add the pair to the OCR replace list? Kind of "Change all" but "Change always" :)

**Comment by Ranger327** [comment]
Whether it's a button or in the context menu, either way as long as the functionality is there. However, I think it would be important to have it say "Add pair to OCR replace list" explicitly, rather than simply saying "Change always". The reason being one could interpret "change always" as being within just this current spell check.

**Comment by niksedk** [comment]
OK, but then an option to auto apply OCR replace list should also be available?

**Comment by Ranger327** [comment]
Ideally if you are halfway through a spell-check and you add something to the OCR-replace list, then that change would automatically apply to any future cases, including within that very same spell check. Otherwise, you would have to exit, then use the "fix common errors" to fix OCR errors, then continue on with your spell check where you left off. I wouldn't think it would need to be an "option" to auto apply OCR, in my mind it just makes sense to expect that the moment I enter something into the OCR replace list, it will fix itself automatically from there on out.

**Comment by Boulder08** [comment]
I agree, if you add the pair to the OCR replace list during the spell check phase, it should also mean that the user wants to apply Change all as well so that the correction is applied to the subtitle that is already being spell checked.

**Comment by Boulder08** [comment]
Was this implemented at some point? I have enabled the 'Remember "Use always" list' but it does nothing when spell checking. It does not add the corrections if I make them and then choose Change all when the word not found dialog comes up, or the ones that are in the same dialog but in the suggestions box from which I choose Use always. I just had several items which were corrected utilizing the suggestions box (just missing spaces between common words) but none of them are in the OCR replace list.

**Comment by afigamli** [comment]
Hi. 
How come that I get these suggestions in the Fix Common error window in Subtitle Edit? 
I can't find this rule in the OCRFixReplaceList or UseAlways files.
![image](https://user-images.githubusercontent.com/82114224/113911065-0f8c3680-97c9-11eb-9d3a-ba9dd16f65de.png)
