### ISSUE TITLE
Why video autoplays on translation mode?

### ISSUE THREAD

**Issue by rhazor** [SubtitleEdit/subtitleedit#2688]
When in split screen translating mode jumping to next line with Shift+Enter the video starts playing automatically, but video play key is Enter+P.

It's impossible to work when video plays on every line jump. E.g. you're translating from English text and use video only for testing or corrections to get context.

Also on top of that it deletes text/makes it empty when jumping to next line that contains any translated text. Real annoying.

When video loaded it shouldn't play when jumping lines with Shift+Enter nor delete/empty the lines.

**Comment by niksedk** [comment]
You can just use <Alt+Arrow down> - but I will update the beta not to start playing.

I don't think SE deletes text/makes it empty...

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.4/SubtitleEditBeta.zip

**Comment by darnn** [comment]
For what it's worth, the text getting deleted might be related to this somehow, if it's being selected automatically and then a key is pressed: https://github.com/SubtitleEdit/subtitleedit/issues/2068

**Comment by darnn** [comment]
Since this also happens when you, for instance, select a subtitle in list view, switch to the textbox, and then press tab to go to the original textbox:
![se-autoselect](https://user-images.githubusercontent.com/19672444/34353170-51c95b0e-ea2f-11e7-9cfb-cc20fafdd2e1.gif)

To be clear, what's happening here is I click on a line in list view with the mouse, press ctrl+down to switch to the textbox (the text is now automatically selected), then press down to deselect the text, press tab to switch to the original textbox (the text is now automatically selected), and again press down to deselect it.
