### ISSUE TITLE
Overlaying subtitles

### ISSUE THREAD

**Issue by unusualcomputers** [SubtitleEdit/subtitleedit#2702]
Hi

a quick one I hope: is it possible to add background color to subtitles for a video with hardcoded subtitles in another language - while still working with .srt and not turning to .ass format?

Thanks

**Comment by aaaxx** [comment]
No, because the SRT format doesn't support that kind of styling. You would have to choose such display option in your player (most software players, like MPC-HC and VLC, support it, but hardware players probably don't).

So your options are to either use ASS or to export your subs to a Blu-ray SUP or Vobsub IDX/SUB, which are image-based formats (I think IDX/SUB should be supported by most hardware players).

**Comment by unusualcomputers** [comment]
thanks very much, very helpfull
