### ISSUE TITLE
Can't import time stamps from subtitles

### ISSUE THREAD

**Issue by Ninelpienel** [SubtitleEdit/subtitleedit#2747]
I want to convert a Blu-ray sup file to ass with Subtitle Edit and Abbyy. I exported all lines to PNGs and I did the OCR part with Abbyy. I saved the ocred text ass a text file and imported it in Subtitle Edit. How can I set now the timing from the sup files? When I try "File -> Import time codes" and choose the original sup file this happens: https://my.mixtape.moe/ehhguo.png

I also tried a sub/idx and the "BDN_Index.xml" file from the PNG export for the time stamps import. Every time the program show me this error.

Is this a bug? Did I do something wrong?

Regards.

**Comment by darnn** [comment]
The simplest way I know is: Open the SUP file (drag+drop or file->open) in SE. You will get a "Import/OCR Blu-ray subtitle" window. Click OK. You now have a blank file with just the timings. You can now save this file as, for instance, an SRT file, and import the timings from that into your text file without timings.
You may have to ensure the proper framerate is selected in SE before you do this - since I haven't experimented with it much, I'm not sure one way or the other.

**Comment by Ninelpienel** [comment]
Do you have experience with Abbyy? I have an other problem:

Sometimes Abbyy ignore some text in the files and make the area really small. https://my.mixtape.moe/pqxdww.png https://my.mixtape.moe/lmiztk.png

**Comment by darnn** [comment]
I'm afraid I don't have a solution for that other than going in and changing them by hand, which is a hassle. I would see about maybe merging the images of several subtitles into one file, with empty lines seperating them - I feel like it might not be setting the areas properly because some things are too close to the border of the image. 
Conversely, you can try taking the widest and tallest subtitle "page" in Finereader, selecting the entirety of the image as a text field, going to area->save area template, selecting all the pages in the thumbnail view on the left, and loading the template via "load area template". That way hopefully nothing will get cut off.

**Comment by aaaxx** [comment]
Yeah, do as darnn suggested: draw a text rectangle big enough for all subs, then use "Area > Save Area Template..." and then "Area > Load Area Template..." and choose to apply it to all pages when asked.

Also, when you draw the text area, right-click it and select "Text Function > Line Numbers" to keep the original line breaks.

And another thing, it's best to use "Plain Text" Document layout. All those "Formatted Text", "Exact Copy", etc., options might contain hidden characters when you export to text file, and they still won't help you keep italics.

* * *

And I see you're gonna get some messed up quotation marks, so you can use [this Multiple replace group](https://github.com/SubtitleEdit/subtitleedit/issues/2192#issuecomment-275832396) to fix them, since Lithuanian uses the same curly quotes as German. Just add this replacement rule at the top of the group to first replace all curly quotes to straight quotes, so you can easily find the ones that were missed by the replacement action:


Find what | Replace with | Search type
-- | -- | --
`[„“”]` | `"` | Regular expression

**Comment by niksedk** [comment]
Time code import could not load other than text based formats - improved somewhat in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.5/SubtitleEditBeta.zip
