### ISSUE TITLE
OCR skips random amounts of unrecognized words

### ISSUE THREAD

**Issue by rhazor** [SubtitleEdit/subtitleedit#2751]
Gibberish is passed as correct as you can see it's highlighted in green, no popup appears for random amount of lines.

![subtitleedit_2018-02-07_21-05-41](https://user-images.githubusercontent.com/22996586/35936291-7b0a68b2-0c4b-11e8-96ea-146eb5806dda.png)

**Comment by niksedk** [comment]
I think you need to add the spell check dictionary for OCR auto correction / spell checking - you have selected "None".

Also, it's easier for us to re-create this if you attached the sub.

**Comment by rhazor** [comment]
Still same (dark green line)

![subtitleedit_2018-02-08_17-41-28](https://user-images.githubusercontent.com/22996586/35982091-990f7b16-0cf7-11e8-8d77-7ecdbe2ea740.png)

Attached subs
[subs.zip](https://github.com/SubtitleEdit/subtitleedit/files/1707711/subs.zip)

**Comment by GulBroz** [comment]
Are the words detected by tesseract correct ? (I mean not the sentence, but each word individually; ie "Aš", "Vos" and "vaikinu" in your example).

If so, I fear there's not much to do but drop "OCR via tesseract" and switch to "Binary Image compare" (which I've done long ago), because - from what I understand - tesseract works at word level, so it "thinks" it has a match on a word (maybe with some punctuation around, as in your example), and put that in the output (notice that this is a correct word, and because of that, spell checking won't detect any error)... Problem is that it has a wrong match in the 1st place, but outputs a correct word, so there's no way to detect the error, unless your read all the lines one by one...

As I said I switch to "binary image compare" for that exact reason and trade the speed of tesseract (no need to learn each character) to the correctness of the output (or at least for errors that can be detected by spell checking).

**Comment by OmrSi** [comment]
@niksedk Seems to work fine with latest version:
![image](https://user-images.githubusercontent.com/20923700/79572126-135d0f80-80c5-11ea-89c9-1ccaec3b91b6.png)
