### ISSUE TITLE
I built a Video And Subtitle Edit (VASE) project based on SubtitlEdit

### ISSUE THREAD

**Issue by ghost** [SubtitleEdit/subtitleedit#2764]
Hi,
I've told you before that I add video editing capabilities to your SubtitleEdit. I'm using it for several months now, and added many enhancements. Finally, I uploaded the project to GitHub: 
https://github.com/MohammadHamdyGhanem/VASE
Sorry, I couldn't fork your project because I had difficulties to modify it. But I referred to this project and your website.
I hope you find some useful pieces in my work, even if you do not adapt the video capabilities.
For example: I allowed to raise  the volume above 100%. Video players allow that, and the only thing you need to do is to modify the volume bar to work between 0 and 500% or 200% or whatever you want.
I added shortcuts to make controlling the player easier, such as:
Alt+Right: Increse play rate by 10%.
Alt+Left: Increse play rate by 10%.
Alt+Up: Increse play rate by 50%.
Alt+Down: Increse play rate by 50%.
BackSpace: Move back to last video pos.
Enter: Stop playing, select current paragraph in subtitleListview, register a move-back point, and refresh video screen.
Ctrl+Y: Stop video and sync. selected paragraph in subtitleListview with current video pos, and apply the same time delay to all next paragraphs.
Ctrl+Shift+Up: delay currently displayed paragraph and all next paragraphs by half second.
Ctrl+Shift+Right: delay previous paragraph to start at current video pos, , and apply the same time delay to all next paragraphs.
Ctrl+Shift+Up: delay currently displayed paragraph and all next paragraphs by half second.
Ctrl+Shift+Down:
Ctrl+Shift+Up: advance currently displayed paragraph and all next paragraphs by half second.
Ctrl+Shift+Left: advance next paragraph to start at current video pos, and apply the same time delay to all next paragraphs.
Ctrl+]: Increase display font by 1.
Ctrl+[: Decrease display font by 1.

I also added a context menu that appears when right-clicking the controls bar. The important item in it, is the Video player submenu, which allow the user to change the video player without going to the settings.

By the way, I decreased the load time of the settings form, by loading system fonts names in a background thread after the main form shown.

I also added a Batch Translate menu Item to translate all the subtitle files in a chosen folder. This is helpful with TV series.

I advice you to make use of my modified VideoPlayer container code. I build some classes for the control panel, bars, and buttons and displayed the subtitle on a transparent RichTextbox on another transparent form. This looks better because it doesn't hide a large portion of the video. 

Feel free to use any of my code as you want.
Thanks.

**Comment by niksedk** [comment]
> I allowed to raise the volume above 100%. Video players allow that, and the only thing you need to do is to modify the volume bar to work between 0 and 500% or 200% or whatever...

Cool, that's sounds like something SE should have :)



>By the way, I decreased the load time of the settings form, by loading the system fonts names in a background thread after the main form shown.

I'll check that out too.


>I advice you to make use of my modified VideoPlayer container code

OK, I'll take a look.

**Comment by niksedk** [comment]
@MohammadHamdyGhanem: Which video players can raise the volume higher than 100% ? (VLC/Directshow/mpv/mpc-hc)

**Comment by MohammadHamdyGhanem** [comment]
VLC can. 
But mpc-hc and Directshow can't. mpc can raise voice to 200% from the context menu "Audio options". It will be nice if you find this command
I didn't test mpv.

**Comment by niksedk** [comment]
Ok, boost for vlc  and mpv added.

**Comment by ldgbc** [comment]
Hey thanks for the contribution. Hopefully some of those thing get implement. Audio Boost did so that good.

**Comment by MohammadHamdyGhanem** [comment]
Thanks @ldgbc 
About: "Right-to-left" 
Yes, I was modifing this for myself at beginnig. You can view the paragraph in the textbox from left to right by clicking (Right CTRL+Right Shift). It is a built in feature in windows.
You can view subtitle from Left right by clicking the context menu Subtitle/Right toLeft. It is a toogle menu. I can add an option to the Video settings tab to select the  flow default direction.

CTRL+ mouse wheel affects the video pos. I thought about adding Shift+mouse wheel to affect the volume, but I found it useless to use the keyboard and mouse at the same time. I avoided using the mouse wheel alone because I sometimes touch it accedentally so I get an undesired results!

I tried to right click on the video player itself, but it is an external window, and it has its own menu in Hc-mpc player.

I will continue to update VASE as a video player and editor. I can't copy every new feature from SE, but I'm interested in audio auto-subtitling. 
I made some new enhancements to VASE, most important ot them is to rise the vedio screen up to make all the black area under the video, so subtitles appear under the video and don't cover unnessary area of it.
You can download the latest exe from here:
http://www.mediafire.com/file/jjrqrfjw6j1jzh9/Video_And_Subtitle_Edit.zip
I advice you to use both VASE and SE:
Use VASE when you are watching vedios. You have many confortable features sauch as increasing the play rate. VLC doesn't destort the audio when increasing play rate. This saves me half of my time without losing the watching pleasure. You can also cut any un-wanted sceens, or revers the process to save some parts of the video. You can also adjust subtitle timin while watching.
Use SE when you are creating subtitles.
It will be nice if @niksedk adapts my new vedio features to SE, so we can have all in one, and continue updating one project.
Thanks.

**Comment by orbittwz** [comment]
did anyone forked VASE and updated it to 2020 release? really need that batch translate option which SE doesn't have...
