### ISSUE TITLE
Hebrew Problem: Can't start a sentence with a number

### ISSUE THREAD

**Issue by SubEdict** [SubtitleEdit/subtitleedit#2768]
Can't start a sentence with a number. The number will always jump to the end of the row. (Using SubRip in Windows hebrew: 1255)

eg. "99 red balloons." will show as "red balloons 99."
eg. (in Hebrew) 99 בלונים אדומים XX 
*the XX is where the 99 should have been.

I tried everything. Any help (or trick) will be appreciated.
All SE versions 3.5.5 inc.

**Comment by darnn** [comment]
First of all, make sure you're working in RTL mode (edit->right-to-left mode). Second, with the cursor in the textbox, press ctrl+shift on the right side of the keyboard to align the text to the right if you haven't already.
Also, make sure you've selected MPV as the video player (options->settings, video player, MPV), and checked "mpv handles preview text". At this point, in Subtitle Edit itself, you should see the numbers in their proper place:
![se-hebrew-numbers-1](https://user-images.githubusercontent.com/19672444/36207595-1cb3dfec-119f-11e8-9ede-72e8ce4a63b7.png)
Now, I assume what you mean is that they show up at the end of the line rather than in the beginning in external players, like this: 
![se-hebrew-numbers-2](https://user-images.githubusercontent.com/19672444/36207683-61e62462-119f-11e8-842b-ad7c47f276b2.png)
This can be solved by using edit->fix RTL via unicode control characters. After applying it, the result should be:
![se-hebrew-numbers-3](https://user-images.githubusercontent.com/19672444/36207861-f254413c-119f-11e8-85ba-b4a9cc5f7ea5.png)

Be advised that unicode control characters count towards the line length, so you might have 17 visible characters in a line, but it will be counted as 18.

**Comment by SubEdict** [comment]
Thank you for the fast and informative reply darnn.

Will try again (in the next hours) to change my Windows: 1255 (Hebrew) .srt file to UTF-8, maybe just for editing. I need to check if I can save the file as ASCII not Unicode because there's some VLC bug with Hebrew and Unicode UTF-8 (Strange arrows): 
![l79ii5t](https://user-images.githubusercontent.com/36477829/36210225-8aed90a0-11a6-11e8-8c45-bd7773b8337d.png
).

**Comment by darnn** [comment]
Huh! I didn't know it did that, I haven't tried using Hebrew subtitles with VLC in a while. Those arrows are in fact the unicode control characters. So, my suggestion to you would be to ask on VLC forums, or perhaps even submit a bug report, because unicode control characters shouldn't be visible. And also VLC should really have the option to display RTL language subtitles in RTL mode.
Pending that, your simplest options, as I see them, are: a. using MPC (or some other player, MPC is just the one that I tried that actually works), or b. saving the subtitles as ASS/SSA. You can do this out of Subtitle Edit itself (save as "advanced sub station alpha" or "sub station alpha").  ASS looks the way it should in VLC. You can also modify the ASS subtitles' appearance in Subtitle Edit by right-clicking on a subtitle in list view and selecting "advanced sub station alpha styles". But I always used to edit ASS subtitles in Aegisub, so I don't know much about that feature.

**Comment by SubEdict** [comment]
Good news!!! Everything now works great (Also saving back to Windows 1255 Hebrew so.. no bug in VLC).
Your solution and explanation was perfect. Thanks again man. Perfect! :)

**Comment by darnn** [comment]
Huh! Well, I'm not sure what you did, Hebrew 1255 doesn't show up for me in VLC at all, but I'm glad it worked out!

**Comment by SubEdict** [comment]
Hey Darnn. I just wanted to let you know what really happened.
While I was checking, I installed a new version of VLC 3 where the bug (Unicode arrows sign) was fixed and I just didn't notice that I was accidentally using UTF-8.

This means that it is **still impossible to write a number at the beginning of a sentence** when the encoding is on Windows 1255 in SE (While editing and saving as .srt).

So.. from now on I just leave the encoding in Unicode UTF-8.
BTW, I know that your ASS suggestion will probably will work also.

**Comment by darnn** [comment]
Ah, now I understand!

**Comment by Suburber** [comment]
Hi SubEdict,
Indeed, the UTF-8 solution is pretty good. But, if you wish to leave you srt subtitles files encoded as Windows 1255, and you want numbers to appear in the beginning of a line, you can type CTRL+] (right rectangular bracket) before the number. It adds the unicode control character without changing the entire file.
Just a little something I've learned over the years :)

**Comment by SubEdict** [comment]
Thank you Suburber. 
**That is perfect.** The search for 1255 solution has ended.
Long live CTR+].

So simple, so needed, so happy. :+1: 
Thanks again.
best regards
