### ISSUE TITLE
Save As bug

### ISSUE THREAD

**Issue by maknol** [SubtitleEdit/subtitleedit#2795]
Hi,
i have file - D:\Subtitles\TS\PORTO-2016.srt, when i open it and sync it with opened video - D:\Movies\Porto.2016.1080p.WEB-DL.DD5.1.H.264-Weibo\Porto.2016.1080p.WEB-DL.DD5.1.H.264-Weibo.mkv, dialog windows give me name to the original file and folder, not like previous versions to new folder and with video name.

**Comment by niksedk** [comment]
OK, this should be now be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip
It's actually a setting now - see Options -> Settings -> General:
![image](https://user-images.githubusercontent.com/1261331/36947068-42654826-1fc7-11e8-9340-d22424bded81.png)

**Comment by maknol** [comment]
Yes, now is OK. hank you!
