### ISSUE TITLE
asks to save changes when Closing an ANSI file without editing

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2900]
Here's a file to test: 
[Test.zip](https://github.com/SubtitleEdit/subtitleedit/files/1921898/Test.zip)

**Comment by mkver** [comment]
Based upon several observations I believe I have found what's going on here: SE thinks that the file has changed if the encoding that SE uses (SE tells you its current encoding in the dropdown menu where you can change the currently used encoding) changes (because SE detects that the new file has a different encoding than the one previously used be SE).
Notice that if you open an instance of SE without loading a subtitle, SE uses the default encoding for the default (empty) subtitles (this presumes that you do not have the option to start with the last file loaded set). If the default encoding is not the one that your file uses (or more exactly: the one that SE thinks that the file uses), there will be a change in the encoding currently used by SE and therefore SE thinks that the file has been modified. If you reopen the very same file again (without changing it), SE will no longer think that the file has been modified. If you now open another file that uses a different encoding, SE will think that this file has been modified; if you open the original subtitles again, SE will again think that is has been modified etc. UTF-8 is not special in this regard; you probably have UTF-8 as your default encoding so that you think that it only happens with other files, but that is wrong.
By the way: If you open a file in explorer (so not opening a file in an already running instance of SE), SE doeesn't think that the file has been modified (even if it has a different encoding than the default encoding). This is consistent with what I said above: SE probably directly initiated the encoding the file uses and never ever used the default encoding, so it didn't switch from one encoding to the other.

**Comment by niksedk** [comment]
Thx for the info :)

Yes, looks like an encoding issue. The `*`should now also appear even when no video is loaded.

**Comment by niksedk** [comment]
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
Tested. Working well. :)
