### ISSUE TITLE
A quick question about Regex 

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#2950]
Hi, I wonder how to use the regex replace feature to do things like this?

![example](https://user-images.githubusercontent.com/494788/41498016-199ae82c-7195-11e8-86aa-a1e1b9005b7d.png)

**Comment by LeonCheung** [comment]
I mean a single rule, I tried to use the "fix lines beginning with dash" in the Fix tool, but it seems can't handle the 3rd one in this case.

**Comment by mkver** [comment]
Use negative lookahead: `^-\p{Zs}*(?![^\n]+\p{Zs}-\p{Zs}*\S)`. Use this in the multiple replace tool as the behaviour of the simple replace differs from multiple replace.
Explanation: ^ matches only at the beginning of a line; "-" is simply the character "-" (notice that there are multiple different hyphens/dashes/minus symbols and my regex only captures one of them; if you use other hyphens/dashes you might need to adapt this piece as well as the later "-"). \p{Zs} is the Unicode horizontal whitespace character class (tabs not included -- if you use them, you have to modify this part) and \p{Zs}* matches all horizontal whitespace after the "-". Then comes the negative lookahead. It is a zero-length match (i.e. it simply says "matches" or "doesn't match", but when it matches, it doesn't add anything to the match (this means that we can simply discard the match (i.e. replace it with nothing) to get what we/you want)). The [^\n]+ means that we only search for a second " -" group on the very same line. The \p{Zs} in front of the second "-" exists so that something like "three-hundred-year-old" isn't matched. The part \p{Zs}*\S (notice that neither of these can match \n, so we stay in the same line) exists to make sure that the second part of the dialogue isn't empty. Trailing "-" like trailing ... sometimes indicate that the text continues in the next subtitle packet (and I have already seen it when the speaker is interrupted).
Notice that I personally have no experience with something outside of the Basic Multilingual Plane (Chinese/Korean/Japanese characters are outside of said plane).

**Comment by LeonCheung** [comment]
Many thanks, mkver! I think it works pretty good so far. Hmm, I never expected the rule can be such complicated. In fact a simple whitespace character is well in enough for me other than `\p{Zs}`  . :)  So I modified it a bit in case of any unwanted spaces ahead. And thanks again for the very comprehensive explanation.
![666](https://user-images.githubusercontent.com/494788/41499134-01594722-71ae-11e8-8fa3-70b3b9a42133.png)
