### ISSUE TITLE
Bug when using Adjust's Move 100 ms

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#2984]
When using it in translator's mode then saving the original and normal subtitle, then closing and opening the file again, the change of start time in Original isn't saved...
![screenshot 179](https://user-images.githubusercontent.com/20923700/43173732-1b2a073e-8fbf-11e8-804f-1c7bd71fccd7.png)
This only happens when using the Adjust's shortcuts, the change on the original subtitle isn't saved.

**Comment by OmrSi** [comment]
Another problem that happens with this shortcuts is when using move end 100 ms forward it overlaps with the next line though overlapping isn't allowed.

**Comment by OmrSi** [comment]
Same as this https://github.com/SubtitleEdit/subtitleedit/commit/442dddfea636602c4b1af2e11dd235f4735618bf but for the original.

**Comment by OmrSi** [comment]
The problem is happening with all of Adjust's move 100 ms.
The change on original isn't being saved.

**Comment by darnn** [comment]
I concur, except I think it would make more sense to discard the translation's time codes. Since, if you create a translation file from scratch, the time codes are taken from the original. At any rate, in the meanwhile, I've kinda learned to live with it: At worst, if, at the end, if I have an original file and a translated file with different TCs, I use "import time codes".

**Comment by OmrSi** [comment]
Yeah, but if you're translating it on stages, it would be hard to import every time...

**Comment by darnn** [comment]
That's true, I just usually don't adjust all the time codes several times while I'm translating. And regardless, just generally, I believe that if there's only one time code on screen (i.e. in the columns, there's only the start/end times of the original subtitle), that should be the TC in both sets of subtitles.

**Comment by LeonCheung** [comment]
LOL, you may want to check the crazy idea like this: #1344

**Comment by OmrSi** [comment]
Yeah, you shouldn't touch the work files usually, but most other files come with not very accurate time codes, especially when working with shot changes.

**Comment by darnn** [comment]
Oh yeah, like, I either get templates that I need to stick to 100%, or I'm importing scripts as plain text, and then the timing is meaningless.

**Comment by LeonCheung** [comment]
Yes, it's all about the workflow. Anyway, 99 of 100 translation projects I met would inevitably need changes on original timings (even one single tiny change), like line split, merge, remove, add new, etc. 

Why? Simply because it really needs editing! **No timing is perfect**, you know that. :) 

So, it's really important to always make sure they are synced, and sharing only one timing set.

**Comment by OmrSi** [comment]
True.

**Comment by niksedk** [comment]
The Adjust 100ms shortcuts should work for original too now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
Works like a charm <3
Thank you.
