### ISSUE TITLE
Audio distorted

### ISSUE THREAD

**Issue by Frigyi** [SubtitleEdit/subtitleedit#3033]
In the v. 3.5.6 the audio playing (VLC engine, MKV file) is distorted and not smooth.
When downgrade back to 3.5.5 it's working fine again.

**Comment by Frigyi** [comment]
Still not. But I will. Maybe it will better. Thx.

**Comment by OmrSi** [comment]
They are the best, I assure you.

**Comment by niksedk** [comment]
@Frigyi: Could you try latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip
It might very well be due to volume boot added in 3.5.6 - in latest beta it's an option in Options -> Settings -> Video player - could you test the beta with and without "Allow volume boost" - what happens?

**Comment by niksedk** [comment]
@OmrSi : Yes, mpv does work well (probably the best video player for SE) - I've seen that the waveforms generated by VLC and FFmpeg are not entirely alike - have you studied the differences?

**Comment by Frigyi** [comment]
The beta is working fine when "Allow volume boost" is off. The audio is clear and smooth.
When it is on, coming the higher volume but distorted audio (like in latest version).

But with VLC player only!
When "DirectShow" is selected, the audio is clear with both( ON/OFF volume boost). But seems similar volume.

(By the way the "DirectShow" is working fine first time for me. Earlier it wasn't show the video. No picture, audio only!)

**Comment by OmrSi** [comment]
@niksedk I haven't, I don't think it's an easy thing to do, but since I use scene changes, I use FFmpeg and found it good.
