### ISSUE TITLE
Off-set selected lines

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3125]
Is there any way to off-set selected lines only? sometimes only a part of the file needs off-setting...

Maybe make "Set start time, keep duration" can work with many (selected lines)?

**Comment by donlencho** [comment]
Synchronisation Menu / Adjust all times (Ctrl+Shift+A), then choose "Selected lines only".
Pretty obvious, but I guess you may not find it due to the improperly named menu entry that makes you think you won't be able to select some lines and not all. You could change your bug issue to reflect this unclear naming and have it changed.

**Comment by OmrSi** [comment]
Nope, I know this, already seen it.
But when timing to scene changes, you must be accurate to a frame, and that can't be achieved with Adjust all times.
You need to calculate the difference manually and that's not easy.

**Comment by LeonCheung** [comment]
I'm about to propose this too. See GIF below, maybe we are talking about the same thing:
![use video pos](https://user-images.githubusercontent.com/494788/47267893-3f550e80-d57c-11e8-9a40-eb743d3d2926.gif)

**Comment by donlencho** [comment]
Right, well, you didn't mention that in your first question. This is another idea, syncing by frames and not milliseconds. Syncing by milliseconds is actually more accurate than by frames (as a frame is only 1/24 or 1/25 sec.). I don't see why you say it can't be achieved, you just need to be precise, and yes it may take some trial and error and calculation.
Auto-Detecting a scene change would be great, but that's a totally different mechanism, Subtitle Edit would not to be able to analyze the video precisely. As far as I know, the timer that displays subtitles is not linked at all to the video.
All this to say, I maintain that you should change the title of this issue!

**Comment by LeonCheung** [comment]
@niksedk Please see my GIF above, I found a UI bug by the way: I did use hh:mm:ss:ff setting, but you see, the tip was still "Hour:min:sec:ms".

**Comment by LeonCheung** [comment]
Since we already had a few similar shortcuts:
![sel](https://user-images.githubusercontent.com/494788/47276276-77923680-d5e8-11e8-9ba6-743d187ffe57.png)
Maybe we could have a workround to solve this by adding one more, like "**Move selected lines to video position**". (to snap video pos to scene change, you need the "go to prev/next scene change" shortcuts, which already existed)

**Comment by OmrSi** [comment]
@niksedk I just found out that these two are related:
https://github.com/SubtitleEdit/subtitleedit/issues/2580
You can close one of them.
