### ISSUE TITLE
Punctuation in persian subtitle

### ISSUE THREAD

**Issue by asadghazanfary** [SubtitleEdit/subtitleedit#3228]
hello everyone

i'm using subtitle edit 3.5.7 and i want create a paragraph in persian language subtitle, and i have a problem in Punctuation marks that point show in begin of last line in paragraph Instead of show in end of last line.

how can fix it.
![capture](https://user-images.githubusercontent.com/5650939/49817411-0bba8780-fd68-11e8-841c-abd98d7495e9.jpg)
![capture2](https://user-images.githubusercontent.com/5650939/49817413-0bba8780-fd68-11e8-9221-a495c1f16e25.jpg)

**Comment by OmrSi** [comment]
This happens in RTL language because the players open the file as LTR.
The solution is, Select all lines the from "Edit", choose one of the two reversing options.
![screenshot 786](https://user-images.githubusercontent.com/20923700/49817837-f8181c80-fd79-11e8-9ec0-75a4a62cc438.png)

And Close this issue after you try. :)

**Comment by asadghazanfary** [comment]
i did try this option but problem is exist

**Comment by OmrSi** [comment]
I believe the developer would ask you to attach the file...

**Comment by niksedk** [comment]
> 
> 
> I believe the developer would ask you to attach the file...

I would... plus what goes wrong in what lines.

**Comment by asadghazanfary** [comment]
i attache a part of subtitle 
[avc_4.zip](https://github.com/SubtitleEdit/subtitleedit/files/2668863/avc_4.zip)

**Comment by OmrSi** [comment]
Looks to me like you didn't break the lines, and used the first way, add Unicode control char.
My opinion is that you should break the lines to many, then use one of the reverse options.
The way your file is, the player itself with break the lines so it can be visible on the screen.
So you should break them manually so that they can fit on the screen, then reverse.

I don't know if Nikolaj has another solution, you should listen to what he has to say after all.

**Comment by OmrSi** [comment]
@niksedk This is easily closed, I think. Was my assessment correct?

**Comment by OmrSi** [comment]
@niksedk I think this is easily closed, was my assessment correct?
> The way your file is, the player itself will break the lines so it can be visible on the screen.
So you should break them manually so that they can fit on the screen, then reverse.

**Comment by OmrSi** [comment]
@niksedk Isn't this closed? It just needed breaking from what I saw, or am I missing something?

**Comment by OmrSi** [comment]
@niksedk Isn't this closed? It just needed breaking from what I saw, or am I missing something?

**Comment by niksedk** [comment]
Looks fixed in mpv for me
