### ISSUE TITLE
Transcription Tab

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#3234]
Hello,
I use InqScribe to transcribe, and sometime I use SE Source view to transcribe.
It would be nice if there's a tab next to Source view called Transcription with basic transcription features like: a text editor with the ability to change fonts, size, color, bold, italics, etc. A Wordpad more or less.
Plus a few shortcuts to input spinets. Like, F6 = SPEAKER 1: F7 = SPEAKER 2: (we can modify the speaker tags + speaker tags always in bold). And a way to input a timestamp. As transcription doesn't require timestamps like subtitles, a method to input on timestamp. For example, in InqScribe, Ctrl+; add a time code in [00:00:00:00] format.
Shortcuts for video player will remain the same as are for subtitling.
Source view in its current stage is better than InqScribe, but the fonts are too small so I prefer InqScribe, otherwise, it still does the job. Just needs a few tweaks.

Thank you.

**Comment by amiaship** [comment]
bump! Subtitle Edit can open audio files as well as video. A few basic tools like speaker names and a transcript shortcut would make this quite a capable transcription software.

**Comment by PreetM07** [comment]
I second this issue.
However, for font size you just can go to settings > Font > Text box > font size -- changes the font in source view. (in the latest SE at least)
However source view is pretty much connected to the list view.
I think a time stamp in text form (maybe clickable to jump to that time) would be awesome.
Also pasting from word into source view releases all the formatting and then I am not able to find a way to do italics in the source view.

**Comment by nomatica** [comment]
I have been looking into using SubtitleEdit to aid in transcribing and annotating videos and audio files.  I really like being able to navigate using the waveform while working with a video/audio file.   

I would be curious how people are using subtitle edit in this way.  I realize there is a different between annotating and transcribing as well as providing subtitles.   InqScribe and alternatives are nice because they auto sync while creating the text.  You can also click on a link and go to that part of the video.  That kind of linking is helpful.
