### ISSUE TITLE
Change the dialogue & keep the time ?

### ISSUE THREAD

**Issue by Aliage** [SubtitleEdit/subtitleedit#3249]
Hello,

Like I said before I'm using  Subtitle Edite v 3.5.7 (now there is v 3.5.8), and I want to do something with my subs to save some of my time. I explain to you... I have a movie subtitles well synchronized in French language and I have the same in english but not synchronized. And I want to know if it is possible with S.E to do this manipulation... to keep the same time (timecode) of the french subtitles and replace all the french dialogue with english (not to change each line alone because it will take a huge time) so in the end the english subs will be SYNCHRO too like french subs.

Is that possible ? Please take your time to answer & thx.

**Comment by aaaxx** [comment]
You can do the opposite: File → Import time codes...

**Comment by mkver** [comment]
1. The method proposed by aaaxx only works well if certain assumptions that are unlikely to be fulfilled are fulfilled: Basically, every subtitle line/packet of the two languages needs to contain equivalent text. Here are reasons why this is very unlikely to be fulfilled:
   a) If one language contains forced subtitles (i.e. if there is a sign in English, the English subtitles will not contain a line for this, but the French subtitles might very well contain a translated version of the sign).
   b) If there is a dialogue, one subtitle might contain the text in the form "- <What person 1 says>\n- <What person 2 says>", whereas the other subtitle might split this into two subtitle packets.
   c) If a person speaks for such a long time that the subtitles for it need to be split into several packets, then it is very unlikely that both subtitles will be split at equivalent points. After all, there is no unique best point where to split: even if you have two subtitles in the native language, there will be differences and if the two subtitles are for different languages, this is vastly more likely.
   d) One subtitle might only subtitle what it considers essential and this is another point where the two subtitles might differ.
2. What does "not synchronized" mean? Is it just the text without any timing at all? Or does the timing of your English subtitle simply not match your movie file?
   a) If it's the latter, it is quite likely that this is just because of PAL speedup and/or different logos at the beginning. In this case go to Synchronization->change frame rate and make the English subtitles match the frame rate of your video. After that use synchronization->Adjust all times to get rid off the constant offset.
   b) There are situations where a) doesn't work: Namely if you have a different cut of the movie. This can be because it is really a different cut (say a director's cut and a theatrical cut; it can also be because of censorship) in which case there will likely be differences in dialogue which means that one can't simply resynch one subtitle for one version for the other. Or it can simply be because one version has a few frames more than the other version at different points (if one version is based upon a TV recording, then such things usually happen at the points where commercials where), but where no differences in dialogue occur. In this case the best way to proceed is to first make the frame rate of your movies match and then use synchronization->Adjust all times to make the subtitles match initially. When the subtitles are out of sync, it means that you are past a point where the two versions that the subtites were initially synced to differed. Now use synchronization->Adjust all times but with "Selected lines and forward" selected to adjust all future lines while not touching the timing of the lines that already are good. Do this until you are at the end.
   c) b) works by effectively splitting the subtitles into subblocks and applying a linear transformation on the timings of the subtitles in each block (in each block, the linear transformation is different: it has a different offset). This works well if your movie is of the kind I mentioned in b) and if your subtitles are actually "good"; if their timing (relative to the version that they are made for) is already bad, the method b) won't work. In this case resyncing will be much more work. In this case it is probably the best to use "Point sync via other subtitle" (it is also the closest to what you initially wanted).

**Comment by Aliage** [comment]
Hi,
I can make them become the same by deleting the SDH lines, that's where the difference is, between French & English subs there is only 52 lines because the first has 1183 lines and the second has 1235. About what "mkver" has said, the two subs are issued from a movie which is in 23.976. 

> What does "not synchronized" mean?
It means that it doesn't stick 100% with the movie, just a little tiny small gap & and I want it to be 100% like the FR subs.
Can you explain me how to do the method of "aaaxx" by importing timecodes... pls

Thank you.

**Comment by uckthis** [comment]
@Aliage Method that @aaaxx proposed only works if you have equal number of lines in both subtitles. Open your Eng sub file, then go to File -> Import time codes.In the pop up window, select the FR sub file.

**Comment by Aliage** [comment]
About what @mkver said :

> it can simply be because one version has a few frames more than the other version

The method of changing the frame is that one ? ----Synchronization -> change frame rate...

I suppose yes.

Thank you guys a lot.
