### ISSUE TITLE
Set End, Set Next, Go to Next

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#3263]
Hello,
I was wondering if it is possible in Create to Set End time, Start New time and go to Next caption with one key. I mostly work with imported texts, so it would be great to have one shortcut that would end the time and start the time of next line and move to next. I know about Set end, add new, go to new, but it adds a blank caption. I don't want it to add new caption but  rather set timing of the already imported one.
Thank you.

**Comment by uckthis** [comment]
I just realized that it's the "Set end, next start and go to next" from Adjust. Is it possible to have this option in Create as well?

**Comment by niksedk** [comment]
I guess the custom shortcuts from create and adjust could be merged... how is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.8/SubtitleEditBeta.zip

**Comment by uckthis** [comment]
@niksedk Works perfectly. Than you, man, and a Happy New Year!!!

**Comment by niksedk** [comment]
Cool, Happy New Year :)

**Comment by OmrSi** [comment]
Hmmm, merging the shortcuts is a brilliant idea, but now there are some repeated shortcuts, some of them only work in Create and some only in adjust.

Making Adjust's shortcuts work in Create is very good, but since they are merged, Create's shortcuts should also work in Adjust and the repeated shortcuts should be deleted.

For example, you have 2 set start and 2 set end, we wouldn't be able to tell the difference, so instead of a global mode switch as suggested here https://github.com/SubtitleEdit/subtitleedit/issues/3044 and here https://github.com/SubtitleEdit/subtitleedit/issues/2361
Merging the shortcuts is better, but the should work in all modes.
Then, I think, 3 issues can be closed. :D

**Comment by niksedk** [comment]
Create/adjust/translate shorcuts now global;
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.8/SubtitleEditBeta.zip
Also, the create/adjust are now better sorted, I hope.

Would a "toggle create/adjust/translate mode" shortcut still be useful?

**Comment by OmrSi** [comment]
I, personally, don't think so, Maybe someone else disagrees, @LeonCheung What do you think?
Since Shortcuts are now Global we can use any shortcut anywhere, and the Fs are mode based.
My main reason for that request was because I need to use one of Create's shortcut in Adjust, so my request has been met. I'll close my issue.

BTW, somewhat unrelated. @LeonCheung I think this is closed https://github.com/SubtitleEdit/subtitleedit/issues/696
