### ISSUE TITLE
.ASS \n gets replaced with <br/>

### ISSUE THREAD

**Issue by 1ll3g4l** [SubtitleEdit/subtitleedit#3295]
Is this a bug or is this purposely this way? anyway to disable it?

\n is not the same as <br /> and it's breaking the subs I am trying to load by making sentences 2 line sentences when it needs one.

**Comment by OmrSi** [comment]
https://github.com/SubtitleEdit/subtitleedit/issues/2457#issuecomment-312513884

**Comment by stern20** [comment]
Hello all the team, I am deaf and this need program subtitles Edit 3.5.6 very satisfied .. because good read, without not going. I am already nervous and restless. I already donate your money $ 5.
what's happening. should software be improved or how will it continue? 3.5.8 or 3.5.9 beta both same problem
