### ISSUE TITLE
Convert and save a UTF-8 to 1255 Hebrew always get a "?" in the beginning of each sentence

### ISSUE THREAD

**Issue by SubEdict** [SubtitleEdit/subtitleedit#3316]
Finish translating to Hebrew an English UTF-8 .srt and now I'm trying to save the file as a 1255 Hebrew windows file.
Now I Can't get rid of the question marks Unicode (?) that appear at the beginning of each sentence after converting from UTF-8 to 1255.
eg. "hello world" will save as "? Hello world"

Steps that I tried:
1. Change UTF-8 to 1255 and save. **Didn't work.
2. Select all and copy from the UTF-8 source > Create New document > change to 1255 > Past into the source. **Didn't work.
3. Copy the UTF-8 from Notepad and past into SE new document 1255. **Didn't work.

[Here is the UTF-8 file](https://www69.zippyshare.com/v/tPNUiCEo/file.html
) that I'm trying to save as 1255 Hebrew windows
Any Ideas?

**Comment by OmrSi** [comment]
That's because you probably used "Fix RTL via Unicode control character" which adds a hidden Unicode character to the beginning of each line to make it suitable for RTL languages and which isn't available in ANSI.

The Idea to fix this is to remove all hidden characters from the file then use the other method to reverse which is "Reverse Start\End for RTL".
To remove the hidden chars, go to replace, activate Regular expressions then write `\p{Cf}` in the first field and leave the second empty, then use the other method to reverse which is "Reverse Start\End for RTL".

Here is the file after the mentioned method:
[FM.S02E01.heb.zip](https://github.com/SubtitleEdit/subtitleedit/files/2799250/FM.S02E01.heb.zip)

After converting to 1255 Hebrew:
[FM.S02E01.heb.1255.zip](https://github.com/SubtitleEdit/subtitleedit/files/2799259/FM.S02E01.heb.1255.zip)

**Comment by OmrSi** [comment]
You're most welcome.
I've faced the same issue before as I use an RTL language as well. 😄
