### ISSUE TITLE
[Idea] Save Video with translate & Font Style Keeper

### ISSUE THREAD

**Issue by DemonRem** [SubtitleEdit/subtitleedit#3371]
instant of using 3rd software why can't the video  been save with  the subtitle I write,
another question is I want to preserve that font as shown In the media player how can I preform that action? 
![inner](https://user-images.githubusercontent.com/29927382/52905983-ae512400-324b-11e9-8a7f-aad77f3f02c4.png)

that pictures is from the software while I used the media player to edit it but as the subtitle show style that the style I want , I be glad if you can tell me how I can save that style over my subtitle.

**Comment by OmrSi** [comment]
`why can't the video been save with the subtitle I write`
Do you mean you want SE to merge the subtitle with the video?! SE doesn't have video editing capabilities and I think It never will.

As for the style, SRT files can't have a style, if when you're translating an SRT file you can only apply a font and a font size and a color and italic/bold/underlined, so after you finish translating you have to select all lines and then select the font and font size you want for all of the lines
If you don't care about the file's extension, you can save it as an ASS file which keeps the style, just save the file as ASS and you'll get to keep the whole style, which is used with MPV inside SE.

**Comment by DemonRem** [comment]
not work

**Comment by DemonRem** [comment]
![1](https://user-images.githubusercontent.com/29927382/52914170-e436ec80-32cd-11e9-9c20-a5365ae74de2.png)

**Comment by OmrSi** [comment]
@DemonRem The border thickness differs from one video player to another.
If you want it to look the same, after you convert the file to ASS, right-click on the first line and choose "Advanced Sub Station Alpha styles..." then increase the "outline" by 2 and save the file.

This happens because MPV and MPC handle the outline differently, so if you open the file in MPV it will look the same, but if you want it to look the same in MPC, you have to increase the "outline".
