### ISSUE TITLE
Saving produces corrupt srt files

### ISSUE THREAD

**Issue by mrahhal** [SubtitleEdit/subtitleedit#3525]
Hello,
I'm trying to adjust the time of some srt files, and then use another program to mix them into mkv videos.

After saving, the following file is produced:
```
1
00:00:20,286 --> 00:00:22,622
（チャイム）

2

2
00:00:25,325 --> 00:00:28,795
（ヴィーネ）
ん んん～ お昼かあ

3

3
00:00:29,329 --> 00:00:32,699
ガヴ 今日のお昼は… ん？
```

As can be seen, there are duplicated numbers. Video players such as VLC might be able to deal with this but other programs are failing at the unexpected format.

**Comment by OmrSi** [comment]
How is SE causing this? I'd think that @niksedk would ask you to attach the original srt file...

**Comment by mrahhal** [comment]
Check out this gist that contains 2 files: https://gist.github.com/mrahhal/0dbc485fff4c1d6c39b7d88dddc44017

I simply loaded "original.srt" in SubtitleEdit, and without even doing anything but simply saving, I got the content in "after_save.srt".

**Comment by OmrSi** [comment]
Ah, I remember now.
This issue was already fixed https://github.com/SubtitleEdit/subtitleedit/issues/3385#issuecomment-466152695
You should use the Beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.9/SubtitleEditBeta.zip

You can just replace the .exe file of what you already have, portable or installed. :D

**Comment by mrahhal** [comment]
Thanks!
