### ISSUE TITLE
Save as w/ language ISO code

### ISSUE THREAD

**Issue by ajbarnard** [SubtitleEdit/subtitleedit#3526]
Is it/would it be possible to have an option where you can save SRT files with the language code automatically attached? I.e. all my subtitle files are in english, so it would save as filename**.en**.srt .

**Comment by xylographe** [comment]
Do you mean a command line option (when run from a shell with `/convert`)?

**Comment by ajbarnard** [comment]
I was thinking through the GUI. It would be a nice option to have where you can have files save with the language code. Many players (for example Plex) read that **.en.srt and associate it to an english sub. ***.ru.srt for Russian, etc..

My workflow is to download SRT's from subscene, edit them in SubtitleEdit to my liking, then save - Then I have to manually rename and add the .en. to each one so Plex knows what language it is. This is kind of a pain when you have lots of TV Show files for example.

**Comment by xylographe** [comment]
You open `title.srt`. You edit. You invoke **Save as...**, and the proposed name in the save dialog is  `title.XX.srt` i/o `title.srt` (where `XX` is the two letter language identifier). You click **OK** to confirm.

Would that be OK?

**Comment by ajbarnard** [comment]
Spot on. I envision that somewhere in options you could set the default "Save As" language that would add the identifier to filename. Much appreciated xylographe!

**Comment by xylographe** [comment]
Suppose the original file name already has a language identifier: `title.fr.srt`. However, Subtitle Edit detects that the actual subtitle language is German! Would the proposed name become `title.de.srt` (German) or remain `title.fr.srt` (French)?

**Comment by ajbarnard** [comment]
Good question, but does SE currently detect language?

**Comment by xylographe** [comment]
Yes, it does (in [LanguageAutoDetect.AutoDetectGoogleLanguage](https://github.com/SubtitleEdit/subtitleedit/blob/7a3e961343826ced0aabed91c6d90e9e43a6101e/libse/LanguageAutoDetect.cs#L202)).

I believe, it would be preferable, to replace the existing language identifier, unless 'AutoDetectGoogleLanguage' did not get a result (language not yet supported).

**Comment by xylographe** [comment]
A preliminary implementation is available in `SE-3.5.9-issue3526.7z` (or `SE-3.5.9-issue3526-setup.exe`) from [this Dropbox folder](https://www.dropbox.com/sh/thgk5507tteg6ze/AABgb8jgWBnz9LLgDHsECfika?dl=0).

The UI part in the Settings dialog is still missing. To activate you must open `Settings.xml` in an editor, search for `<SaveAsUseFileNameFrom>`, and add a new line `<SaveAsDefaultLanguageId>XX</SaveAsDefaultLanguageId>` (replacing `XX` with the desired two letter language identifier, or an empty string to deactivate the feature).

The UI part will be more difficult to implement, because the **General** tab in the **Settings** dialogue is already ‘well-filled’. Could take some time to figure it out.

**Comment by ajbarnard** [comment]
👍
