### ISSUE TITLE
Which format is this? 

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#3534]
Hello,
 Help me identify this XML format. Which one is this? 
[01 Leaching_1_1.txt](https://github.com/SubtitleEdit/subtitleedit/files/3067962/01.Leaching_1_1.txt)

**Comment by SvenErik1968** [comment]
That is an Excel document. Try to rename it from .txt to .xml, open it in a recent version of Excel...

![snip_20190411125339](https://user-images.githubusercontent.com/10983802/55952047-ec216600-5c58-11e9-8d3a-5e0c150441f9.png)

**Comment by uckthis** [comment]
@SvenErik1968 , Thanks. Is it possible to export SRT to this format?

**Comment by SvenErik1968** [comment]
@uckthis, not directly from Excel, but with a little work in Excel to rearrange and add missing elements normally found in an .srt-file, then copy the result into a text editor like Notepad++ and do some hand tweaking.

I quickly tried did that, only took a few minutes since it is a small file; though it looks like SE changes the time codes a bit, so I suggest removing the leading `00:`, and add `,000` after the time codes or  `00:00:02:18 -->  00:00:05:15` gets changed to `00:00:02,751 --> 00:00:05,626`.

[01.Leaching_1_1.srt.txt](https://github.com/SubtitleEdit/subtitleedit/files/3069062/01.Leaching_1_1.srt.txt)

**Comment by uckthis** [comment]
@SvenErik1968 , You got my question wrong. I meant to ask if an SRT can be exported to an XLS.

From XLS to SRT is quite simple. Select and copy the 3 columns containing timecodes and text body and paste in a text file and open in SE. That's it.

**Comment by SvenErik1968** [comment]
OK, sorry.

Yes, should be possible, but you would have to do some VBA coding in Excel first.
