### ISSUE TITLE
[Minor] MPC not detected.

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#3644]
I have recently installed K-Lite_Codec_Pack_1500_Mega and SE didn't detect MPC, I looked for the file and found that it's named `mpc-hc64_nvo.exe`
I don't know if it's just for the MEGA pack or what...

**Comment by xylographe** [comment]
Installed from:`K-Lite_Codec_Pack_1500_Mega.exe`
Location:`C:\Program Files (x86)\K-Lite Codec Pack\MPC-HC64\mpc-hc64.exe`

What is full path of `mpc-hc64_nvo.exe`?

**Comment by OmrSi** [comment]
@xylographe Weird. I've got:
`C:\Program Files (x86)\K-Lite Codec Pack\MPC-HC64\mpc-hc64_nvo.exe`
Didn't even change anything while installing...

**Comment by xylographe** [comment]
Apparently, this is something new for Win10 — I'm using Win7.
See [How do I configure MPC-HC to use the NVIDIA GPU instead of Intel?](https://www.codecguide.com/faq_mpc.htm#item44) in the FAQ.

**Comment by OmrSi** [comment]
I actually have 1809 installed…

**Comment by xylographe** [comment]
Please, try **`SE-3.5.9-issue3644.7z`** (or **`SE-3.5.9-issue3644-Setup.exe`**) from [this DropBox folder](https://www.dropbox.com/sh/thgk5507tteg6ze/AABgb8jgWBnz9LLgDHsECfika?dl=0)

**Comment by OmrSi** [comment]
@xylographe Works well. Thanks.
I use MPV, by the way.
I was just testing DirectShow after installing K-lite and noticed MPC wasn't available.

**Comment by xylographe** [comment]
I just had a closer look at the K-Lite MPC FAQ. When mentioning “older versions of Windows” they actually mean Win10 before build 1803, not (as one might expect) older versions of Windows such as Win8.1 or Win7. Hence, the `mpc-hc[64]_nvo.exe` files are indeed a Win10 ‘novelty’.

Thank you for reporting. I use DirectShow as it is the most flexible option, but because I have decided to hold on to Win7 as long as possible, I have not noticed the change.

**Comment by OmrSi** [comment]
@xylographe Oh, yeah. I've heard that from many people.
I don't know why, though. I like Win 10. But I never worked on Win 7 to begin with...

MPV is the best in my opinion, as I use some ass codes in fansubbing.
And it doesn't hurt when translating for work.
