### ISSUE TITLE
[Feature Request] EBU STL Persian (Farsi) Character Table

### ISSUE THREAD

**Issue by Saya47** [SubtitleEdit/subtitleedit#3662]
EBU STL currently doesn't have Farsi (Persian) support, it has Latin/Arabic but I found out that 6 characters (if not more) will miss if Arabic is used:
{گ}{چ}{پ}{ژ}{ی}{ک}
Thank you very much.

**Comment by Setaran** [comment]
https://tech.ebu.ch/docs/tech/tech3264.pdf
On the documentations for EBU STL, there's Persian (5A) language code available. But on Subtitle Edit, it's not present.

**Comment by niksedk** [comment]
I cannot find the Persian Character Table...

**Comment by Setaran** [comment]
ok so it seems although the Language Code for Persian is available, there's no Character Table for it, and very likely there won't be in the future. Can you please add support for Persian letters somehow?
I honestly don't know how it works so it's a shot in the dark. I need EBU STL subtitle because this and SCC (Scenarist Closed Captions) are the only formats that Adobe Premiere Pro accepts for Closed Captioning, SCC doesn't even support Arabic so it's a lost cause but I have hopes for EBU STL. I used Closed Captioning to be able to Export my Media with a Sidecar subtitle, otherwise I would have to export it as Harcoded (Burn-In) subtitle video.
Thanks very much :)

**Comment by niksedk** [comment]
Sorry, I don't think this is fixable.
