### ISSUE TITLE
How to ovrd center-align to left if lines starts with dash?

### ISSUE THREAD

**Issue by Araynilmar** [SubtitleEdit/subtitleedit#3734]
![img_url](https://res.cloudinary.com/aray/image/upload/v1567199548/Screenshots/Ovrd_Center-Align_to_Left_if_Starts_with_Dash.jpg)

As shown in the figure, the top one is Actual behavior, the bottom one is Expected behavior.

Is there any possibility that two lines begin with dash on SRT or ASS subtitles, it'll be automatically center-aligned to left Just like on Blu-Ray Subtitles?

**Comment by niksedk** [comment]
Did you ever find a good solution?

What does "ovrd" mean?

SRTs are (mostly) styled by the video player, so definitively no.
ASS: it would be possible to calculate positions - perhaps Aegisub can do this?

Otherwise you can export as Blu-ray sup files (will affect all lines):
![image](https://user-images.githubusercontent.com/1261331/66663374-ea0d8380-ec4a-11e9-9dea-26be9fcf8501.png)
