### ISSUE TITLE
[Feature Request] Keyboard shortcuts for keys not in the list

### ISSUE THREAD

**Issue by amiaship** [SubtitleEdit/subtitleedit#3840]
I just started using SE and I'm loving it. Once I got the keyboard shortcuts lined up, the workflow is pretty streamlined. Good work, thank you!

I would like keyboard shortcuts to be set by key press rather than choosing from a list. I have macro keys that aren't defined by my OS, and I would like to set them to act as shortcuts, but they're not in the drop-down menu. It would be nice to set shortcuts by:
- Selecting the action to be performed ("auto duration for current line")
- Hit a button to reassign the shortcut, next to the button to clear the current key bind
- Dialog box comes up, prompting user to press the correct key combination
- Pressing the desired combination applies the new key bind and closes the dialog, returning user to Settings/Shortcuts where the new key bind is listed beside the action

This would allow for macro keys and key combinations that do not involve Control, Shift, or Alt. (Like a macro key + a letter, or PgUp + PgDown at the same time.)

Thanks again. SE is good, practical software, and I love to see stuff like this under the GPL.

**Comment by xylographe** [comment]
SE is written in C# using WinForms. The available key codes and modifiers can be found [here](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.keys?view=netframework-4.0).
If your macro keys are not in that list the .NET Framework won't recognise them, and you cannot use them in any WinForms application (including SE).

**Comment by darnn** [comment]
For what it's worth, I would love macros based on a sequence of typed letters, but since I assumed this would be somewhat beyond the scope of SE's main focus, I'm just using Breevy to create my own. Breevy works best for me on Windows, I don't know what the equivalents are on other OSes, but I know they exist.
So, for instance, I could type, like, "aaaa" at the end of a line, and that would make Breevy send the input of ctrl+alt+7, which is "merge with next line" for me. Instead of holding down function keys and moving my fingers from the typing position. In my case it's actually " ;", and it looks like this:
![se-muffins](https://user-images.githubusercontent.com/19672444/69044510-b8cc6400-09fd-11ea-8c05-8f532fe1ed58.gif)

This doesn't help with the middle mouse button, but I still think it's useful overall.

**Comment by n0selfesteem** [comment]
Hi, I'm late but I just want to share a workaround for using mouse buttons in shortcuts by using a simple AHK script.

```
#IfWinActive, ahk_class WindowsForms10.Window.8.app.0.141b42a_r6_ad1 ; Detect if SE is active, get it from WindowSpy
MButton::F14 ; Bind middle mouse click to F14
return
```

Basically just bind any buttons you want to F13-F24 (or any keys you're not using). Then configure the shortcuts in Subtitle Edit.

AHK can create even more complex macro to fit your needs so I suggest you experiment with it.
