### ISSUE TITLE
[Bug] use not break after list not work anymore

### ISSUE THREAD

**Issue by marb99** [SubtitleEdit/subtitleedit#3853]
Not break after list not work after the last changes in SE

last build 128, after add new options for break line, SE not respect some words in list "Not break after list"

example: I have in list "**Sr.**" before the last changes work perfect after the last changes some words in list not work.

![11](https://user-images.githubusercontent.com/7856897/69765051-55170900-116a-11ea-891b-2ebc43c58307.gif)

**Comment by xylographe** [comment]
As there is no Portuguese do-not-break-after list, I copied `es_NoBreakAfterList.xml` to `pt_NoBreakAfterList.xml`, and added "**Sr.**", but I couldn't reproduce. Could you post your "Auto br" Settings (Tools tab),

![NoBreakAfter](https://user-images.githubusercontent.com/8535293/69772079-370fcf80-118f-11ea-9827-630607129872.png)

**Comment by xylographe** [comment]
Got it!
Reproducible if "Break early for line ending" is enabled.

**Comment by xylographe** [comment]
The problem is that in [Utilities.NoBreakAfterList()](https://github.com/SubtitleEdit/subtitleedit/blob/7a625f7b3b7751c8e982c60245ee769738b7d48d/libse/Utilities.cs#L276) a non-regex item is preceded by a space character. In the case above the subtitle text starts with "**Sr.**", hence [NoBreakAfterItem.IsMatch()](https://github.com/SubtitleEdit/subtitleedit/blob/7a625f7b3b7751c8e982c60245ee769738b7d48d/libse/NoBreakAfterItem.cs#L22) will fail, and the space between "**Sr.**" and "**Gallo,**" becomes a ‘safe’ place to break.

**Comment by xylographe** [comment]
@marb99 
Perhaps, your **`pt_NoBreakAfterList.xml`** should be added to the repository?

**Comment by xylographe** [comment]
@niksedk 
Perhaps, "_Break early for line ending_" could read "_Break early for end of sentence_"?

**Comment by niksedk** [comment]
Fixed English text here: 85b124e6db530ae5d33b11e5b023e3743db39dee

**Comment by marb99** [comment]
@xylographe 

ok here is it 
[pt_NoBreakAfterList.zip](https://github.com/SubtitleEdit/subtitleedit/files/3903160/pt_NoBreakAfterList.zip)

**Comment by xylographe** [comment]
Thank you, @marb99. Added in commit 960915c14b5187c347aad045fb0a685a10b86b54.
