### ISSUE TITLE
Video is off

### ISSUE THREAD

**Issue by cocimho** [SubtitleEdit/subtitleedit#3891]
Hello !

I don't understand why i can't see video when i add it....

I try to install Lav filter and then codec pack full but it doesn't work...

can you help me please ? thanks.

Imho.

**Comment by xylographe** [comment]
I installed [K-Lite Codec Pack](https://codecguide.com/download_kl.htm) and set the "Video engine" to "DirectShow".

![se-settings](https://user-images.githubusercontent.com/8535293/71078553-eb4ab780-2189-11ea-84a0-64dab110a8ec.png)

**Comment by cocimho** [comment]
yes already set but not working :'(

**Comment by xylographe** [comment]
Do you see the four LAV icons in the tray?

![se-settings](https://user-images.githubusercontent.com/8535293/71079443-9445e200-218b-11ea-9e14-c67eac770b09.png)

**Comment by cocimho** [comment]
yes....

**Comment by cocimho** [comment]
i try to install kodec MEGA codec pack but the same...

**Comment by xylographe** [comment]
The Mega pack comes with MPC-HC. Does MPC-HC work?

**Comment by cocimho** [comment]
yes of course and i see the movie..

**Comment by cocimho** [comment]
i try to reboot but nothing, try to reinstall Subtitle Edit, even old version...

**Comment by cocimho** [comment]
anybody can help me please ?

**Comment by OmrSi** [comment]
Have you tried using MPV? Just click on "Download mpv lib".
It's the best video player for SE.

**Comment by xylographe** [comment]
@cocimho 
You could give _Codec Tweak Tool_ a try,
- "General / Fixes" (enable all, except for "Reset Windows Audio Mixer")
- "Settings / Reset" (perhaps, do a Backup first)

**Comment by uckthis** [comment]
@niksedk we need to fix this. I have had this issue since March, and after trying many fixes, I just switched to MPV. With Directshow there  is no video feed. You can hear the audio and video screen is blank. Directshow works in every other tool. Subtitle Workshop, Caption Maker, etc.
I just tried to open with old version of SE, and video displays until 3.5.8. Last version that displays video is 3.5.7 build 189. After that, the nearest I have is 3.5.8 build 218 and it doesn't show video. There's some issue with SE. 
Also, the tray icons are same in all instances. LAV Splitter, LAV Audio Decoder, LAV Video Decoder, and  DirectVobSubFilter2.

**Comment by xylographe** [comment]
DirectShow (LAV from K-Lite) still working on Win7, as it has done for many years.
Only minor issue, no correction when SAR does not equal one.

**Comment by uckthis** [comment]
I use:
Operating system:
  Name:           Windows 10 Enterprise LTSC (build 17763), 64-bit edition
  Version:        10.0
  Platform:       64-bit system

**Comment by niksedk** [comment]
I also have problems with DirectShow and Win10 now (I normally use mpv as video player).
There's not really been changes to the directshow code in the last many years: https://github.com/SubtitleEdit/subtitleedit/commits/master/src/Logic/VideoPlayers/QuartsPlayer.cs (other than rename of variables etc.)
So... I'm guessing it's something with a windows update at some point (again), but if DirectShow is working for other ppl on latest win10, then it's probably my computer.

I even tried to use the "DirectShowLib-2005.dll" instead of just the interop dll made by visual studio, and that also did not load the video (but it actually did if I re-opened the video).

@cocimho / uckthis: How is latest beta for you?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.11/SubtitleEditBeta.zip
(SE now just opens the video file twice... seems to work on my computer but it's hackish and I don't know why this happens). 
Ideas are welcome.

Well, luckily we have "mpv" and vlc 4 beta also work well.

**Comment by OmrSi** [comment]
I have Win10, 1909. And DirectShow works just fine, it always has. Even with x265 videos.

**Comment by uckthis** [comment]
@niksedk  It's working fine now. Great work. Thank you very much.

**Comment by niksedk** [comment]
Version 10 1909, build 18363.535 here... 

@OmrSi: does the hack (double loading) in latest beta with directshow have any side effects on your computer?

**Comment by OmrSi** [comment]
Just a fast flash when opening a video:
![Untitled Project](https://user-images.githubusercontent.com/20923700/71325503-757e7d00-24f6-11ea-9a23-233714b3833c.gif)

**Comment by uckthis** [comment]
No flash or anything on my side. 

![5tr](https://user-images.githubusercontent.com/28671050/71334484-40a71000-2560-11ea-976c-6280de06dce8.gif)

**Comment by uckthis** [comment]
I just installed a new version of Windows: Windows 10 V 1909 (build 18363), 64-bit edition and in this version last SE version also run DirectShow. So it was a Windows issue after all.

**Comment by niksedk** [comment]
I'll close this for now - could be a windows version problem and also the Settings.xml setting `DirectShowDoubleLoadVideo` equals `true` might also help. And switching to `mpv` video player is also a solution (notice that VLC has bad precision which should be fixed in v4 at some point)
