### ISSUE TITLE
Extraction Error (Timed Text from MP4)

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#3925]
This has happened to me on multiple occasions, so I thought to make a thread.
When I extract subtitles, specially for scene UK, some of them are out of sync. If you play the video and use the embedded subtitles, it plays fine, but once you extract them, they're outta sync.

Eg: https://dropapk.to/0etsfhnz590p/Would.I.Lie.to.You.S13E06.iP.WEB-DL.x264-Scene-RLS.mp4.html

When extracted, subtitles are outta sync. I used CCExtractor to extract and it worked fine, but with that files loses all of the color tags.

3.5.11 Beta 258

**Comment by xylographe** [comment]
The time codes are shifted one line, (SE left, CCE right)

![TimedText](https://user-images.githubusercontent.com/8535293/72733262-c89c2c00-3b97-11ea-8c30-b19711a8b45e.png)

The time codes of line 2 belong to line 1, line 3 to line 2, 4 to 3, etc.

**Comment by niksedk** [comment]
thx for the info :)

I cannot find the specs for subtitles in mp4 files... any ideas @xylographe @mkver @uckthis ?
( probably something in the `ReadText` method needs fixing: https://github.com/SubtitleEdit/subtitleedit/blob/master/libse/ContainerFormats/Mp4/Boxes/Stbl.cs#L139 )

**Comment by VaslD** [comment]
Ran into this issue as well. Had to use `ffmpeg` to convert the CC/SDH track to SRT.

Also it looks like `ffmpeg` generated SRT contains more formatting info (typeface and weight) than what SubtitleEdit would've produced after shifting timecodes.

From what I can gather on other video muxing forums, *Timed Text* "codec" refers to **ISO/IEC 14496-17:2006 - Streaming Text Format** (or as Wikipedia calls it, MPEG-4 Part 17). [Here's a PDF for that ISO with no paywall.](https://d1.amobbs.com/bbs_upload782111/files_38/ourdev_631444SHQH4Y.pdf) Looks like it contains the binary data structure of said format but I didn't really read whole 28-pages. (That's like US$4/page, can you believe it?!)

Hope this helps.

**Comment by niksedk** [comment]
@VaslD: thx for the info :)
I will look more at this - could you share a link to the problematic mp4 file (either here or email)?

**Comment by VaslD** [comment]
Here's the link: magnet:?xt=urn:btih:2c3c5119647025300fec2348a7ebb47b290a148e

(I hope this doesn't get pulled due to DMCA. Ironically the official download didn't contain any CC/SDH track so I had to improvise.)

A comparison with `ffmpeg` extracted subs on the right (after stripping formatting) shows not only lines are shifted, the very first and last entry are just incorrect, timecodes and texts-wise.

![SubtitleEdit_LMyFJDtJSw](https://user-images.githubusercontent.com/3415065/79038258-933d3280-7c0a-11ea-8b80-6d2db80b1d94.png)

![SubtitleEdit_4iSkisrG4C](https://user-images.githubusercontent.com/3415065/79038264-9fc18b00-7c0a-11ea-9bf4-ea3b30035745.png)

**Comment by niksedk** [comment]
Could be fixed... ?
