### ISSUE TITLE
Feature Request:  add "replace 1 to I" in common fix error list

### ISSUE THREAD

**Issue by solidmaple** [SubtitleEdit/subtitleedit#4068]
Feature Request:  add "replace 1 to I" in common fix error list

i often get  1 instead of "I"  using OCR and this is very common mistake

**Comment by uckthis** [comment]
That will be bad it it changed every instance of 1 to I. Subtitles have numbers too. 
A simple solution would by to find the common words where 1 is to be the replaced with I and putting those in OCR Fix Replace list in Dictionary folder. Try that one.

**Comment by niksedk** [comment]
@solidmaple: Please do attach a subtitle where this is a problem.

**Comment by shag00** [comment]
I also am concerned with this approach. I acknowledge the issue exists but there are also many instances where the number 1 is in fact a number. I think this is a tesseract issue.

**Comment by solidmaple** [comment]
https://x0.at/JXj.zip   here is a zip file with  jpg files with timecodes in it

you will notice you will get 1 instead of I using tesseract 4.xxx

**Comment by shag00** [comment]
Yes, I am fully aware of the point you are making, my point is you need to make the people at tesseract aware of it, by for example, adding to the following post that you also have the same issue.
[https://github.com/tesseract-ocr/tesseract/issues/2854#issuecomment-573406762](url)

**Comment by Signy13** [comment]
I used to have similar problem with `0` instead of `O` or `o` (this problems dissapeared with Tesseract 5, which has another problems with `|` instead of `l` or `I`).
A quick and versatile solution could be Multiple replace function with regular expressions (RE). It needs some knowledge and time to develop proper RE, but it is probably better solution in a situation when different versions of Tesseract and maybe even different `.traineddata` files produce different OCR errors.
I prepared czech subtitle file with this kind of error
https://uloz.to/file/q9C8fph7KiKE/se-test-zeroes-srt
and exported a template for Multiple replace 
https://uloz.to/file/oge6gyzBdNey/multiple-replace-zeroes-template
![SubtitleEdit_69_zeroes](https://user-images.githubusercontent.com/18901924/79829702-12b5c900-83a4-11ea-9043-cab8717ab283.png)
It needs to be adjusted for another languages and probably another cases - it is just a start for your own solution.

**Comment by Signy13** [comment]
I prepared another multiple replace template for changing `1` into `I` or `l` (both these options are possible in czech language). And sometimes there is no certainty whether `1` means `I` or `l` so the `1` is left intact.
Template:
https://uloz.to/file/BIAAzOnHuQvX/multiple-replace-ones-template
Example of SRT:
https://uloz.to/file/5uVttrPSG0NF/se-one-srt
Result:
![SubtitleEdit_71_ones](https://user-images.githubusercontent.com/18901924/79850442-3983f780-83c4-11ea-8769-a446e71370b8.png)
There can be another rules for another languages so it might need some fixes.

**Comment by niksedk** [comment]
>https://x0.at/JXj.zip here is a zip file with jpg files with timecodes in it
you will notice you will get 1 instead of I using tesseract 4.xxx

SE 3.5.15 does not seem to have this problem with Tesseract 5 with this file
