### ISSUE TITLE
Transferring audio PAL DVD to blu-ray

### ISSUE THREAD

**Issue by Maitch** [SubtitleEdit/subtitleedit#4072]
Sorry for posting it here. It is certainly something out of the scope of SubtitleEdit, but maybe some of you know how to do this...

So I have a rip of the same tv episodes both from the PAL DVD and the blu ray edition in MKV format. I only have Danish language audio on the DVD edition. Now, I wish to transfer the audio to the blu-ray rip. The problem is that PAL DVD is playing at 25 FPS and blu-ray is playing at 23,976 FPS, so some form of time streching is needed.

Do anyone have ideas to do this?

**Comment by VaslD** [comment]
**Stretching the audio cannot be done losslessly**, as speeding up or down the audio changes pitch (e.g. how *high* or *low* the voice is) by default. This is due to how sound wave works, so any technology that maintains pitch does so lossy; technically speaking, they have to make up or discard some sound data when you demand more or less than the original. If you're uncomfortable by this, you should get the appropriate audio track from a real Blu-ray.

`FFmpeg` can do basic stretching in one simple step: See [official docs](https://trac.ffmpeg.org/wiki/How%20to%20speed%20up%20/%20slow%20down%20a%20video); and [a more user-friendly version](https://avpres.net/FFmpeg/sound_speed.html). The process is automatic, but the audio may "sound a tad worse" according to comments.

Adobe's Audition and free (open-source) alternatives such as Audacity have a graphical waveform editor so you can fine-tune what happens during stretching. If you need to apply some other magic to make the audio great again, these apps are the way to go.

Note that if your source audio format is a lossy one (MP3, most Dolby formats, and most DTS formats), the audio goes through twice lossy operations (modify and save) so it will likely sound even more worse in the end.

**Comment by Maitch** [comment]
Thank you for your thoughts on this. I will try and check out those recommandations.
