### ISSUE TITLE
Accented characters in English subtitles

### ISSUE THREAD

**Issue by ipilcher** [SubtitleEdit/subtitleedit#4102]
I at attempting to OCR an English Blu-ray subtitle track that includes quite a few accented characters (in character and place names).  The characters include í, û, ë, and ó; SE (Tesseract 3.02) is failing to recognize any of these characters.  I noticed that SE does reliably recognize é; I am guessing that this is because it's somewhat commonly used in English, and is thus considered to be an English character.

If I'm right about what is going on, is there a way to get SE to recognize other accented characters in English subtitles?

**Comment by niksedk** [comment]
You probably need to train your own Tesseract language file: https://tesseract-ocr.github.io/tessdoc/Training-Tesseract.html

Latest beta of SE supports Tesseract 5 Alpha: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip

Also, you could try the OCR method "Binary image compare" in SE.

**Comment by Signy13** [comment]
Sorry I am commenting already closed issue, but would it be possible to use multipe language choice for tesseract?
I did some tests with Tesseract 3.02 and this image (saved from SE):
![UG_Ceska_TV_uvadi](https://user-images.githubusercontent.com/18901924/79067620-03a68b00-7cc1-11ea-899a-116cd7df3b1b.png)
* `tesseract.exe test.png test_ces -l ces hocr`
returns `Česká televize uvádí ÚSMĚVNÁ GALERIE`
* `tesseract.exe test.png test_eng -l ces hocr`
returns `Ceské televize uvédi USMEVNA GALERIE`
* `wine tesseract.exe test.png test_eng_ces -l eng+ces hocr`
returns `Česká televize uvádí ÚSMĚVNÁ GALERIE`

It looks like Tesseract can do it - if SE would use another way how to select language(s) for Tesseract (instead of comboBox). It could solve similar problems.
