### ISSUE TITLE
Remove Dialogue Dashes in Single Line

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#4206]
Hello,
What does this supposed to do? From the name I assume it removes dashes, but single line means? Does it mean one line or one sentence? I have a file I need dashes removed from single sentenced dialogue and this option doesn't do it. Is there any option to do it?
File attached.

Thank you.
[New Text Document.txt](https://github.com/SubtitleEdit/subtitleedit/files/4689146/New.Text.Document.txt)

**Comment by OmrSi** [comment]
That's because the dash in this file is a hyphen `‐`: https://www.compart.com/en/unicode/U+2010
While the used dash is a Hyphen-Minus `-`: https://www.compart.com/en/unicode/U+002D

You can do a replace and it should work, or you can use the "Normalize" option which was added to FCE today: https://github.com/SubtitleEdit/subtitleedit/commit/34d541198b83cd7906e18c9fbc90caea951fa86e

**Comment by uckthis** [comment]
@OmrSi Replace worked. Thank you.
