### ISSUE TITLE
Subtitle Edit not recognizing subtitle RTF files

### ISSUE THREAD

**Issue by Hai-Lag** [SubtitleEdit/subtitleedit#4218]
I have RTF subtitle files that come with a subtitle like this:
```
=====
01:00:00:07	
01:00:01:21	>> Narrator: in 2010, an anticipation of absorbing
01:00:04:10	the WEC, the UFC added featherweight fighters
01:00:07:24	to its roster.
====
```
Subtitle Edit is not reading these files. Is there any solution or a trick to do so?
I also want to convert them to SRT files with timecode like this: 
```
====
1
01:00:00,280 --> 01:00:01,799
>> Female reporter: We're getting minute to minute,
====
```
Please help and thank you so much in advance :)

**Comment by darnn** [comment]
I don't think SE recognizes this subtitle format at the moment. It would help if you posted a few more lines, since this one is kind of inconsistent: It seems like every subtitle only has a starting time, but then the first one appears to be blank.
Either way, if this format does indeed only have the start times, I fear it won't do you much good in terms of having a fully timed final file, since you'd at least have to set the end times by hand.

If the format is what it appears, you can convert it by hand into something SE could read. I use EditPad, but I assume this can be done in any text editor that supports regular expressions. EditPad is the only one whose syntax I know, though.
So, what I would do is this. Save the file as a text file, and then in the text editor, perform the following search and replace operation. Replace this:
^(\d\d:\d\d:\d\d:\d\d)(.*)
With this:
\1\r\n\1\2

(That is, you take the time code, and out of each line, create one line with just the time code and then another line with the time code and the text.)

The result should now look like this:

`01:00:00:07`
`01:00:00:07`
`01:00:01:21`
`01:00:01:21 >> Narrator: in 2010, an anticipation of absorbing`
`01:00:04:10`
`01:00:04:10 the WEC, the UFC added featherweight fighters`
`01:00:07:24`
`01:00:07:24 to its roster.`

Now delete the first line (01:00:00:07) and replace it with "#PE2 Format file", so that you get this:

#PE2 Format file
`01:00:00:07`
`01:00:01:21`
`01:00:01:21 >> Narrator: in 2010, an anticipation of absorbing`
`01:00:04:10`
`01:00:04:10 the WEC, the UFC added featherweight fighters`
`01:00:07:24`
`01:00:07:24 to its roster.`

Now you can save this file and open it in SE. As you can see, the end time of each subtitle will now be the start time of the following subtitle, so as I said, you'll have to set the end times manually. But this is the best you can do with only the start time, aside from determining an end time based on the length of the subtitle, which I have no experience with.

**Comment by niksedk** [comment]
Please post a complete file :)
You can attach .zip files here.

**Comment by Hai-Lag** [comment]
[200 Greatest Fighters 101-AR +EN Saplesto GitHub.zip](https://github.com/SubtitleEdit/subtitleedit/files/4735911/200.Greatest.Fighters.101-AR.%2BEN.Saplesto.GitHub.zip)

Thanks a lot guys for the help. 
These are just samples of the original files received from or sent to my client - used small samples because I am afraid to get into troubles of copyrights haha-

Thanks @darnn : This timecode, it has only the input not the output, and I want to read it SE somehow and export it as an SRT file.

To make my work easier, I always finish the transcription or translation work in SE then import the file to Premier Pro so that my client can use it in their channel or broadcasting stuff...
So the issue is to convert the RTF file into SRT format to be accepted in SE and Premier Pro.

Notes: 
- I found some timecode type close to my timecodes called (Unknown 47) but it like this (1:00:00:00) not like this (01:00:00:00) but when I import the RTF file in SE, it doesn't recognize it.
- I also tried that technique of fin/replace (**^(\d\d**:\d\d:\d\d:\d\d)(.*) with **^(\d:\**d\d:\d\d:\d\d)(.*)) but it didn't work

Thanks again :)

**Comment by niksedk** [comment]
@Hai-Lag: I've updated latest beta version to support this format: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.15/SubtitleEditBeta.zip
Does that work for you?

**Comment by Hai-Lag** [comment]
Hi @niksedk 
It works just perfectly, I really appreciate that. I tried to play around and this what I found:
- I tried to import both formats (Arabic and English) and the import works perfect

*-the Timecode of English did not change and it was perfectly synced with video (despite we only have the input in the original RTF ).

*-the Timecode of Arabic file changed a little bit (and sometimes a lot: 5-6 seconds after or before the video) and the weird thing is that the in Arabic file, I found so many lines that were supposed to be in different subtitles/ moments of the video, I found them in one line, in a different moment (I hope I explained that in a good way hhh)

- I tried to export them both, the English export was just like the original one, but the Arabic, it took the same style like English 

- in all cases, when import a file to SE, then click **Source Review** it changes the format to the SRT timecode format.

* you may check the attached to see screenshots of what I got.

I really appreciate your time, Thanks again :)  

[Ar-En exports-originally RTF-SE-beta-feedback.zip](https://github.com/SubtitleEdit/subtitleedit/files/4736816/Ar-En.exports-originally.RTF-SE-beta-feedback.zip)

**Comment by niksedk** [comment]
Latest beta should support both formats: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.15/SubtitleEditBeta.zip

**Comment by Hai-Lag** [comment]
Hi @niksedk and @darnn 
Thank you so much for help and appreciate your time.
Sorry I couldn't reply in time but what you did is really amazing. Keep up the good work, Guys. 😎👌👌 
Now it reads both the Arabic and English formats. but can I use the beta version for daily use or I have to download the official one from the site?

Thanks again

**Comment by darnn** [comment]
No need to thank me, it's all @niksedk!
