### ISSUE TITLE
Ctrl + S and File > Save doesn't always seem to work

### ISSUE THREAD

**Issue by guido-visser** [SubtitleEdit/subtitleedit#4313]
It looks like that in the latest version: `3.5.16`, using Ctrl + S doesn't work consistently. Sometimes it works and other times it doesn't.
The only way to save the srt is to click on the save icon. File > Save seems the same way (inconsistent in saving).

Can't really nail to consistently reproduce the issue. I'll add an update to this thread if I've found a consistent reproduction.

Are other people having the same problem?

**Comment by Lokotito** [comment]
I have similar issues with early versions, but in my case happens because I was working translating subtitles or resync times (adjust all times) and I was using a second "child" window and I had not selected (in focus) the main SubitileEdit window.
I notice when I was using (in focus) the main SubtitleEdit program windows all work normal, maybe is your case also.
