### ISSUE TITLE
Windows Forms Thread Exception

### ISSUE THREAD

**Issue by jrceloni** [SubtitleEdit/subtitleedit#4375]
Windows Forms Thread Exception

An application error occurred in Subtitle Edit 3.5.16.0.
Please report at
https://github.com/SubtitleEdit/subtitleedit/issues with the
following information:

Error Message:
Index was out of range. Must be non-negative and less than
the size of the collection.
Parameter name: index

Stack Trace:
  at
System.ThrowHelper.ThrowArgumentOutOfRangeException(E
xceptionArgument argument, ExceptionResource resource)
  at System.Collections.Generic.List`1.setItem(Int32 index, T
value)
  at
Nikse.SubtitleEdit.Forms.Main.AudioWaveformOnTimeChang
ed(Object: sender, ParagraphEventArgs e)
  at
Nikse.SubtitleEdit.Controls.AudioVisualizer.WaveformMouseD
own(Object: sender, MouseEventArgs e)
  at
System.Windows.Forms.Control.OnMouseDown(MouseEventA
rgs e)
  at
System.Windows.Forms.Control.WmMouseDown(Message&
m, MouseButtons button, Int32 clicks)
  at System.Windows.Forms.Control.WndProc(Message& m)
  at System.Windows.Forms.UserControl.WndProc(Message&
m)
  at System.Windows.Forms.NativeWindow.Callback(IntPtr
hWnd, Int32 msg, IntPtr wparam, IntPtr Iparam)

Abort Retry Ignore

Retry yielded same error.  I then hit Ignore and proceeded to add my subtitles.  BTW I tried to upload a screen clip of the error as a PDF and wasn't sure it worked, so I repeated it as PNG, but I see from the links below that they both worked.  No need to look at both!  Thank you.

[SubtitleEditScreenClip20200916.pdf]https://github.com/SubtitleEdit/subtitleedit/files/5234268/SubtitleEditScreenClip20200916.pdf)

[SubtitleEditScreenClip20200916](https://user-images.githubusercontent.com/7849791/93379122-40e3eb80-f812-11ea-98bb-d45c94008d39.png)

**Comment by OmrSi** [comment]
Can you provide steps to recreate this? What caused this error?

**Comment by jrceloni** [comment]
Wow that was quick reply.  I'd loaded a video and was about to enter my first subtitle:  I listened to a phrase, selected the end of it, dragged the mouse to the left to the start, let go, then clicked on the starting point and dragged left a bit more; that's when I got the error.  I'm new to Subtitle Edit but can't imagine not having done the same thing before with no error.  I can't think of anything that was different this time.  I didn't lose any work, "Ignore" worked (I finished the subtitles, saved the .srt, uploaded it to YouTube, and watched the result with captions on), and it's the only time I've seen an error, so I'm not worried.  (BTW I've used Subtitle Edit from 2 different PCs, both Win10 Pro desktops.)  Both .mp4 and .srt files are on  the local hard disk.

Could you please shed light on another experience?  I downloaded an .srt file from YouTube for a 54-min video, then brought both the .mp4 and .srt into SubtitleEdit to clean up the robotitles.  I found myself moving just about everything that YT put there to the left, to the point that it became faster for me just to listen and type, deleting the robotitles one by one.  I was worried that when I uploaded my new .srt it wouldn't be in sync, but it was fine.  When I watch a YT video with the robotitles, they seem in sync, but I didn't watch THIS video's robotitles on YT before editing the .srt file.

BTW I need to get faster of moving around in the timeline.   I shrink the timeline and speed up playback most of the time, and I navigate using the bar below the waveform, and that all helps, but since I need to straddle screens to move titles ahead, I was looking for other ways, e.g. click/drag mouse, PgUp/PgDn keys.  Moving the mouse does other things (like selecting regions of the video so I can add text etc.), but am I missing another mode (e.g. sliding mouse above/below waveform to shift visible section without making a selection)?

Thanks again.  *j

James R. Celoni
Los Angeles

**Comment by OmrSi** [comment]
Do you mean that this error only happened once and you were not able to reproduce it?
If so, I'm afraid nothing can be done, because if we weren't able to reproduce it, we won't be able to know which line in the code causes the issue.
That's just what I think, the final word will be for @niksedk

As for the controls, you can drag the line in the waveform by clicking on it in the center, aways from the edges, and dragging it.
There are some useful shortcuts, though. You can find some of them here https://www.nikse.dk/SubtitleEdit/Help#waveform
Also, there are many useful shortcuts in the settings, like `Set start, keep duration` and `Adjust via end position`.
If you want to get faster working on SE, you should get used to the shortcuts. :D

From my experience, Youtube's subtitles are rarely synced well.
They usually need heavy adjusting, especially if they are auto-generated.
If you notice that all lines need shifting in a fixed amount, you click where the first line starts and then press F9, it offsets the whole file shifting it to begin from the place you chose.

**Comment by jrceloni** [comment]
Thanks again.  I only reproduced it in that one case, both by Retry and by selecting and adjusting the same region.  If I run into a similar problem, I'll work harder and reproducing it and report it if I can.

Thanks too for the tips on shortcuts and shifting.  I'll check them out!  I bet they'll get me closer to entering subtitles about as fast as I can type them in…  *j

**Comment by maknol** [comment]
Same problem for me with 3.5.16 and the beta 184. Here the file for test - http://www.mediafire.com/file/t4z731tpby4h73v/FilmBox.mks/file (if you need - Bulgarian)

**Comment by OmrSi** [comment]
@maknol When does it happen? Steps to recreate?

**Comment by niksedk** [comment]
Hi @maknol: Could you try this debug version: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.16/SubtitleEditBetaDebug.zip ?
(should give the exact line number when crashing)

**Comment by maknol** [comment]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Nikse.SubtitleEdit.Core.ContainerFormats.TransportStream.ObjectDataSegment.Next4Bits(Byte[] buffer, Int32& index, Boolean& startHalf)
   at Nikse.SubtitleEdit.Core.ContainerFormats.TransportStream.ObjectDataSegment.FourBitPixelDecoding(Byte[] buffer, Int32& index, Boolean& startHalf, Int32& pixelCode, Int32& runLength)
   at Nikse.SubtitleEdit.Core.ContainerFormats.TransportStream.ObjectDataSegment.ProcessDataType(Byte[] buffer, Int32 index, ClutDefinitionSegment cds, Int32& dataType, Int32 start, List`1 twoToFourBitColorLookup, List`1 fourToEightBitColorLookup, List`1 twoToEightBitColorLookup, Int32& x, Int32& y, Int32 length, Int32& pixelCode, Int32& runLength)
   at Nikse.SubtitleEdit.Core.ContainerFormats.TransportStream.ObjectDataSegment.DecodeImage(Byte[] buffer, Int32 index, ClutDefinitionSegment cds)
   at Nikse.SubtitleEdit.Core.ContainerFormats.TransportStream.DvbSubPes.GetImage(ObjectDataSegment ods)
   at Nikse.SubtitleEdit.Core.ContainerFormats.TransportStream.DvbSubPes.GetImageFull()
   at Nikse.SubtitleEdit.Forms.Ocr.VobSubOcr.GetSubtitleBitmap(Int32 index, Boolean crop) in C:\Data\SubtitleEdit\subtitleedit\src\Forms\Ocr\VobSubOcr.cs:line 1756
   at Nikse.SubtitleEdit.Forms.Ocr.VobSubOcr.MainLoopTesseract(Int32 max, Int32 i) in C:\Data\SubtitleEdit\subtitleedit\src\Forms\Ocr\VobSubOcr.cs:line 5366
   at Nikse.SubtitleEdit.Forms.Ocr.VobSubOcr.mainOcrTimer_Tick(Object sender, EventArgs e) in C:\Data\SubtitleEdit\subtitleedit\src\Forms\Ocr\VobSubOcr.cs:line 5376
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4220.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
SubtitleEdit
    Assembly Version: 3.5.16.193
    Win32 Version: 3.5.16.193
    CodeBase: file:///C:/Users/TTT/Downloads/SubtitleEditBetaDebug/SubtitleEdit.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
libse
    Assembly Version: 3.5.16.193
    Win32 Version: 3.5.16.193
    CodeBase: file:///C:/Users/TTT/Downloads/SubtitleEditBetaDebug/libse.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4220.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
zlib.net
    Assembly Version: 1.0.3.0
    Win32 Version: 1.0.4.0
    CodeBase: file:///C:/Users/TTT/Downloads/SubtitleEditBetaDebug/zlib.net.DLL
----------------------------------------
NHunspell
    Assembly Version: 1.2.5554.16953
    Win32 Version: 1.2.5554.16953
    CodeBase: file:///C:/Users/TTT/Downloads/SubtitleEditBetaDebug/NHunspell.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by maknol** [comment]
Just tested with Tesseract302 and work, but with Tesseract500.Alpha.20200328 - crashing.

**Comment by niksedk** [comment]
@maknol: thx for the mks file - beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.16/SubtitleEditBeta.zip - hopefully fixes crash

**Comment by maknol** [comment]
Fixed! But not asking me for unknown word, neither fix OCR errors, just rushing to the end with an ocean of errors.
