### ISSUE TITLE
alignment on video preview?

### ISSUE THREAD

**Issue by m0ck69** [SubtitleEdit/subtitleedit#4752]
Hello.
Is it possible for mpv player to respect subtitle position (alignment) on the video preview?
I guess not, otherwise you would have done it by now, right?

![Clipboard01](https://user-images.githubusercontent.com/46628545/105634062-8d90a080-5e5c-11eb-9c79-e525b6e98320.jpg)

**Comment by niksedk** [comment]
Try "mpv handles preview text"...

**Comment by m0ck69** [comment]
"mpv handles preview text" seems to respect alignment but subtitles look ugly when I use this option.



Subtitles are displayed on the video on on the black bar below.

![2](https://user-images.githubusercontent.com/46628545/105635367-ae5bf480-5e62-11eb-8032-fe650d221adc.jpg)



They also have outline and shadow which I can't get rid of.
I tried to change them here but it doesn't wotk.

![3](https://user-images.githubusercontent.com/46628545/105635374-b4ea6c00-5e62-11eb-8b0a-427e7ae79c31.jpg)



"mpv handles preview text" turned off looks much better imo but alignment isn't supported here.
![1](https://user-images.githubusercontent.com/46628545/105635376-b74cc600-5e62-11eb-8c7f-78e20b65ad22.jpg)

**Comment by OmrSi** [comment]
`mpv handles preview text` is the only way to respect alignment.
SE uses a textbox on the video to display the subtitles and it's located at the bottom of the video player, so there isn't a way to align the text to the top, as far as I know.

The border color and the shadow should be adjustable from the ASS style tab, but a change here https://github.com/SubtitleEdit/subtitleedit/commit/bbb3c400deda76fd1798a28e1f3010a78e726514 caused it not to because it's using fixed values, it's an easy fix.
