### ISSUE TITLE
OCR not see text

### ISSUE THREAD

**Issue by maknol** [SubtitleEdit/subtitleedit#4755]
Hi,
images generated by VideoSubFinder (https://www.videohelp.com/software/VideoSubFinder) in OCR showing blank image with every OCR engine. Example image generated from VideoSubFinder:

<a href="http://www.imagebam.com/image/f08e501367939586" target="_blank"><img src="https://thumbs2.imagebam.com/d3/48/c9/f08e501367939586.jpg"></a>

Open in with SE and see.
I edited and convert it to other format (PNG, JPG, etc.) and nothing changed. 
Extracted from TS files work well, only from this program have problem.

**Comment by niksedk** [comment]
Please attach some sample files (attach .zip file)

**Comment by maknol** [comment]
[https://dox.abv.bg/download?id=4888baae0a](url)

**Comment by niksedk** [comment]
thx for the files, easier to understand the issue :)

The image pre-processing was not working too well with Tesseract5... should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip

You need to setup image pre-processing like this (right-click on image):
![image](https://user-images.githubusercontent.com/1261331/105901509-c4fa7b00-601d-11eb-8fcf-b4b2fa590498.png)
