### ISSUE TITLE
NQC gets very laggy when video is loaded

### ISSUE THREAD

**Issue by m0ck69** [SubtitleEdit/subtitleedit#4790]
The title says it all.

https://user-images.githubusercontent.com/46628545/107339524-0fb7d080-6abd-11eb-8609-7afbcb75130d.mp4

https://user-images.githubusercontent.com/46628545/107339545-15151b00-6abd-11eb-9529-5224aa6ee43e.mp4

**Comment by OmrSi** [comment]
This is normal.
`Check timing to shot changes rules` takes a lot of work, the more shot changes and lines, the more the time,
and each time you check or uncheck a line, the whole list is generated from scratch.
Since generating `Check timing to shot changes rules` takes a lot of time, it's normal that the window will lag.
You can uncheck that option first then work with other options in order to avoid the lag.

**Comment by m0ck69** [comment]
OK, that make sense.
