### ISSUE TITLE
Subtitle Edit won't open my video

### ISSUE THREAD

**Issue by DianaJank** [SubtitleEdit/subtitleedit#4831]
I have installed Subtitle Edit on my Windows/Parallels machine and it won't open any videos to subtitle. I keep getting an error message. What can I do?
![Zrzut ekranu 2021-02-22 o 12 12 26](https://user-images.githubusercontent.com/79452643/108700999-b06bae80-7507-11eb-8926-138634e8d27e.png)

**Comment by niksedk** [comment]
Sounds a lot like https://github.com/SubtitleEdit/subtitleedit/issues/4826

Is latest beta (portable version) any better: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip ?
(unpack to something like c:\tools\SE)

**Comment by DianaJank** [comment]
Hi, I've installed the suggested Beta version, but the error still comes up. To recreate, add a video file, then an error message shows up (There seems to be missing a codec (or file is not a valid video/audio file)!) - even though this video file opens up on Mac/Windows without problems outside of Subtitle Edit.

I'm not sure if I can explain any better, I'm not a very technical person :(
![Zrzut ekranu 2021-02-22 o 12 12 26](https://user-images.githubusercontent.com/79452643/108702597-c7130500-7509-11eb-8a69-abedc74aa8ba.png)

,

**Comment by niksedk** [comment]
OK, I've updated the beta a little, could you re-download: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip

And also download "mpv" - see options - settings - video player

What happens now?

**Comment by niksedk** [comment]
Also, how do you open the video file? Menu item? Drag-n-drop or ?

**Comment by DianaJank** [comment]
Thanks. I have deinstalled the previous versions of Subtitle Edit and downloaded the updated beta version - unfortunately there's no change. I've tried opening video files both ways - using the menu and dragging and dropping them - to the same effect.

I have mpv installed already.

**Comment by DianaJank** [comment]
Any clues how I can fix this? Thanks in advance

**Comment by OmrSi** [comment]
Hey, @DianaJank 
The error in your main issue is different from the error you posted later.
The first one was a problem is opening a video file using MPV, while the second is saying that DirectShow doesn't have the codec to open the video.

To test if the main error is fixed, you need to click on "Download and use MPV" in order to switch to MPV, so it can be tested again for the main error.
If you just want to work with DirectShow, you might need to install a codec like LAVFilters.

Here are the steps to test the beta properly:
1. Extract the beta zip file somewhere, but not in `C:\Program Files\`.
2. Download MPV from that extracted version.
3. Test the video with the new version.

If you have the installed version, you can just replace the executable file in `C:\Program Files\Subtitle Edit\` with the one in the beta.

**Comment by DianaJank** [comment]
Hi,

Thanks so much - I’ve installed LAVFilters and it’s working. I absolutely love Subtitle Edit so I’d like to use this opportunity to thank you for creating it.

Is there a way for me to donate an amount to show my appreciation?

Diana Jankowiak

**Comment by niksedk** [comment]
I'll close this for now... but if you find out how to re-create the original issue do let us know.
