### ISSUE TITLE
Problem when batch converting subtitles

### ISSUE THREAD

**Issue by IDontKnow218** [SubtitleEdit/subtitleedit#4917]
Hello. I have a problem using Subtitle Edit to convert subtitles. Every time I convert subtitles and then check them after converting, I find that Subtitle Edit changes some words from the original subtitle. For example, the original subtitle will have the word apple. When I convert the subtitle, apple becomes apele (replaces a word with another word). Is there any way to fix this problem? Any help appreciated.

**Comment by niksedk** [comment]
OK, you should probably mention this thread: https://forum.videohelp.com/threads/401206-Problem-when-batch-converting-subtitles-using-Subtitle-Edit
There's a very large difference between text-to-text and image-to-text.

OCR not a 100% accurate conversion and errors should be expected. 
You could try nocr via cmd line and see if that gives better results, if not you must improve the ocr db to match your bd sup better.

In order to receive help, always try give as much info as possible: screenshots + attached subs always improves your chances of a relevant answer.
