### ISSUE TITLE
Subtitle Styling and Line Positiong for WebVTT

### ISSUE THREAD

**Issue by wickedfable** [SubtitleEdit/subtitleedit#4983]
Hi there,

This is similar to #2296 but I'm not sure if it was actually ever resolved even though that issue was closed.

I was wondering if it is possible to get subtitle styling (size, color, etc.) and positioning (line position, alignment, etc.) options for WebVTT subtitles? At the moment I can't see any way to do any of these options. The expected output would be something like:

`00:00.000 --> 00:33.000 line:11 position:50% align:left size:100%
Test text`

The line positioning is the most important part for me ("line:11", from the above example) but the other options would also be useful.

Edit: I should have mentioned specifically that I am looking for these as an option to style all of the lines and not just line-by-line. Similar to what you can do with other subtitle formats such as Advanced SubStation Alpha (.ass).

Thank you,
-Daniel

**Comment by niksedk** [comment]
SE should already support this... except size which SE does not support for any formats (except via ASSA/SSA style).
What exactly is not working for you? (please attach sub sample file)

**Comment by wickedfable** [comment]
Thanks for the reply. Unfortunately I don't have a sample sub file since I'm not able to accomplish what I'm looking for. I have attached below a couple of images showing what I mean. In one you can see that with .ass subtitles, you are able to select the red "A" to set a default style for all of the lines in a file. In the other, if you are working with a .vtt file, this is not possible as the option isn't available. 

You would have to manually select the lines you want styled and apply each specific style to each line one-by-one. For example, if I wanted to apply alignment and color to a line, I would first have to select the line in question, apply the alignment I would want and then select it again and apply the color I want. It doesn't look like there's a way to set a default style (with multiple changes such as alignment, color, size, font etc.) and simply apply that style to a line or multiple lines.

![2021-04-16 18_09_21-_AncientDetective S01E01 test vtt - Subtitle Edit 3 6 0](https://user-images.githubusercontent.com/1691076/115093206-95099800-9ee7-11eb-8bba-6244b7d809a7.png)
![2021-04-16 18_09_40-_AncientDetective S01E01 test vtt - Subtitle Edit 3 6 0](https://user-images.githubusercontent.com/1691076/115093207-95099800-9ee7-11eb-8448-ba6de24c01c3.png)

**Comment by niksedk** [comment]
You can apply color/italic/alignment to multiple lines (Ctrl+A select all lines in the list view - shift+mouse-click to select a range),

**Comment by BDGreyson** [comment]
Sorry for barging in, I THINK my issue is mostly related to this, otherwise I apologise and I can open a new issue:

I just subtitled something in VTT format and at one specific point wanted to change the alignment to "line:70%".
Se only gives me the nine predefined directions, which, in this specific case, was not working well with the scene.

So I finished everything and changed SE's "line:50%" to 70% manually in a text editor, and it's working as intended in, for example, VLC.

BUT: If I open this changed file in SE again, it seems to interpret it as 50%, displaying it wrong in both, text and preview.
If I now change anything else, like adding new subtitles or anything, and save this, it'll, of course, overwrite my 70% with the 50% again.

Is that an error, or am I using the feature wrong?
![Subs](https://user-images.githubusercontent.com/50461895/126863746-4b4e7967-5578-496b-b9b2-8e9c9bfc9ce2.png)

**Comment by niksedk** [comment]
@BDGreyson: In latest beta your can define your own settings the the nine alignments supported by SE:
![image](https://user-images.githubusercontent.com/1261331/126865386-f3e708bd-b870-4439-89ca-d42552367552.png)

https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.1/SubtitleEditBeta.zip
