### ISSUE TITLE
DCI default issue

### ISSUE THREAD

**Issue by igitlin** [SubtitleEdit/subtitleedit#5032]
HI, SE don't remember and always reset DCI subtitle settings to wrongs
![изображение](https://user-images.githubusercontent.com/30923527/117574852-cb51c600-b0e7-11eb-97cb-a3c0c92f381b.png)
Fonts 
Color
Size
Problem has if import SRT and set D-cinema InterOp as output.

**Comment by F5System** [comment]
I do confirm that when you close and reopen application it resets "D-Cinema interop (.xml)" settings to default.
Looks like this "default" settings somehow corresponds to the settings of the author. Because several versions ago "Effect color" changed to red
![SE-2](https://github.com/SubtitleEdit/subtitleedit/assets/7966722/40ac7892-e812-4a50-a67c-32fc01f297e9)
and in the last version 4.0.2 it changed to grey
![SE-4](https://github.com/SubtitleEdit/subtitleedit/assets/7966722/ab3eb15c-f4b0-4907-8824-2fc03aa9edbe)
And you have to remember about this bug and change it everytime you want to save new DCP subtitle.

The simple "workaround" of this is to open some old D-Cinema XML subtitle first, go to settings "File -> D-Cinema interop properties" to "save" this settings in memory (see screenshot) and only then open your new subtitles - this way settings pasts from your old to the new subtitle.
![SE-1](https://github.com/SubtitleEdit/subtitleedit/assets/7966722/9d654353-9452-4c5c-9708-3b36396bf16f)

But with every application update you have to recheck that nothing "new" appeared in D-Cinema workflow :)
