### ISSUE TITLE
Opaque box on the second line

### ISSUE THREAD

**Issue by Andrebavila** [SubtitleEdit/subtitleedit#5045]
Is it possible make the opaque box be like this, instead be reduced on the second line to the text?
Thank you.

![BlazeTV mp4_snapshot_00 01 700](https://user-images.githubusercontent.com/64425752/118188358-a37b9e80-b416-11eb-879b-afbd0ad79cdc.png)

**Comment by LeonCheung** [comment]
If you are handling with the .ASS format, This is something I always want to achieve too. However, we cannot simply make that happen for now since the opaque box doesn't support that. However, you can draw a rectangle in an individual line as a background box. For example, if you want to draw an 800*100 rectangle, using the draw command like this:

`{\p1}m 0 0 l 800 0 800 100 0 100{\p0}`

Indeed, it is cool to have a kind of auto-generation on this effect. I'm planning to propose some cool preset tools for dev's reference, and this is one of them.

**Comment by Andrebavila** [comment]
Thank you, Leon.
It would be a tool very nice.
I think this is the modern way to do a background box.
The SE would be amazing if have this.
