### ISSUE TITLE
Netflix Quality Check

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#5091]
So, my file was being rejected because they want the 3-11 gap to be followed to the book. As my understanding is that 2 frames at 29.98FPS are 67ms and 11 around 370. So, I bridged all the gaps less than 500ms just to be sure and then made a gap of 67ms. That should have covered it all. And it did in Quality Check. They said there are still 3-11 issues and sent me the fixed file. Now when I check the file they sent, I still get 3-11 errors in Quality Check.
![Untitled](https://user-images.githubusercontent.com/28671050/120620052-042a5400-c476-11eb-96a5-da6ac5079164.png)
So, error at 794. Why? Gap between 793-794 and 794-795 is exactly 67ms aka 2 frames. Why the error? 

Two, I get a lot of errors of less than 2frames gap if the duration between them is less than 83ms. Why so? 83ms is correct for 23.98FPS, not 29.98FPS. Quality Check should take into account the framerate of the video.

But right now, help me with the first issue. 

Thank you.

**Comment by OmrSi** [comment]
I didn't do a lot of testing on NQC for frame rates other than 24.
Netflix said recently that all number of frames should be adjusted based on the frame rate, what I got basically is that it's more of a half-second gap.

Right now I opened a file and added two lines, first tested with 67 ms gap, NQC didn't show any errors, then with a half-second gap, aka 14 frames, it didn't give any errors either.

I can't seem to recreate the issue here.
Maybe the file could help?

Also, do you have a video opened when you do the checks?

**Comment by uckthis** [comment]
Can't share the full file; NDA and all. Here are the troubled parts.

Gives 3-11 errors with or without the video opened. 
Video is 29.98

[Test.zip](https://github.com/SubtitleEdit/subtitleedit/files/6590866/Test.zip)

**Comment by OmrSi** [comment]
[SubtitleEditBeta.zip](https://github.com/SubtitleEdit/subtitleedit/files/6591322/SubtitleEditBeta.zip)

Test this out.

**Comment by uckthis** [comment]
Yes, good now. And the 2 frame gap error is fixed too for 29.98 (67ms). I don't have a 23.98 file now, but I hope it will give the 2 frame gap error if the gap is less than 83ms. 
Overall looks good.


Any ideas why they say there were 3-11 issues when I have all gaps 67ms? They use EZTitles, I think.
