### ISSUE TITLE
Changed Play Rate (Speed) actually remains "Normal" after restart SE

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#51]
When changing the Play Rate (Speed), say, change it to "Very Fast", after restarting SE, it will display as "Very Fast", but actually plays at normal speed, unless setting it again manually. Thank a lot for checking!   :)

**Comment by LeonCheung** [comment]
@niksedk Please help to confirm if this is a fishy bug. Thanks.

**Comment by darnn** [comment]
Wait, if I might ask, where are you even seeing this? I thought it wasn't possible to change playback speed.

**Comment by niksedk** [comment]
![image](https://user-images.githubusercontent.com/1261331/35769040-4e69715c-0905-11e8-9160-963713d58885.png)

Again, mpv is nice in this situation as sound is not distorted.

**Comment by darnn** [comment]
Oh, incredible! I didn't know it was there the whole time and I just needed to generate a waveform to do it!
Is there any way you could turn it into its own option separate from the waveform? Should I open a separate issue? I understand if not, since this is perfectly usable, I'd just rather not generate the waveform and then not use it if it can be avoided.
And, anyway, I didn't mean to hijack Leon's thread.

**Comment by LeonCheung** [comment]
@niksedk Sorry but I don't quite understand, do you mean I should use VLC instead of mpv in this case? It occurs when I use VLC too, I'm afraid.

**Comment by niksedk** [comment]
Play speed is not saved/restored...

**Comment by niksedk** [comment]
Fast is a factor of 1.2, and very fast factor is 1.6
