### ISSUE TITLE
3.6.1 Slow OCR Performance via command line

### ISSUE THREAD

**Issue by nieuwoudtza** [SubtitleEdit/subtitleedit#5125]
Hi,

When running OCR on a .sub file in the **GUI** version of the tool - the task is finishes in **19 seconds**.
When running OCR on a .sub file in the **command line** version of the tool - the task is finishes in **150 seconds**.

GUI: Every setting was left default
Command Line: SubtitleEdit /convert "input.sup" subrip /fps:25

**Comment by inieuwoudt1** [comment]
Not sure if same issue as #4340.
I'll close if it is.

**Comment by double16** [comment]
Using 3.6.6 here and I see this because the images being processed are different. For some subtitles, when I uncheck 'custom colors' I get white background and black font. OCR is 'fast'. From command line, I've captured the images and the background is white, the font outline is black and the interior of the font is white. OCR takes longer and is far less accurate. Possibly the longer run time is because Tesseract is having a harder time with the outline fonts?

**Comment by mhdevop** [comment]
Adding myself to this. I can confirm what is being said here even in version `3.6.12`

Using the GUI is quick! For whatever reason the command line (Batch Converter) is very slow. I'd be happy to test or try something if there are ideas?
