### ISSUE TITLE
String conversion error when pasting text

### ISSUE THREAD

**Issue by bryce-lynch** [SubtitleEdit/subtitleedit#5152]
I use a simple text editor (leafpad) to compose subtitles before pasting them into SubtitleEdit. Sometimes I get an exception when I paste the Text box: "String conversion error: Partial byte sequence encountered in the input" ([screenshot here](https://i.imgur.com/kQwvTUH.png))

I'm using SE361.zip under Linux (wine 6.11, wine-mono 6.2, arch linux kernel 5.12.12 x64).

Thanks for this invaluable tool!

**Comment by niksedk** [comment]
Sorry, that's a known error in mono...

**Comment by PJaros** [comment]
@niksedk I installed subtitle-edit 3.5.13.192 with snap on Ubuntu 22.04 and I get this message I should report it here.

Maybe you should add a some code, that case you mention that it's a mono error that won't be fixed instead of telling users to come here?

![Image](https://github.com/user-attachments/assets/2ce49973-88be-4d63-b902-277daae8fc82)
