### ISSUE TITLE
Move parts after cursor goes to next

### ISSUE THREAD

**Issue by lambdacore12** [SubtitleEdit/subtitleedit#5257]
Hello.
If only "move text after cursor to next subtitle" would behave like "move last word to next subtitle". Right now, it automatically goes to the next subtitle, but there are still changes to be made in the current subtitle. I suggest an option in the tools to activate/deactivate "go to next" after this option to satisfy everyone.

**Comment by LeonCheung** [comment]
Hmm, so why not use this option AFTER everything else is done for that part?

**Comment by lambdacore12** [comment]
@LeonCheung Because it would mean additional work especialy if the length of the subtitle is not appropriate (too long):
1-Fix sub 1
2- Move sub 2 forward to search for sub 1 ending
3- Go back to sub 1 to set end
4- Go to sub 2 to continue working
While if the option was to stay on current sub, it would save some effort, just like with "move last word to next subtitle"

**Comment by LeonCheung** [comment]
I know, but IMHO the current behavior is originally designed to save tons of copy-paste work based on an existing timecode,(e.g., when in translation mode). For that, I would NOT expect devs to change it. But I would agree that you made your point, though it's highly workflow-related, for me, I would rather deal with all issues right before closing the project because we should do a final checking anyhow, right? So, it should be a separate shortcut.

Oh, that's why I propose the idea of **Customized Shortcut** in #4928, so that we can create our own shortcut just by modifying the behavior of an existing one a tiny bit.

**Comment by lambdacore12** [comment]
@LeonCheung  I had a look at your issue and the idea is interesting. With that being said, I have already implemented my own "custom shortcuts" using AHK. I have almost 11 of them working on SE! And by the way, I have coded a workaround for this exact issue using an AHK script and I was thinking maybe others have been having this issue, so that's why I posted it.

**Comment by darnn** [comment]
Just curious, what other AHK shortcuts do you have for SE?

**Comment by lambdacore12** [comment]
@darnn  OK.
1- This one is not really for SE but I use it a lot there : "autohotstring", which allows you to type a few letters to get a whole word or even a sentence (example: just type "hw" to get "how do you do today?").
2- One I made just two days ago about this very issue, which fixed it for me.
3- I want Alt+Del to delete current subtitle, but it is only available if list view is in focus, so I made a workaround to make it work while text box has focus.
4- While a current subtitle is selected, i want to be able to drag the beginning of next subtitle (keep in mind that it is not selected) all while using a single button.
And many others...

**Comment by lambdacore12** [comment]
@LeonCheung For what purpose do you use this shortcut?

**Comment by LeonCheung** [comment]
I used it when I have to copy-paste a large paragraph (with no breaks) from a text editor.
