### ISSUE TITLE
ASSA font size issue

### ISSUE THREAD

**Issue by Andrebavila** [SubtitleEdit/subtitleedit#5300]
Suddenly, this is happenning.
The number 22 was fine for me, but, now, is tiny.

I'm using MPV.

![ERROR1](https://user-images.githubusercontent.com/64425752/131419918-182f0151-0729-452f-a43b-2d8dd2748184.jpg)

**Comment by LeonCheung** [comment]
It seems you used to leave the resolution setting untouched, right? Since v3.6.2, SE would automatically set resolution based on the loaded video. See #5284

![QQ截图20210831094500](https://user-images.githubusercontent.com/494788/131429049-d1bffd6d-4338-4abe-946f-19e2c0b3c7dc.jpg)



Previously, it was set as 0 x 0 by default, in which case, the code would assume it as 384 x 288.

This is the proper workflow, the solution is very simple, **just use a larger font size.**

**Comment by Andrebavila** [comment]
Thank you very much, @LeonCheung!
I really didn't know abou that!
Thanks thanks!
