### ISSUE TITLE
Feature Request: Add option to save and load all sync points for 'Point sync via other subtitle'

### ISSUE THREAD

**Issue by kobygold** [SubtitleEdit/subtitleedit#5318]
Hi,
Can you add option to save and load all sync points in 'Point sync via other subtitle'?
Save to file and load from file (preferable text file).
That would be very useful for synchronizing difficult subtitles in several iterations (subtitles that need many sync points, such in case where some scenes are missing on the movie). The idea is to use the 'Point sync via other subtitle' once, save the list to file, then check the outcome to see if all intervals are OK, and if not, run it again, load the list from the file, add more sync points, save the list again to the file, and check again. This will allow repeating the process and adding new sync points each time until the subtitle file is synchronized correctly.
It is very difficult to synchronize subtitles with missing scenes in any other way.
I couldn't find this workflow in any other software, and it would be very powerful!

**Comment by kobygold** [comment]
Hi,
With my C# (slightly limited) knowledge, I managed to make the change by my own!
Thanks for the sources zip file in this repository!
Let me know if you want me to send you my changes, to merge into the official version.

**Comment by zootie** [comment]
I've been meaning to suggest this too (or look into doing it myself, so if you posted the code somewhere, let me know please). This would be a nice feature, to be able to sync iteratively. 

Thinking about it further, rather than saving the syncpoints between using sync dialogs, it would be better to be able to have an active list of points on the main interface (and have a dialog to load them from another file). That way, you can use the waveform to move the lines, in a natural flow consistent with the rest of the interface. To add a syncpoint, you would have to use a modifier hotkey (something like Ctrl+Drag), so you could flag the new time index for the selected line (and then show an icon for the new time index, maybe an anchor with a line towards the line, or a crossed out time index in the list of lines). You would have tools to remove a syncpoint, list them (a list of points), and to apply the syncpoints. It's more complicated than merely making them persistent outside of the sync dialogs and I'm not familiar with the source code to do it myself, so putting it out there in case someone else is also interested, or I my get around to do it someday.

**Comment by kobygold** [comment]
Hi Zootie,
I saw no interest in my code changes so I didn't post them anywhere (I
posted my original comments almost a year and a half ago).
I've uploaded my entire code to my google drive here
<https://drive.google.com/drive/folders/1JcpFcpLw1ovLvbJHMdI2yzFgawafwDlu?usp=sharing>,
so you can try them if you like.
I don't really remember how I did it exactly, so I placed the entire folder
7zip inside my google drive folder above, together with the original
7zip sources folder,
so you can compare the two versions and see what I did if you like.
About your suggestions, those are too complicated for me, as i'm not a big
expect on this source code, and again, I don't really remember what I
did... It was a long time ago.
I hope my sources will help you.

Cheers,
Koby
