### ISSUE TITLE
Save error with saving as .stl from .srt (txt)

### ISSUE THREAD

**Issue by korp-2** [SubtitleEdit/subtitleedit#5447]
Hi. We like to use your Subtitle Edit tool. But sometimes error occurs when we are trying saving as .stl from .srt(txt).
Here is our algorithm. First we open .srt file. Then, we pick scripts as 28595 Cirillic (ISO) and EBU STL (*.stl). Then we press "Save". By this moment everything seems to be OK. But once we close the tool and open .stl file, we see these symbols: ???? instead of letters, and there is Unicode (UTF-8 script) or 1251: Cirillic (Windows)
Here is the screenshot: http://joxi.ru/LmGBj5Qig1O6Or

This error occurs with different versions, we tried from 3.5.13 to 3.6.2.
We used machines with Win7 Home (Maximum), Win10, Russian language.
Please let us know is there any way to avoid this bug. Or is there any existing fix work.
We are waiting for your answer,
Regards...

Russian text:

Добрый день. Мы пользуемся вашей программой Subtitle Edit. Нам нравится использовать её в работе, но иногда возникает ошибка при переводе из формата srt (txt) в stl.
Действия. Мы загружаем файл srt. После выбираем в настройках 28595 Cirillic (ISO) и EBU STL (*.stl). После делаем Сохранить. Отображается нормально. Но стоит закрыть программу и загрузить файл stl, то вместо букв появляются знаки вопросов - ????, а вверху отображается выбор Unicode (UTF - 8), либо 1251: Cirillic (Windows).
Скриншот:
http://joxi.ru/LmGBj5Qig1O6Or

Данная ошибка возникает при использовании разных версий, пробовали от 3.5.13 до 3.6.2.
В работе использовались компьютеры с Windows 7 Home (Максимальная), Windows 10. Язык системы русский.

**Comment by darnn** [comment]
When you're saving the STL file, the "EBU save options" window pops up. Here, for "character table", pick "Latin/Cyrillic". I also changed the code page number to 850, but I'm not sure if that's necessary or not.

**Comment by korp-2** [comment]
> When you're saving the STL file, the "EBU save options" window pops up. Here, for "character table", pick "Latin/Cyrillic". I also changed the code page number to 850, but I'm not sure if that's necessary or not.

Import options from file, but sometimes error:
http://joxi.ru/krDBxjeigoQDD2

**Comment by darnn** [comment]
I'm afraid that's probably beyond what I can help you with, as I'm just a fellow user, but could you explain further, either in English or in Russian?

**Comment by korp-2** [comment]
We haven't seen regularity of error

Мы не заметили регулярности появления этой ошибки. После запуска программы Subtitle Edit и перевода в формат .stl несколько раз разных srt-файлов, на каком-то возникает ошибка с ???? в тексте при повторном открытии.  Иногда делаешь второй раз и эта ошибка не появляется при повторном открытии stl-файла. Иногда три раза переводишь в stl один и тот же srt, а ошибка каждый раз. У кого-то не проявляется так часто такая ошибка, либо её нет. То есть пробовали закрывать и открывать снова, переводить в stl - возникает ошибка иногда. Даёшь другому этот файл srt - нормально может с первого раза перевести в stl.

В общем, мы не смогли понять, при каких условиях эта ошибка возникает.

**Comment by darnn** [comment]
Hmm, so you're basically saying you don't know how to reproduce it?
My only real suggestions (and I'm not the developer, mind you, I'm just saying this as someone who has submitted bug reports here) are these:
1. If you do see a file where, on specific computers, the conversion into STL usually goes wrong (but not always), try to mess around with it on those computers until you manage to reproduce it every time. For instance, find the smallest file that this happens with more or less consistently, and see if you can't change things about it (deleting lines, special characters, changing encoding) in order to make it happen more or less frequently.
2. If this doesn't happen with the same files on different computers, aside from making sure you're using the same version of Subtitle Edit, try copying the settings.xml file from the SE folder on the affected computer to the unaffected computer (you can always just copy the portable version to a different folder and replace the settings file there, so as to not mess up the primary one). See if that affects the outcome any.
Also, if you have specific files with which it happens frequently on certain computers, try attaching a few of them here, so we could at least try them out on our end.

And let me know if you need me to translate this into Russian. I'm afraid that while I can read Russian fine, formulating actual sentences in it, let alone spelling the individual words, is much more challenging for me.

**Comment by PascalsHere** [comment]
Have similar problem, When I try to save it, SE stops responding, I also had https://github.com/SubtitleEdit/subtitleedit/issues/5122 happen to me. Maybe related?

**Comment by PascalsHere** [comment]
The quick solution to this is to convert it to another format then convert it to stl, That works for me now, But this is still annoying.

**Comment by PascalsHere** [comment]
Have issue when scc to stl too...
