### ISSUE TITLE
Frame rate 29,97 is automatically changed to 30 when exporting EBU

### ISSUE THREAD

**Issue by Robinsimus** [SubtitleEdit/subtitleedit#5666]
Hello,

I have a problem with the exportation of EBU stl files. If I set the frame rate in the EBU stl properties to 29,97 with Disk Format code of 30.01 and I press OK,
![image](https://user-images.githubusercontent.com/97104773/148067402-2d4807d4-3dd4-4b59-b565-84abfed9fe04.png)

 when I go back to properties it's set authomatically to 30 again.
![image](https://user-images.githubusercontent.com/97104773/148067510-fead9426-41a7-42a8-97f9-bc76d987f16f.png)

How do I solve this?

Thank you!

**Comment by BattleAlchemist** [comment]
'Frame Rate' is not actually a field within the EBU STL file format - the frame rate is only expressed in the 'Disk Format Code' above (STL25.01, STL30.01, etc).

Technically speaking only frame rates of 25 and 30 are officially supported by the spec, so other software or equipment may not interpret other values in the way that is expected, but you'll see the Subtitle Edit will let you select a disc format code of, for example, 'STL29.01' which I believe should be interpreted as 29.97 frames rather than 30.
