### ISSUE TITLE
[Feature Suggestion] Translator mode based on indexes instead of timestamps

### ISSUE THREAD

**Issue by cyzs233** [SubtitleEdit/subtitleedit#5778]
Currently seems to use timestamps to match two subtitles, It's fine if you're translating from scratch. But if you're working as a group on a translation, or editing upon others work. Binding translation with original subtitle through timestamps will make fine tune unbearable in subtitleedit. 

Below is a demo used to confirm that currently, translator mode is based on timestamp.
![timestamp based approach in translator mode](https://user-images.githubusercontent.com/25927091/153772103-a0689533-9b8a-4f49-810e-cc137d467818.jpg)

Feature suggestions:
- Translator mode based on subtitle entry indexes instead of timestamps
   Couple drawbacks in current timestamps method.
   - buggy display if opened original subtile doesn't have identical timecode with translation. (text disappear & repeat)
     ![mess in translator mode](https://user-images.githubusercontent.com/25927091/153769212-ebf4cbf7-4a4d-400d-bc99-d889d3167f61.jpg)
     It says translator mode, so the focus should be text, assuming users use original subtitle with same total line and identical timecode is a bold assumption. 
Especially consider user can't edit text without interfering each other in translator mode's text-edit-panel,  cause they're linked through timestamp for some reason. 
If user ever want to make some adjustments to a single subtile, then it's good luck for user, notepad might be quicker than master subtitleedit shortcuts.

    - Unwanted overwrite caused by timestamps
     more in #5779, I believe they are all caused by internal timestamp-related logic.

    For indexes method, in my understanding, it's an enhancement. It won't interfere current subtitle user's workflow. Cause previously, translation and original are line matched anyway, they'll still appear&manupilated side by side in text panel, plus index method will enable have more control through waveform panel

- Edit translation and original subtitle independently in waveform panel

   This will be possible with index method, User can now add/delete subtitle entries to their needs. Choose edit in waveform panel cause it might be easier to implement than overhaul current text panel, and there is already enough option to achieve basic editing in waveform panel. 
More importantly, users can adjust timestamp of both translation and original subtitle without interfering each other. This'll extremely helpful in translation production since translated text might shorter/longer than the original. They can now fine-tune translation's timestamp during translate-stage, saving extra effort to sync by hand afterward.

One may argue how to display both original & translation timecode in the current text panel?
Since the mode is transltor mode, the focus should always be translation. "Show original in waveform" should be more than enough for user to make micro-adjustment to the original.

Below are two sample subtitles, their timestamp and line number differs, but translation is reasonably well done.
Currently, subtitleedit have all the tools needed to tweak them into a bilingual subtitle, translator mode is the perfect place for this kind of task (side by side compare + waveform adjust). 
But its productivity is limited by current translation&original linking (through timestamp). Sincerely hope this can be improved.❤
[I.Served.The.King.Of.England.2006.chs.srt.zip](https://github.com/SubtitleEdit/subtitleedit/files/8054183/I.Served.The.King.Of.England.2006.chs.srt.zip)
[I.Served.The.King.Of.England.2006.eng.srt.zip](https://github.com/SubtitleEdit/subtitleedit/files/8054184/I.Served.The.King.Of.England.2006.eng.srt.zip)

**Comment by LeonCheung** [comment]
@cyzs233 I totally agree that it would be really useful to have a feature like "import plain text as translation", which means to automatically enter translation mode and have the imported text ready for proofreading, so that your No.1 feature suggestion can be well met.  

For your No.2 suggestion, actually, you can assign a shortcut to switch between translation and original, which could be  However, I don't think your suggestion is applicable because it would display timecodes differently for list view and waveform, which is not good obviously. Imho, a more practical solution would be something like #1344. 

For your No.3 suggestion, actually, you can already add or remove subtitles from the waveform.

**Comment by cyzs233** [comment]
@LeonCheung @darnn Sorry for not state iit more clearly, but this issue isn't about "import plain text" related stuff, is about enable more control&readbility in Translator mode.
Below is a translation sample with timestamps differ from English subtitle avaliable.
![subtitleedit translator mode using timestamp](https://user-images.githubusercontent.com/25927091/153714775-b9e79055-8fd5-477b-8f97-2d416ce39cae.jpg)

This is common in subtitles from Netflix, where all subtitles are translated & timed independently by individual translators, you'll hardly find a single timestamp match with English subs.

The situation will get worse with different framerates, in that case, the original and translated lines probably won't be on the same screen.

For No.2 suggestion. 
SubtitleEdit do have an option in the toolbar. 
![show original text](https://user-images.githubusercontent.com/25927091/153716207-fef79765-6fb7-47e8-9d27-441eb5670fa6.jpg)
But delete waveform will delete line both in translation&original, delete timestamp only in one subtitle may result in a bunch of extra work in the above situations. Thought using indexes will be more effecient.
Also, this option in toolbar located in toolbar is fine with me, but it might more intuitive to put it in the waveform panel.
![select original](https://user-images.githubusercontent.com/25927091/153716716-37ae7b18-00cc-4031-98b6-05e92e41bb0a.jpg)

For No.3 suggestion. 
Sorry for my rush, it does have a shortcut for this (insert/delete). This is used quite often, why not put it into right-click-menu too?

The main motivation behind this is to make two subtitles line matched, so that you can generate a bilingual subtitle later. 
In this case, timestamps in translated subtitle aren't needed at all, since original subtitle's timestamps should always be checked by user, if translation and original are line matched, you can just import timecode from original without causing any trouble.
Sorry if timestamps are useful to you, I'm open to corrections.

**Comment by darnn** [comment]
@cyzs233, I think you may have misunderstood me. In your first screenshot, it seems like you opened one subtitle file, and then used file->open original subtitle (translator mode) to open another subtitle file, with different timecodes (and possibly a different number of lines). This creates an unintended situation, like what is seen in your screenshot, where a line in one file that doesn't have a matching timecode in the other is left with a blank line next to it. Like in the first line in the screenshot, "original text" is empty, and in the second line "text" is empty.
This is not the intended way to work with a pair of files. "Open original subtitle (translator mode)" is only meant to be used when you have two files with the same number of lines and the exact same timecodes (like what SE itself creates).
In order to get this:
![se-translator-mode-lines](https://user-images.githubusercontent.com/19672444/153720111-46542bf8-342d-4e54-8bfe-344bc7a81670.png)

You need to follow the steps I outlined in my previous post. Open the subtitle file with the desired timing, and then, and this is the important part, use tools->make new empty translation from current subtitle. Now paste the text of the translation into this new file. If you want me to explain step by step in more detail, I can do that.

**Comment by cyzs233** [comment]
@darnn Thanks for the explanation.
Do you happen to know how to line match those two .srt files?
[I.Served.The.King.Of.England.2006.chs.srt.zip](https://github.com/SubtitleEdit/subtitleedit/files/8054183/I.Served.The.King.Of.England.2006.chs.srt.zip)
[I.Served.The.King.Of.England.2006.eng.srt.zip](https://github.com/SubtitleEdit/subtitleedit/files/8054184/I.Served.The.King.Of.England.2006.eng.srt.zip)

**Comment by darnn** [comment]
Well, there's no magic solution, you'll still need to get both sides to match, but to start with, if you, for instance, want to match the Chinese to the English:
First make sure the translation has the same number of subtitles as the source, or less. If the translation has more, first open the source file and add as many blank subtitles at the end as necessary for the number of subtitles in both files to be equal. In our case this isn't necessary because there are less subtitles in the Chinese file than there are in the English one.
Now, open the Chinese file in SE, in list view, select all the subtitles, and then right-click on them and click "copy as text to clipboard":
![se-sync-01](https://user-images.githubusercontent.com/19672444/153722760-a5e6f5c0-36f6-4fb3-9c5a-598255bad75f.png)

Now open the English file. Go to the tools menu and click on "Make new empty translation from current subtitle":
![se-sync-02](https://user-images.githubusercontent.com/19672444/153722816-734a9560-60fe-48ea-9f6e-6ef1601dbff9.png)

The window will now look like this:
![se-sync-03](https://user-images.githubusercontent.com/19672444/153722849-db7a08a4-a57b-4c2f-a8f7-f66e816f1aac.png)

Now, if you haven't done this yet, go into the Options menu and there into Settings. Here go to Shortcuts. Under List View, find the entry for "Column, paste", and set a keyboard shortcut for it (for me it's Control+G). Click OK.
![se-sync-04](https://user-images.githubusercontent.com/19672444/153723060-f0bad576-61fe-4015-9b8c-36675c6b258b.png)

Now click on the first line in list view, and then press the keyboard shortcut for column paste. The result should look like this:
![se-sync-05](https://user-images.githubusercontent.com/19672444/153723159-fd4f81af-a277-48ae-aadf-f01e526d1ce1.png)

Save the new translation file. Now you can start going over the lines and making them match the English, using the shortcuts I mentioned earlier:
"Column, insert text" and "column, delete text and shift up" (in settings->shortcuts->list view), and "move last word to next subtitle" and "fetch first word from next subtitle" (in settings->shortcuts->text box).

**Comment by darnn** [comment]
As for your question of how the two things are different: When you use "open original subtitle", Subtitle Edit assumes you have two files with an identical number of subtitles and identical timecodes for each subtitle. If this is the case, they both open properly, without the entries disappearing and reappearing and so on.
When you follow the process I've described, you're only using the timecodes from one file. Subtitle Edit creates a second file with no text, but with an identical number of subtitles which all have the same timecodes as the first file. Then you only paste the text from your translation file into this new, empty file. Now, when you save it, you have two files with the same number of subtitles, and they have the same timecodes, but one contains the original text and one the translation. From this point you still need to make adjustments in order for them to match, but since you're now only working with one set of timecodes, there should be no buggy behavior of the sort you described.

**Comment by cyzs233** [comment]
@darnn thanks for the instruction. 
The re-edit part is harder than you think. I spend 4 hours adjusting text on both sides to make them match. I would rather translate myself if I know it's this time-consuming.

But since subtitleEdit already has cool features like split&merge. If I can edit both subtitles independently in translator mode (side by side compare + waveform adjust), the estimated time would only be 30 minutes.

**Comment by darnn** [comment]
I mean, if you want to have two different subtitle files, one for each language, and synchronize them independently, go ahead. I would think everything is already in place in Subtitle Edit to do this, but I can't speak to it one way or the other because I never use the waveform function.

Now, I thought you wanted a bilingual file in the end. In order to create one, you'd have to have what I described above, two files with the same number of lines and time codes, where each subtitle in English matches the equivalent subtitle in Chinese. Whether or not you've already spent time synchronizing both of these files by hand makes no difference, since in a bilingual file you can only have one set of timecodes.
Personally I find it much easier, when I already have one file with the proper timecodes, to adjust the text to match the timecodes rather than change the timecodes in any way. Especially since nobody pays me to do that, but they _do_ sometimes pay me to adjust translation text to match the timecodes of the original subtitle. But I suppose it's a matter of preference.

**Comment by cyzs233** [comment]
> Whether or not you've already spent time synchronizing both of these files by hand makes no difference, since in a bilingual file you can only have one set of timecodes. 

only line match is required to make a bilingual, original sub will be edit as needed in the process.
> In this case, timestamps in translated subtitle aren't needed at all, since original subtitle's timestamps should always be checked by user, if translation and original are line matched, you can just import timecode from original without causing any trouble.

**Comment by cyzs233** [comment]
@niksedk would you mind take a relook at this issue?
I didn't convey my thought clearly previously, causing some unrelated discussion, hope I did a better job this time.
