### ISSUE TITLE
[Help] Generate Timecode from scratch

### ISSUE THREAD

**Issue by cyzs233** [SubtitleEdit/subtitleedit#5795]
I have couple audio transcription .txt done by translators, now I have to generate timecode to make them subtitles. (english text with english audio)

Since it's 2022, any suggestion that can save me from manually edit every single line?

Suggestions that might speed up the process are also welcome. (1000+lines, estimated 5 hours by hand 😑)

Currently, I can use speech to text to get a rough timecode. But to actually use the timecode, I have to edit the subtitle generated by speech to text, to make it at least line match with the audio transcription .txt, then "import timecode" + later fine-tune. 

Saw you wandering around a lot, do you have any tricks in your pocket? @LeonCheung 

Update:
Seems Youtube offer the option to auto generate timecode for you (upload transcription text same language as audio). [Better audio quality preferred](https://support.google.com/youtube/answer/2734799)
Now, we have to find a way to flatter the Youtube God to process my seeming scam video faster 🤔(blank video track to reduce size)

**Comment by LeonCheung** [comment]
Hi, well, IMHO, it's all about which workflow you are taking. The most proper workflow for jobs like this would be:

**Step 1:** Transcribe, or, if you already got the script in hand, prepare it with proper breaks, say, at full stops, or commas, etc, or pre-break some long lines if necessary to meet the CPL requirement, which could be done in any text editor.

**Step 2:** Make subtitles, manually or automatically. Here I highly recommend doing it manually because auto-made subtitles are far from perfect. You have to go through the whole video to revise it for acceptable quality. According to my experience, I don't think technical solutions like AI/ML can handle it in the near future because trust me it's very, very complicated to achieve proper breaks in many cases because it really depends on many factors like language, culture, tones, pauses, CPS, CPL, etc. 

**Step 3**: Translate the subtitle. Or, you can also translate the script earlier than this, in which case, what you are going to do here is to distribute translations accordingly so that they can well match the original subtitle. We have some nice tools for that in SE.

That's it.

**IMPORTANT:** never trust any auto-generated timecodes in 90%+ cases, even it's 2022! 有修改的工夫不如早就手打完了。

**Comment by LeonCheung** [comment]
By the way, speaking of your complaint about "1000+lines, estimated 5 hours by hand", actually, I think it's all about how well you master SE.  :)  For a regular 1 hr film, usually, I can finish the subtitling work within 1~2 hrs with some nice shortcuts. FYI.

**Comment by cyzs233** [comment]
@LeonCheung Thanks for the insights, cleared my twisted mind, will be checking some shortcuts to speed up workflow.

About auto-generated timecodes, I think it has a bright future, google already did a fantastic job with youtube auto-sub.

In the end, it's all about the time&energy you have to put into it. 
Manually edit timecode require an experienced user & he/she has to be extremely focused throughout the process, you'll easily get burned out. Whereas with auto-generated timecodes, it doesn't have to be accurate, they're here to remind users where the speech actually happens. Fix timecode is trival & easy in subtitleedit, you can therefore split the task into groups and co-working on that.

**Comment by LeonCheung** [comment]
Right. A bright future indeed, just not at the moment.  Honestly, to me, youtube auto-sub sucks. XD  I mean the transcription works great, but definately not the sub.part,  too many improper breaks and splits, not mentioning the no punctuation issue.
