### ISSUE TITLE
[Feature Request] Adding Glossary to Subtitle Edit

### ISSUE THREAD

**Issue by Hai-Lag** [SubtitleEdit/subtitleedit#6001]
Hi Team...
Hope you are doing well!

I have an additional feature I would love to have in SE which is the Glossaries.
I know that SE has the dictionary feature but this is a bit different thing.

The glossary is a list of pre-translated words in a CSV file (there are other extensions IDK about) [see attached screenshot for a sample: 
![image](https://user-images.githubusercontent.com/61273443/171120052-61db0c98-e270-43d4-9e50-4b21e30d82a8.png)
.  

  As a translator, I receive this list from the client or help them create it, then we keep using it in our daily work.

* Important notes: 
      A-Glossary works only in translator mode/view
      B-Glossaries work with no specific direction in terms of languages pairs

How do I imagine the glossary working in SE? [Sample: AR<>EN Glossary+ Auto generated text +auto translated text, Results are amazing BTW xD ]

1-User uploads that CSV file to the project he is working on (because different clients may translate the same word differently). Or uploads many CSV files at once [maybe in a new list or menu..] and when he starts a new project, the SE asks him to choose which Glossary to use for this specific project.

2- When the user is working in translator mode/view, SE highlights the words that are listed in the glossary and if SE finds an English words that is listed in the glossary and its Arabic equivalent is not mentioned/written in the Arabic side, here SE highlights the English word in the English side and highlights the whole cell of the Arabic side [see attached screenshot for explanation: [ 
![image](https://user-images.githubusercontent.com/61273443/171128268-3a8e604a-67af-4292-b3e4-19ea9f34bdec.png)
 ]

Colors are just for explanation, but:

a- **Green** highlights both words if both exist and are correct, and it means that the user used the same word from glossary either in English or Arabic. 
b-**Red** highlights the words that are listed in the glossary [either Arabic or English] but their equivalent doesn't exist in the other side [either Arabic or English]

I hope this was a good explanation despite the fact that I am sure many know how glossaries work in any kind of software. I am attaching here a sample CSV file and if you need a bigger one or any other help, please don't hesitate to ask or contact via my email [mad3info@gmail.com]
[Glossary-combat sports.csv.xlsx](https://github.com/SubtitleEdit/subtitleedit/files/8803463/Glossary-combat.sports.csv.xlsx)

A very big thank you to you all ♥
Abdelhai

**Comment by eladkarako** [comment]
that's a nice idea,  
b.t.w., you can also install the subtitleedit plugin for the word spell-check,  
(you'll need word installed obviously).  
<img width="305" alt="2022-06-01_031918" src="https://user-images.githubusercontent.com/415238/171304066-7f497f59-95f0-4e01-bc83-3e827634b5f8.png">

ms-word allows you to check grammar as well as single-word spelling,  
and you can store custom phrases you've already fixed in the custom dictionary,  
and "replace all" to quickly fix multiple occurrences.  

<details><summary>notes</summary>
you would need a dictionaries for those languages,  
it usually comes with the installation of ms-office,  
or you can google it for the microsoft websites ("google.com/search?q=download+Hungarian+dictionary+microsoft+office+2010" for example),  
or you can look for office language packs, since the dictionaries often comes with it.  
you can also try browsing `tb. rg-adguard. net/ public. php` for language packs or installations.
</details>

**Comment by uckthis** [comment]
@Hai-Lag Download plugin first from File Menu.

**Comment by Hai-Lag** [comment]
Thank you so much guys for the help but the idea of glossaries is totally different as we know. 

If any of the engineers is working on it for subtitle edit, I am ready to explain to them how it works in other software and how it should work in SE in any way possible; chat, video call.. But I am 100% sure that this feature will be very helpful to many SE users.

Thanks again for your help and time ♥

**Comment by uckthis** [comment]
Yes, I know and use Trados Studio 2021 sometimes. Though, I only work in English 99% of time.

**Comment by Hai-Lag** [comment]
Any Updates, volunteers or ideas to make this happen, Guys? 🙏
