### ISSUE TITLE
[Feature suggestion] Screenshot option for video preview window

### ISSUE THREAD

**Issue by cyzs233** [SubtitleEdit/subtitleedit#6067]
It would be nice to have to be able to take a screenshot in subtitleedit directly. 😉

Sometimes when you're subbing, you come up with an impressive translation but it would take too much effort to load&capture it using external video players, so you put it on your todo list and never look back at it.

![Untitled](https://user-images.githubusercontent.com/25927091/177657941-2cd17727-69dc-4d2c-b15e-2f8855b60c02.png)

Some notes:
- 1. Setting for enabling capture "video control area ".
Tring to include the timestamp information. A more elegant solution would be an option to enable timestamp watermark somewhere over the screenshot.
  <details><summary>Demo</summary>

  <p>

  ![Untitled](https://user-images.githubusercontent.com/25927091/177658141-1bde8b3f-5b84-4cc9-b711-53b49ae7dab0.png)

</p>
</details>

- 2. Screenshot format option (Jpg/Png).
- 3. Filename string format.
{filename} + {timestamp} + {capture date}
- 4. Option to set default saving directory.

**Comment by eladkarako** [comment]
interesting,  
there are multiple rendering engines available (Media Player Classic, MPV, VLC,..),  
depending on user selection.

<details><summary>I've been using external tools for that</summary>  

- `mpv --vo=image:format=png --frames=1`  
- `ffmpeg -ss "01:23:45.678" -i input -frames:v 1 -q:v 2 output.png` (not accurate if it doesn't hit a keyframe nearby, or `ffmpeg -ss "01:23:20.000" -i input -ss "00:00:25.678" -frames:v 1 -q:v 2 output.png` which is slower since it needs to decode a little of the streams but more accurate).

</details>

but c# can capture the container of the video-rendered including whatever overlays it has with `RenderTargetBitmap`, `CanvasBitmap`, `CanvasRenderTarget`, and `CanvasDrawingSession`. I think it should even work if the rendering uses dshow, and compress the bitmap to jpg/png/...  

there are much more simpler Windows API to [capture the screen](https://github.com/eladkarako/kaptureScreen/blob/master/kaptureScreen/ScreenCapture.cs) and then cut just the size and placement of the renderer.

not as simple as it might seems at first..

**Comment by niksedk** [comment]
`WinKey+Shift+S` is also nice.
