### ISSUE TITLE
"Audio/Video to text" unavailable in portable SE 3.6.6 version

### ISSUE THREAD

**Issue by edcol** [SubtitleEdit/subtitleedit#6071]
Hello,

why useful feature ""Audio/Video to text" is unavailable in portable 3.6.6 version of SubtitleEdit that can be launched on Ubuntu linux?
Is there a plan to add it?

TIA
EC

**Comment by gjvnq** [comment]
I have a similar problem. If I run the executable with Mono, the option doesn't appear. But if I run with Wine then it does appear.

I tried to search for where the conditional to hide the menu entry is but I couldn't find it.

**Comment by coastal45** [comment]
Is it possible to say whether this is a Mono related issue, or vosk incompatibility with a non-Windows system?

**Comment by niksedk** [comment]
Some Linux dev/user would probably need to fix this.

First, I don't even know how to install vosk on Linux... anyone?

**Comment by edcol** [comment]
Perhaps this package?
https://alphacephei.com/vosk/

**Comment by coastal45** [comment]
This might be helpful, though I've never tried an install myself. It runs under Python, so it should not be so OS dependent.

[Offline Speech Recognition Made Easy with Vosk](https://medium.com/analytics-vidhya/offline-speech-recognition-made-easy-with-vosk-c61f7b720215)

**Comment by coastal45** [comment]
I was able to install vosk on Ubuntu 20.04. Required is python 3.7 or greater, and pip3.
This instruction is easy to follow if they need to be installed: https://itsfoss.com/install-pip-ubuntu/

Then, I could install vosk as in https://alphacephei.com/vosk/install
`pip3 install vosk`

But I don't know what to do next, as I don't know any details of the integration with SE. I'm willing to give it a go if it's helpful.
For reference, here is the basic directory structure:
![Screenshot from 2022-08-27 14-18-54](https://user-images.githubusercontent.com/102390147/187051128-89a42414-f0b1-407e-98fa-77dd7b0836a0.png)

**Comment by niksedk** [comment]
OK, the `Video - Audio to text` menu item should be be visible: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.7/SubtitleEditBeta.zip

What happens?

**Comment by niksedk** [comment]
OK, I got this:

![image](https://user-images.githubusercontent.com/1261331/187239349-79a461ae-ac41-4c46-b29d-903ac9c6db70.png)

**Comment by nshmyrev** [comment]
Its probably because runtime is 32-bit, it must be 64-bit

**Comment by coastal45** [comment]
> OK, I got this on Ubuntu 22.04:
> 
> ![image](https://user-images.githubusercontent.com/1261331/187239349-79a461ae-ac41-4c46-b29d-903ac9c6db70.png)

> OK, the `Video - Audio to text` menu item should be be visible: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.7/SubtitleEditBeta.zip
> 
> What happens?

Thanks. I got the same result.
I can only imagine SE can't find vosk because file names/location are different.

Windows (contained in SE directory)

![Screenshot 2022-08-29 182727](https://user-images.githubusercontent.com/102390147/187277786-ee8119d6-9017-4fdf-9e24-c33eb56532bc.png)

 Ubuntu (in usr-->local-->lib-->python3.8-->dist-packages-->vosk)

![Screenshot 2022-08-29 182751](https://user-images.githubusercontent.com/102390147/187277819-d8f3ee79-ca2a-4a54-bf7f-e412db929a9c.png)

But I'm not a programmer...

**Comment by coastal45** [comment]
> Its probably because runtime is 32-bit, it must be 64-bit

Which runtime? Could you elaborate?

**Comment by niksedk** [comment]
@coastal45: Does a symlink file help? 
Like `sudo ln -s /usr/local/lib/python3.8/dist-packages/vosk/libvosk.so ~Downloads/SubtitleEdit/libvosk.so` (or where SE is...) ?

(I do not have time atm - but will try in a few days...)

**Comment by coastal45** [comment]
> @coastal45: Does a symlink file help? Like `sudo ln -s /usr/local/lib/python3.8/dist-packages/vosk/libvosk.so ~Downloads/SubtitleEdit/libvosk.so` (or where SE is...) ?
> 
> (I do not have time atm - but will try in a few days...)

Fantastic, it works! Just missing a "/" before Downloads...
`sudo ln -s /usr/local/lib/python3.8/dist-packages/vosk/libvosk.so ~/Downloads/SubtitleEdit/libvosk.so`

![Screenshot from 2022-08-29 19-44-28](https://user-images.githubusercontent.com/102390147/187341074-6ca555a3-0b21-4043-83d8-51b2f467103d.png)

Progress bar???

![Screenshot from 2022-08-29 20-03-34](https://user-images.githubusercontent.com/102390147/187341433-785ed004-5b10-43d6-b9fd-f0fdd547b683.png)

Otherwise looks/works the same as Windows version.

**Comment by niksedk** [comment]
Also, if video is popping out of SE on Linux, try this settings in `Settings.xml`:

`<MpvVideoOutputLinux>x11</MpvVideoOutputLinux>`
