### ISSUE TITLE
[Request] Common errors: "Fix continuation style"

### ISSUE THREAD

**Issue by Akhilesh-T** [SubtitleEdit/subtitleedit#6124]
Hello,

I have been using rules to insert three dots if a line begins or ends with a lower case letter. I have been using them since many years.
But today I noticed that there is this new option where I can insert them with "Fix common errors". It seems that this option was added 2 years ago. It is a very useful option, especially for lines beginning with uppercase I (eye) and I can't thank you enough for including it.

However, there is one issue with it. For example, if a line ends with a continuation style (say, dots) and the next line begins after a gap/pause of 1 minute, the beginning is still considered as a continuation when it isn't needed. Yes, we can go through such lines one at a time, but when there are a lot of them in a subtitle, it can get time consuming.

Sorry if such an issue was raised earlier. But I couldn't find any solution.

Thank you for making this amazing software.

**Comment by niksedk** [comment]
@Flitskikker: Martin, could you take a look? Seems that "make new first word" should only occur if !gap ? https://github.com/SubtitleEdit/subtitleedit/blob/01186edd7a5b58d93f4443de8f2652a2c0881d91/src/libse/Common/ContinuationUtilities.cs#L481

**Comment by Flitskikker** [comment]
Hello @Akhilesh-T,

Thank you for the kind words!

Do you have an example file so I can do some testing?

When I test it now with an actual split sentence (ending with lower case, starting with lower case), it applies the continuation style, regardless of the time inbetween:

![image](https://user-images.githubusercontent.com/3516155/183260750-176f98b4-b9c3-4274-bb1d-4ab7c20ab737.png)

![image](https://user-images.githubusercontent.com/3516155/183260760-5dfae0d2-171a-42be-a5d6-d816d82d804b.png)

This is as designed, because it actually is a continuing sentence.

When the first sentence ends with dots and the second sentence starts with I (capital i), it does get added to the list, but it's unchecked by default.

![image](https://user-images.githubusercontent.com/3516155/183260897-2ec518eb-ac54-4466-8cb2-42d82f0df31a.png)

![image](https://user-images.githubusercontent.com/3516155/183260886-74bb6c0d-dcda-4985-8f39-5a84a5469d1c.png)

I'm curious to see what your use case is. Perhaps it's a language thing I'm not yet aware of.

In Dutch, when a sentence ends with dots and the next sentence starts with lower case, the only possiblity is that it's a continuing sentence, even after a 1 minute pause, so the continuation style is applied.

Please let me know and I'll take a look!

**Comment by Akhilesh-T** [comment]
I appreciate your prompt reply. Unfortunately, I deleted the file that had problems and I haven't been able to reproduce it. I'm closing this for now. But if I come across it again, I'll reopen it and let you know.

Thank you!
