### ISSUE TITLE
SE audio to text error

### ISSUE THREAD

**Issue by newburn6** [SubtitleEdit/subtitleedit#6193]
SE 
audio to text
I would like to report this error message

![error2](https://user-images.githubusercontent.com/112551906/187658313-913fddbf-7acf-44d9-92dc-bf4db340b99e.jpg)

**Comment by niksedk** [comment]
If you re-download ffmpeg, does it still happen? See Options - Settings - Waveform: click the download ffmpeg button

Another use also reported this, but his files worked fine on my PC. 
What OS are you using?

**Comment by niksedk** [comment]
Oh, and is the file really missing when the error pops up?

**Comment by niksedk** [comment]
Improved error logging in latest beta regarding this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.7/SubtitleEditBeta.zip
(will log info to `error_log.txt` in the SE data folder - press ctrl+alt+shift+d in SE main window to open this folder)

Also just updated ffmpeg to 5.1.1...  so try to re-download that too.

**Comment by niksedk** [comment]
@newburn6: Also, could you try ffmpeg in a command prompt?

Put your video and a folder with ffmpeg, and run:
`ffmpeg -i "input.mkv" -vn -ar 16000 -ac 1 -ab 128 -af volume=1.75 -f wav "output.wav"` ?

And what does `ffmpeg -version` say?

**Comment by ralcore** [comment]
currently having the same issue. weirdly (assuming the only changes in that beta are to logging) the error doesn't occur in the linked beta.zip release. the subtitles are generated as intended.
both the regular and beta flavors now installed are running ffmpeg 5.1.1-essentials.
running the sample command on either installed ffmpeg version spits out a 128kbps wav of the whole video's audio, as intended.
the file does appear to be actually missing - there's no .wav in the /temp/ directory.
feels like some weird permissions issue, since the only difference between the two environments i can think of is that one of them is portable and one uses appdata

**Comment by ralcore** [comment]
at the very least anyone running into this *should* be able to download and use the beta as a temporary workaround lol

**Comment by niksedk** [comment]
@ralcore: thx for the info :)

**Comment by Xenos71** [comment]
Hi Nikolaj,

I'm using SE 3.6.7 portable and I'm having the same issue (the file was actually missing). 
I tried to install it, and it works perfectly with the installed version. In both cases I downloaded the most recent ffmpeg.
I also tried the portable beta version you provided above and it works fine.

I'll be happy to provide any information you might need.

**Comment by Xenos71** [comment]
Hello again, 
I just found out that when I change the video player to DirectShow instead of VLC which I normally use, the problem doesn't occur and audio to text function works.
I hope this helps.

**Comment by niksedk** [comment]
> Hello again, I just found out that when I change the video player to DirectShow instead of VLC which I normally use, the problem doesn't occur and audio to text function works. I hope this helps.

thx :)
Yes, I can re-create the issue with VLC!
