### ISSUE TITLE
STL Open and Closed Captions - HELP!

### ISSUE THREAD

**Issue by Jyaelev** [SubtitleEdit/subtitleedit#6248]
Hello everyone,

A client is asking for a STL Open file with colours and positioing (French subtitle for hard of hearing people). It's for a DCP.
Everytime I try to switch to "Open" from teletext, I loose the colours and the positionning.
Some colleague tell me that it is posible to have colours and positionning in STL Open files, but I assume they are not using SubtitleEdit...
I Have also been told that I could switch to xml closed captions file for the DCP, but there are quite a few options in SE, and the ones I have tried made me loose everything...
Thanking you in advance,
Best,
Jessica

**Comment by uckthis** [comment]
STL is a very old format, and we're not fluent in that. Send the file, and I'll test with CaptionMaker and Ooona and see if it's a limitation of SE or Open captions are supposed to be like that.
All is know is that the standard framerate for an STL is either 25 or 29.98, but SE supports other frame rates as well, so we don't always follow standards if it means a better output.

**Comment by uckthis** [comment]
Please reply on Github and attach file in ZIP.

**Comment by Jyaelev** [comment]
Hi,
Thank you for getting back to me.
Enclosed is the TELETEXT file with the colours and the positioning.
My client wants a .stl OPEN file with the colours and the positioning, but when I switch from TELETEX
[L_ombre_de_Goya_VF_avecST_AvecLogoEpicentre_Mix_VF_stereo_220625_MP4.zip](https://github.com/SubtitleEdit/subtitleedit/files/9618953/L_ombre_de_Goya_VF_avecST_AvecLogoEpicentre_Mix_VF_stereo_220625_MP4.zip)
T to OPEN, I lose the colours and the positioning..
Thank you in advance for your help,
Best,
Jessica

**Comment by uckthis** [comment]
I exported as Open with both CaptionMaker and Ooona and in both instances, STL loses the color and alignment tags. I think it's STL's standard and has nothing to do with SE or any other software. Your client should not ask for a format that isn't designed to keep the color tags. 
As a last ditch attempt, use the Undefined profile and see if your client accepts that. Otherwise, ask them to send you a sample of Open STL with color tags; which they won't be able to do. 

If your colleague knows something that we don't, please edify us. 

Thank you.

**Comment by niksedk** [comment]
According to the ebu stl spec it is not possible: https://www.google.com/search?client=firefox-b-d&q=ebu+stl+spec
It might be possible to not follow the spec... but that is probably not a good idea.

**Comment by Jyaelev** [comment]
Thank you so much for looking into it.
I told my client... we'll see if she's satisfied with the answer...
best,
Jessica
