### ISSUE TITLE
Auto balance lines in batch convert.

### ISSUE THREAD

**Issue by Ding-adong** [SubtitleEdit/subtitleedit#6306]
It doesn't do anything to fix auto balance for years.

I have to use right click mouse on selected lines then use auto balance for every file.

Latest version the auto balance is somewhat deeper into menus after menus, buried and time consuming. No shortcuts either.

Auto balancing lines is important and is there any way you can fix the:
- batch convert auto balance lines
- provide access for shortcuts
- put auto balance as an option in fix common errors
- put auto balance in tools menu

ta

**Comment by niksedk** [comment]
OK. added an auto balance selected lines shortcut in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.7/SubtitleEditBeta.zip

**Comment by Ding-adong** [comment]
Any ideas on the other 3 suggestions?

Already had Alt+B as shortcut for auto balance but I'd put it up for other people benefit and to make it a permanent fixture in settings.xml file.

**Comment by niksedk** [comment]
Batch convert works fine for me...

**Comment by niksedk** [comment]
Hm, it is the same code...

Before batch convert:
````
1
00:00:02,490 --> 00:00:05,670
the catastrophe of world war
has fallen upon us.

2
00:00:13,591 --> 00:00:17,820
The brunt of the war has
fallen upon the sailor men,

3
00:00:18,843 --> 00:00:20,843
"Dear Lord,
let your holy angel be with me,
````

After batch convert:
````
1
00:00:02,490 --> 00:00:05,670
the catastrophe of world
war has fallen upon us.

2
00:00:13,591 --> 00:00:17,820
The brunt of the war has
fallen upon the sailor men,

3
00:00:18,843 --> 00:00:20,843
"Dear Lord, let your
holy angel be with me,
````

Looks good to me

**Comment by Ding-adong** [comment]
Thxs for the quick fix.

Your last post is incorrect. You haven't read my post correctly.

It should be...

Before batch convert:

```
1
00:00:02,490 --> 00:00:05,670
the catastrophe of world
war has fallen upon us.

2
00:00:13,591 --> 00:00:17,820
The brunt of the war has
fallen upon the sailor men,

3
00:00:18,843 --> 00:00:20,843
"Dear Lord,
let your holy angel be with me,
```

After batch convert:

```
1
00:00:40,999 --> 00:00:45,295
the catastrophe of world war
has fallen upon us.

2
00:00:13,591 --> 00:00:17,820
The brunt of the war
has fallen upon the sailor men,

3
00:00:18,843 --> 00:00:20,843
"Dear Lord,
let your holy angel be with me,

```

**Comment by niksedk** [comment]
My last post was my results...

**Comment by Ding-adong** [comment]
Is there any settings that may affect how it works? Such as max lines, unbreak max lines. Mine is 34 and 35

**Comment by niksedk** [comment]
Possibly. Could you attach your Settings.xml?

**Comment by Ding-adong** [comment]
[Settings v3.5.11.xml.txt](https://github.com/SubtitleEdit/subtitleedit/files/9736396/Settings.v3.5.11.xml.txt)


[Settings v3.6.7.xml.txt](https://github.com/SubtitleEdit/subtitleedit/files/9736426/Settings.v3.6.7.xml.txt)

**Comment by Ding-adong** [comment]
Another issue, difference between 3.5.11 and 3.6.7.

3.5.11
More clones who have
lost their way.

3.6.7
More clones who
have lost their way.

The space gap between those lines are 5. The old version prioritise longer length on the 1st line and the latest prioritise longer length on the bottom line. Any reason why it changed?

**Comment by niksedk** [comment]
People have asked for bottom heavy. 
See  Options - Settings - Tools

**Comment by LeonCheung** [comment]
@Ding-adong In your third post here, for the two Original examples you claimed that are "no issues", IMHO they both have issues according to our criteria. In fact, the "whhaaaaatt!!!" ones look better.

Rule of thumb: As experienced captioners, TBH, we don't rely too much on the auto balance result. I don't mean that it's not a good tool. It does help, sometimes a lot, but we still need to do tweaks here and there in most cases because an appropriate break is much trickier than simply balancing the length or word count, even the most high-end AI tech nowadays (AFAIK) can't do this job really well, not mentioning that rules may differ among languages.

The recommended workflow here is: after completing the timecoding work for the whole project, use the auto-balance tool to do a rough breaking work for all lines first, then go through it and fix inappropriate breaks by using some nice shortcuts like:

![image](https://user-images.githubusercontent.com/494788/194739942-ded952b9-7cc2-472d-9a05-809691a9a067.png)

You can do the whole thing really quickly because you don't need to move the mouse cursor focus out of the list view, just hit the Up and Down arrow keys to go through the lines, then use those shortcuts when needed. My two cents. Hoping it helps.
