### ISSUE TITLE
Automatic Pitch Shift after update?

### ISSUE THREAD

**Issue by RyanAngelos** [SubtitleEdit/subtitleedit#6333]
Why is the pitch of the audio automatically tuned back down when increasing playback speed? This never happened before and i can not find a setting/toggle for it anywhere. Also doesn't appear to be in the change logs. I get that the "chipmunk" audio is annoying for some, but when working at 270% speed, this automatic pitch shifting seems to mess up the audio pretty badly. Sounds to me almost as if audio data is being cut out by the algorithm and some short words are even going missing.

Please advise me on this, thanks.

**Comment by darnn** [comment]
What was the last time this wasn't happening? I am merely a user, but this has been the way increased playback speed has worked for me since the start. So I wonder what was happening in the last version you were using that this wasn't the case. Also, could it be you're using something other than mpv for video playback (or were using it then)? I think only mpv and VLC even support increasing the playback speed properly, but they both sound pretty much the same to me, no chipmunk audio.

**Comment by niksedk** [comment]
It's not something done by SE... is done by VLC/mpv default.

I think is possible to turn off in mpv - see https://github.com/mpv-player/mpv/blob/master/DOCS/man/options.rst
You can probably set `MpvExtraOptions` to  `audio-pitch-correction=no` in Settings.xml ?
