### ISSUE TITLE
[Feature Request] Support Automatic Translation Using Whisper from Other Languages to English

### ISSUE THREAD

**Issue by MbuguaDavid** [SubtitleEdit/subtitleedit#6346]
Finally, I got Audio to Text (Whisper) to work. :) 
I noted Open AI's Whisper has the option to translate text or subtitles in other languages to English.

It would be awesome to have it available to use for translation purposes. :) 

Hopefully in the future. 
Thanks!

**Comment by niksedk** [comment]
Hi David,

Thanks for the idea :)

Implemented in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.8/SubtitleEditBeta.zip

**Comment by o-data** [comment]
Does anyone know how to use this feature? I only see Google as the option

**Comment by darnn** [comment]
Open a video file without a subtitle file (because a new one will be created, so the previous one will be closed anyway). Go to Video->Audio-to-text (Whisper). there you can check "Translate to English".
Having said that, I would avoid this. Just get a transcript using Whisper, and then correct any errors you find in it. These would naturally affect the translation, and if you check Translate into English you'll only have the translated text, not the original, and you won't be able to adjust it.
Once you have the corrected transcript in your original language, translate it to English using ChatGPT. Just type "Translate into English:" followed by your text, in chunks of roughly 1,120 characters. If you input much more than that, the ending will get cut off. Translating into English, this does better than any free online machine translation tool at the moment, and they're both OpenAI anyway, so there's probably some things in common under the hood.

**Comment by o-data** [comment]
@darnn Thank you for that. Just notice the "Translate" option in Whisper, I was using Vosk as the timing is better

Honestly I'm surprise that we manage to get AudioAI (Speech to Text) before TranslationAI in SubtitleEdit. A huge surprise when I saw this after updating SubtitleEdit, making mass creation of subtitle very conveniently now.
