### ISSUE TITLE
Black and white video

### ISSUE THREAD

**Issue by Juststorm** [SubtitleEdit/subtitleedit#6375]
![Captura de tela 2022-11-01 004211](https://user-images.githubusercontent.com/58124914/199153837-33f7167d-7e26-49a7-a61d-fbf20f38acb8.png)

Why is the video preview black and white? Using the latest version of Subtitle Edit and VLC Media Player.

How can I fix that?

**Comment by niksedk** [comment]
Try mpv - goto Options - Settings - Video player, and download "mpv"

Does that work better?

**Comment by Juststorm** [comment]
It worked!

Thanks.

**Comment by tharsim** [comment]
Same thing happened to me, which I quickly resolved using MPV. I've recently updated my GPU's driver, that's why. Is there a way to have both the template and the translation subtitles in the video? The only reason why I used DirectShow was because of that, it's easier to review having them both on screen
