### ISSUE TITLE
Import/Export settings

### ISSUE THREAD

**Issue by shanedk** [SubtitleEdit/subtitleedit#6424]
It would be really handy to have an import/export function for settings when reinstalling, installing Subtitle Edit or another computer, or recovering after a Windows crash (which has reset my settings twice now).

It's a long time to go and set everything back again, or go through the fine-tuning one does over weeks of use. Being able to export the settings to a file, and import them back when needed, would save a lot of time and headache.

**Comment by LeonCheung** [comment]
In case you don't know but you can try to back up the **Settings.xml** file in SE's directory, which contains almost all settings.

**Comment by uckthis** [comment]
Copy the Settings file from old folder to new folder, and it'll keep the settings.
Generally speaking, just copy the new SE. exe in the old folder, and it works most of the time. If you get an error, copy the new libse.dll from the new folder to the old one, and it's fixed

Note: I'm assuming you're using portable version.

**Comment by shanedk** [comment]
No, this is the installed version, and Windows trashes the file. The settings file and the file I was working on get filled with ASCII nulls.

**Comment by darnn** [comment]
I don't think that's intentional. Like, that happens to me sometimes when the power cuts out (presumably while the file is being modified or something), but it's not supposed to happen, and certainly isn't initiated by SE, as far as I know. And I agree backing it up manually kinda sucks, I wish I could just set a folder where a backup was saved automatically and then point it to my Dropbox or whatever, but on the plus side, once you have it configured the way you want once, you're set.

Just to make sure, though, under what circumstances are you saying that the setting file gets filled with ASCII nulls?

**Comment by niksedk** [comment]
Yes, as @darnn said, ascii nulls often occurs during crashes.

SE could perhaps rename the old Settings.xml to e.g. Settings.old before saving - would that help?
Does anyone know how other programs handle this?

Note that some windows have a context menu where you can export some settings/profiles.

Starting from blank once every few years is actually a good idea, as some default values may have improved...

**Comment by Ding-adong** [comment]
What i do is do all the settings then copy - paste settings.xml. If the original get screwed then delete settings.xml and copy - paste backup then rename. Happens once or twice per year so not a big deal.

**Comment by shanedk** [comment]
Having a settings.old file would certainly help. It'd still be nice to have a way of exporting and importing just so I wouldn't have to go find the file's location each time. It sounds like the import/export feature would really just be copying the settings file.
