### ISSUE TITLE
Regex Multiple Replace

### ISSUE THREAD

**Issue by francissjr** [SubtitleEdit/subtitleedit#6459]
Hello guys,

I am trying to replace an expression with regex that returns the searched term with the first letter of the word capitalized. 

I'm trying to do the substitution with `\U$1`  , but it's not working. Any suggestions?

This software doesn't support \U  or \L ?  Thanks for your attention

**Comment by pyrr** [comment]
[.NET regex doesn't support \U or \L.](https://social.msdn.microsoft.com/Forums/en-US/5ae2778b-2e1a-4e3b-8471-3fe97e268f72/does-u-convert-to-uppercase-work-in-net-regex?forum=regexp)

What are you trying to capitalize? If it's anything at the beginning of a line / after a period etc. then it should be pretty easy to write a regex. If it's a list of phrases that you want capitalized then that's also doable.

**Comment by francissjr** [comment]
I am trying to capitalize the second word of a locution the way the first word is capitalized, and then delete the first word. For example:

Lazy dog -> Dog
smart cat -> cat

**Comment by pyrr** [comment]
Ah well I realize now that it's impossible with NET regex.

I wrote a tiny script for you to run on the files in order to accomplish this [here](https://github.com/pyrr/public/blob/main/foo.py). I've only tested this on .srt files but it should work on any file that contains the subs in plaintext. Let me know if this helps.
