### ISSUE TITLE
Subtitle Edit 3.6.10 - Whisper Very Slow

### ISSUE THREAD

**Issue by JBreezy222** [SubtitleEdit/subtitleedit#6553]
After months of trying to get SE to get whisper to work. I finally got it to work with the 3.6.10 Beta model. I asked a question the other day and pretty much got ignored in the thread. I am asking why it only works in the beta version and not in the regular 3.6.10 version? I have done every single step I could find on here to get Whisper to work. Everything I think was suppose to go into path is in path. I did a 20 minute and it took 3 hours to subtitle. I could only use the CPP verion and not the original PHP. The original would show "No Text Found" like it always has for the few months I tried to get SE Whisper to work. I have a Intel GPU and not the NVIDIA that uses CUDA, But if it wasn't for this beta version of SE I would not be able to use Whisper through SE. Is there any solution to get Whisper to use my Intel GPU? Other than this I have no idea why I can not get SE whisper to work for me other then the CPP in the beta version.

**Comment by akashmamun610** [comment]
excellent writing JBreezy222.. same problem for me...whisper is very very slow..  is it possible to make whisper quicker in intel GPU.. I do not have graphics card ..

**Comment by niksedk** [comment]
>I am asking why it only works in the beta version and not in the regular 3.6.10 version? 

SE 3.6.10 has some bugs regarding Whisper. I hope these bugs has been fixed in latest SE beta...

You can read more about performance here: https://github.com/ggerganov/whisper.cpp/discussions/126

Installation instructions for the original OpenAI whisper is here: https://github.com/openai/whisper

Note that Whisper is still very new and has several issues like inaccurate timestamps, looping of text, and even freezes. Hopefully some of the issues will be fixed in the future - which might not be good new for professional translators.

Both the original and the cpp version of Whisper has srt cmd line tool - you can test that too.

**Comment by JBreezy222** [comment]
I gave up after going on 8hours :D Thank you for responding back though. I always manage to figure something out. ;) Keep up the awesome work here at Github.
