### ISSUE TITLE
Subtitle does not time sync correctly when running with GPU method. 

### ISSUE THREAD

**Issue by xhien9** [SubtitleEdit/subtitleedit#6700]
Subtitle does not time sync correctly with video when running "Generate text from audio via Whisper speech recognition" with GPU method. So that I have to use CPP method although it slower than GPU. Hope to fix this issue.

**Comment by Purfview** [comment]
Whisper timing issues are not Subtitle Edit's issues at all.

Try "Whisper OpenAI", it supports GPU and CPU, for me "Whisper OpenAI" runs 3x faster than "Whisper cpp".
If you don't want to bother with Python then you can get executable from there -> [whisper-standalone-win](https://github.com/Purfview/whisper-standalone-win)

Currently, @niksedk didn't added option to run "Whisper OpenAI" on GPU, so you would need to enable GPU yourself with this parameter -> `--device cuda`

**Comment by rsmith02ct** [comment]
Could this standalone Whisper be integrated into Subtitle Edit (is it better than Cost-me?)

**Comment by Purfview** [comment]
> Could this standalone Whisper be integrated into Subtitle Edit?

"OpenAI" is supported already,, download latest portable beta.

> is it better than Cost-me?

People say that "OpenAI" doesn't have "infinite loop" bug like "cpp" and "Const-me".
Dunno if it's slower or faster than "Const-me", I didn't tested it on GPU.

**Comment by rsmith02ct** [comment]
Is there a way to make OpenAI use the GPU? It seems CPU only like CPP in my test.

**Comment by Purfview** [comment]
> Is there a way to make OpenAI use the GPU? It seems CPU only like CPP in my test.

Did you read this post https://github.com/SubtitleEdit/subtitleedit/issues/6700#issuecomment-1445331996

This is command to use GPU:
`whisper.exe --device cuda --language en --model "small.en" "D:\test.wav"`

**Comment by rsmith02ct** [comment]
Thanks for that, I didn't really understand the comment above.

I'm not getting success. I just downloaded and decompressed it to a folder within SubtitleEdit. Through Subtitle Edit OpenAI works in English, though in Japanese with the base or large model I get a blank srt file. Not sure why.

I tried just doing a command prompt and it gives an error. Does this have to be installed in a particular folder? There is nothing at D:\whisper\

c:\Program Files\Subtitle Edit\Whisper-OpenAI>whisper.exe --device cuda --language ja --model "base" "D:\My Documents\Dropbox\Videos\10 MPantry final new titles 2.mp4"

Traceback (most recent call last):
  File "D:\whisper\__main__.py", line 4, in <module>
  File "whisper\transcribe.py", line 314, in cli
  File "whisper\transcribe.py", line 85, in transcribe
  File "whisper\audio.py", line 111, in log_mel_spectrogram
  File "whisper\audio.py", line 42, in load_audio
  File "ffmpeg\_run.py", line 313, in run
  File "ffmpeg\_run.py", line 284, in run_async
  File "subprocess.py", line 858, in __init__
  File "subprocess.py", line 1311, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
[18756] Failed to execute script '__main__' due to unhandled exception!

**Comment by Purfview** [comment]
Looks like you don't have FFmpeg in PATH, copy it to whisper's folder.

Here is English wav for tests: https://we.tl/t-2S5cTx9bBa

**Comment by rsmith02ct** [comment]
Thanks so much.

I took ffmpeg.exe and put it in the same folder as whisper.exe. That
enabled the translation to start!

[00:00.000 --> 00:01.440] 宇宙の Austria
[00:04.340 --> 00:07.700] みたこともないように食べ物だとはもうので
[00:18.980 --> 00:22.940] 中央党までお気マスしつもりにとって
[00:22.940 --> 00:27.820] まず大学卒業してから2年間くらい留学でアメリカに行って
[00:27.820 --> 00:29.380] 今まで本当に感じたことないの
[00:29.380 --> 00:30.620] マッシュマンの良さとか
[00:30.620 --> 00:32.620] 見上げの良さに日本の良さがすごい感じで
[00:32.620 --> 00:34.180] 収索をして
[00:34.180 --> 00:37.780] 収索している最中に審査が起こって
[00:37.780 --> 00:39.860] その時に
[00:39.860 --> 00:41.500] このまま
[00:41.500 --> 00:47.660] ずっと会社で働いて
[00:47.660 --> 00:48.980] 行くよりも
[00:48.980 --> 00:52.900] 地元に帰ってお店をやることによって
[00:52.900 --> 00:55.260] 新しいお客さんに来ていただいているとか
[00:55.260 --> 01:00.300] でもマッシュマン全体が活性化したい
[01:00.300 --> 01:02.660] 見えんけんっていうやっぱり込めどころ
[01:02.660 --> 01:04.620] そしてあと見えんけん
[01:04.620 --> 01:06.300] まぁマッシュマンといえば
[01:06.300 --> 01:07.980] やっぱり書きいう夢だったんで
[01:07.980 --> 01:12.860] この2つを使って何か作る
[01:12.860 --> 01:21.860] これは2年間のひとめぼれの込め子を100%になります
[01:21.860 --> 01:27.860] 込め子をダンゴ状にして
[01:27.860 --> 01:34.860] ダンゴ状にした込め子の上に
[01:34.860 --> 01:37.860] 丸ごと一つの書きを乗せて
[01:37.860 --> 01:41.860] フレスをして水分を飛ばしても
[01:41.860 --> 01:46.860] パリパリのお店
[01:46.860 --> 01:51.860] パリパリのお店
[01:51.860 --> 01:56.860] パリパリのお店
[01:56.860 --> 02:01.860] パリパリのお店
[02:01.860 --> 02:06.860] パリパリのお店
[02:06.860 --> 02:11.860] パリパリのお店
[02:11.860 --> 02:14.860] そのまでも食べられるような
[02:14.860 --> 02:16.860] お土産としても
[02:16.860 --> 02:19.860] 行けるような商品を
[02:19.860 --> 02:21.860] マスクりたいな
[02:21.860 --> 02:24.860] お店
[02:24.860 --> 02:27.860] 込め子と書きをプレスして
[02:27.860 --> 02:29.860] お店便にするっていうのは
[02:29.860 --> 02:31.860] ほかにはないんじゃないかなと思うので
[02:31.860 --> 02:34.860] 一度食べていただいて
[02:34.860 --> 02:44.860] おいしさを味わっていただけたらなと思います

Traceback (most recent call last):
  File "D:\whisper\__main__.py", line 4, in <module>
  File "whisper\transcribe.py", line 315, in cli
  File "whisper\utils.py", line 158, in write_all
  File "whisper\utils.py", line 73, in __call__
PermissionError: [Errno 13] Permission denied: '.\\10 MPantry final new
titles 2.mp4.txt'
[5708] Failed to execute script '__main__' due to unhandled exception!

It seems to be calling a path that points to nothing and while it processes
the audio now it doesn't produce a SRT file.
It also doesn't seem to use the GPU at all (laptop with integrated HD630
and GTX1050).

**Comment by Purfview** [comment]
Did you run command prompt as Administrator?
Don't keep standalone programs in system folder or system disk. 
And maybe problem is that you have 2 GPU's, try `--device cuda:1`.

**Comment by rsmith02ct** [comment]
Thanks for the tech support. Running cmd as an admin it no longer gives an error. I tried cuda:1 though I get an error

> RuntimeError: Attempting to deserialize object on CUDA device 1 but torch.cuda.device_count() is 1. Please use torch.load with map_location to map your storages to an existing device.
> [11224] Failed to execute script '__main__' due to unhandled exception!
> 

Cuda:2 also fails. Cuda:0 works but it's CPU only based on task manager/performance.

I then moved Whisper OpenAi to its own folder on the c: drive.  For Japanese it worked though didn't output a file- I have to cut and paste from command prompt to notepad, There are a number of repeated lines (using base model here).

I did an English video and it also worked (though no file is exported) and it had no repeated lines.

**Comment by Purfview** [comment]
Subs are outputted to whisper's folder.
Do you have this installed [CUDA Toolkit 11.6](https://developer.nvidia.com/cuda-11-6-0-download-archive?target_os=Windows&target_arch=x86_64#)
What versions is your GPU driver?

**Comment by rsmith02ct** [comment]
Thanks for letting me know the save is in the Whisper folder rather than
the video folder.

I moved over to my desktop which has a RTX 2080 Super installed and tried
the same video file with the same settings. This time it worked with the
GPU and was extremely fast without repeated lines! Overall quality of the
base model wasn't so good so I downloaded the large model on this computer.

However large wouldn't run (8GB Vram). It ran on Const-Me and CPP before.

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 26.00
> MiB (GPU 0; 8.00 GiB total capacity; 6.93 GiB already allocated; 0 bytes
> free; 7.27 GiB reserved in total by PyTorch) If reserved memory is >>
> allocated memory try setting max_split_size_mb to avoid fragmentation.  See
> documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> [19836] Failed to execute script '__main__' due to unhandled exception!
>

Medium worked with GPU with no repeated lines.

Both computers are on Studio driver 528.49. I'll turn on the laptop again
and check regarding CUDA Toolkit.

I noticed on both machines Subtitle Edit doesn't work together with this
version of OpenAI. if I point Subtitle Edit to Whisper Open AI it breaks
CPP and Const-me.
It prompts me to download const-me even though I have it and then gives
this error.
[image: image.png]
I have to reset the settings of SubtitleEdit to be able to use them again.

**Comment by Purfview** [comment]
Works for me, maybe you copied standalone SE to your system's folders?

And check this video - https://www.youtube.com/watch?v=X9wXMHSvssQ

**Comment by Purfview** [comment]
Btw, you need ~10GB VRAM fot large model.

**Comment by rsmith02ct** [comment]
Shouldn't SubtitleEdit be in program files? The installer puts it there and
I paste in beta builds over it. Is that the problem?

I understand regarding VRAM and the large model- odd that it works in
Const-me.

**Comment by Purfview** [comment]
Beta builds are standalone, standalone doesn't go to system's folders.

Not strange, they are different implementations.

**Comment by rsmith02ct** [comment]
I retested on my laptop GTX1050 after assigning Open AI Whisper to the
NVIDIA GPU in Windows Graphics Settings (which took over from NVIDIA
Control panel.)I also assigned PhysX to NVIDIA as the video showed. I
didn't install the toolkit as it looks like its for devs and wasn't
required on my 2080. Still no GPU activity with the CUDA switch set. Maybe
a limitation with 10XX or mobile versions?

**Comment by Purfview** [comment]
If you don't have CUDA v11.6 installed then it won't work.

**Comment by rsmith02ct** [comment]
I'm trying to help troubleshoot the issue. NVIDIA Studio Driver Version
528.49 WHQL  comes with CUDA 12 according to the release notes. Users don't
need a SDK to use CUDA as the libraries are part of the driver.

**Comment by Purfview** [comment]
Just install runtimes from it.
