### ISSUE TITLE
Accessing files over a local network file share = slow / mini freezes

### ISSUE THREAD

**Issue by ghost** [SubtitleEdit/subtitleedit#6772]
Attempting to parse files through the network only uses around 100-200Mb which seems a little slow. When downloading files from my NAS I can easily do 1000Mb and while I know it's not the same type of access, SE still seems slower than it should be to parse through. SE also has these little mini freezes while parsing through the mkv. The share is mounted as a network location with a drive letter via SMB3.

**Comment by lukastribus** [comment]
Yes, this is a real problem.

I have a 2,69 GB mkv file here on the NAS:

It takes 65 seconds for SE to parse it and it doesn't use more than 20% of the network bandwidth (200mbit/s). During this time 47000 SMB read request are issued and 1717 MB are transferred from the NAS to the PC (so *not* the entire file).

It takes 25 seconds to copy the file from the NAS to the local SSD with windows explorer. During this transfer 2760 SMB read requests are issued and 3001 MB are transferred from the NAS to the PC.

SE takes about 2 seconds to parse the file from the local SSD.


So it looks like instead of streaming the file to SE, SE jumps around to specific offsets trying to read just pieces of the file leading to to subpar performance when spinning hard disks and/or remote storage are involved.

Yes, this behavior does conserve bandwidth but I don't think this expected.


ffmpeg on the other hand does a fine job of extracting subtitles from mkv files on remote drives with full bandwidth: it took only 27 seconds for ffmpeg to extract the subtitles from the very same remote file, fully saturating the Gigabit network. So there is really no fundamental problem with extracting subtitles, rather the implementation chosen in SE reads specific offset instead of just streaming the file in a straightforward way.

**Comment by lukastribus** [comment]
Hello,

I tested again with a 11.8GB MKV file:

SE4.0.16 took 2 minutes 23 seconds, problems:
- SE UI freezes during the entire process
- no sequential read, so very slow (1/5th of the possible speed)
- the only indication about progress is in the Windows Task Bar (small progress indicator)

In SE5 this has not improved:

SE5RC4 took 3 minutes and 4 seconds, problems got worse:
- same SE UI freezes during the entire process
- same problem with no sequential read, slower than 4.0.16 even
- progress bar in Windows Task Bar is gone now, so there is not indication about the progress at all


So in summary, there are different issues:
- the Matroska parsing blocks any UI updates, which therefore totally freezes
- there is no progress bar in SE
- the file is not read sequentially which makes this about 5 - 6 times slower than necessary on rotating disk drives (at least on NAS)


And additionally the SE5RC4 regressions are:
- at least 30% slower than SE4
- the only progress indication (in the windows task bar) is now gone as well


When removing ffmpeg from the install, SE5 performance goes back to approx. the performance of SE4 (it went from over 3 minutes to 2 minutes and 40 seconds).

If I understand correctly, ffmpeg is used for Waveform generation, which can be disabled only be deleting ffmpeg.


If at least one of those behaviors is not expected, I'm happy to provide additional details, test things, etc.

If all of this is expected, please explicitly say so.

Thanks

**Comment by niksedk** [comment]
Both issues here should be much better now — PR #11712.

**Reading speed:** Using a 4 KB read buffer cuts the disk I/O ~4x (~700 MB → ~175 MB) and cold-open time dropped ~5x on my system.

**Progress:** opening a large MKV now extracts on a background thread (so the UI no longer freezes) and shows a "Please wait…" window with a percentage progress bar for files ≥ 25 MB.

SE5 was already faster on my system, but that might be due to SSD disk.

**Comment by lukastribus** [comment]
Great work, thank you! Will test with RC5 once available.

**Comment by lukastribus** [comment]
I have some more feedback from SE5 release:

The code path regarding the background thread and progress windows appears to be invoked only when the MKV file contains exactly one subtitle.

When multiple subtitles are present, and therefore the parsing happens right after drawing the "Pick Matroska track" window, the UI remains completely blocked and the progress window never shows.

As to the performance on spinning disk (HDD) on a NAS connected via 1Gbps LAN, SE5 release is slower than RC4, so for the same 11.8GB MKV file I see:

SE4.0.16 took 2 minutes 23 seconds
SE5RC4 took 3 minutes and 4 seconds
SE5 release took 3 minutes and 52 seconds

I have no doubt that the new code is faster on SSD, unfortunately it's gotten worse for HDDs that benefit from sequential instead of short reads. Perhaps it would be beneficial if the read buffer length would be configurable?

**Comment by lukastribus** [comment]
I made some test with a USB3 connected HDD drive.

The performance (time measured) between SE4, SE5RC4 and SE5 release is nearly identical in this case (of course one release reads more than the other, but all of the releases are fast and within seconds of each other).

Likely with a local disk some read ahead optimization come into play that are not enabled in the SMB mounted server drive. I will play with server settings (smb vfs readahead, btrfs read ahead, making sure to purge the page cache) and repeat the benchmarks.
