### ISSUE TITLE
[Bug] Can't undo text change when opening file

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/subtitleedit#6784]
If you open a file and change a text, you can't use `undo`, the `Edit history` is empty.
Just open any file and edit a text and try to undo.

I tried to track it down and it led to this:
```
                    int hidx = _subtitle.HistoryItems.Count - 1;
                    if (hidx >= 0 && hidx < _subtitle.HistoryItems.Count)
                    {
                        var historyParagraph = _subtitle.HistoryItems[hidx].Subtitle.GetParagraphOrDefault(index);
                        if (historyParagraph != null)
                        {
                            MakeHistoryForUndo(_languageGeneral.Text + ": " + _listViewTextUndoLast.TrimEnd() + " -> " + newText, false);
                            historyParagraph.Text = _listViewTextUndoLast;
                        }
                    }
```

`_subtitle.HistoryItems.Count` is 0 when you edit a text without making any other edit first, so `hidx` is -1 and a history item is not added, but I did not know how to fix it.

**Comment by niksedk** [comment]
Nice catch - I just think this commit was wrong: https://github.com/SubtitleEdit/subtitleedit/commit/1956ad296d9a7d07f8684d7d3c36920e16f96397

**Comment by darnn** [comment]
This might not be related to this, since it's an old issue, and I'm not exactly sure how to reproduce it, so I haven't opened a separate issue about it yet, but while we're on the subject: occasionally, after working on files for a while in translation mode, especially merging lines, inserting new lines and so on, and using undo, it will revert the translation (and sometimes the original as well) to some state before most of the line changes were made.

**Comment by Jaxzerax** [comment]
Hi. I use this program for work everyday. What should I do to fix this problem? I have no knowledge of programming. Should I just wait for the next update?

Thank you in advance.
