### ISSUE TITLE
[Small Issue] Text box text selection - selects whole word, instead of character-by-character

### ISSUE THREAD

**Issue by rRobis** [SubtitleEdit/subtitleedit#6822]
Currently, when trying to select text in a subtitle text box, the mouse selection automatically jumps to select the whole word instead of allowing character-by-character selection (sometimes it selects characters, if moving the mouse slowly).
Sometimes this is annoying, when I have to select small parts like in :

"SUBTITLETEXT?{\fad(0,1200)}"  I need to select {\fad(0,1200)}, but it also selects "?" with it. This is not limited to special characters only, but all text.

Maybe this can be fixed somehow to work just like selection here in browser, or at least make it in an optional thing.

**Comment by darnn** [comment]
Go to Settings->Appearance and turn off "Use syntax coloring".

**Comment by rRobis** [comment]
That works, but unfortunately, I need to see syntax coloring, it helps me with ASS format.

**Comment by GrampaWildWilly** [comment]
You could always ditch the mouse entirely for marking.  Just use the arrow keys to position the mouse cursor at the position where you want to start marking.  Then press & hold down either shift key.  Then use the arrow keys to highlight whatever it is you want.  If you want to copy the highlighted text elsewhere, Ctrl+Insert puts it in the system clipboard but leaves it unchanged in its original place.  If you want to also remove it from its original place, use Shift+Delete instead, which still puts it in the system clipboard.  When you navigate to the new place where you want to put the text, once again, use the arrow keys to position the mouse cursor at the new location of the text.  Then Shift+Insert will copy the text from the system clipboard to the new location.  Within a very short time practicing this you will find this so convenient, you will wonder why you ever did it with the mouse.  I expect using the keyboard instead of the mouse in this fashion will allow your text coloring to remain in effect.  Do try it & report back.

**Comment by rRobis** [comment]
I'm occasionally using shift and arrows and shortcuts, it does the job, but it requires jumping from mouse to keyboard. If i have to do it in fast-paced workflow, it slows me down a lot.

I have a setup that i use macro keypad with specific macros (splitting, coloring, etc), in the left hand and mouse in the right hand. 

I usually put my keyboard a little bit out of my reach, to make it more comfortable.

I just want to be able to normally select text like when the syntax coloring is disabled.

**Comment by darnn** [comment]
@niksedk I'm not sure what happened, but in the latest beta, selecting text normally doesn't work with syntax coloring disabled as well.

**Comment by rRobis** [comment]
@niksedk Will you be able to do this? I would be very thankful, because it would speed up my workflow a lot.
