### ISSUE TITLE
Translator Mode: The original subtitle cannot be recovered in a file

### ISSUE THREAD

**Issue by SpasV** [SubtitleEdit/subtitleedit#6833]
When working in translator mode, SE opens both translated subtitle and the original subtitle with the File/Reopen command which displays a list of files. Among them, it shows translated.srt + original.srt as a single item file. SE works ok.
But, I cannot get the original.srt file as I see it in the translator mode Window. This has happened, probably, after my using the File/Save original subtitle command.
The original subtitle file looks like a file generated by the File/Restore auto-backup command with twice more lines including many empty ones.

Spas Velev
[Enemy at the Gates 2001 2160p.copy.txt](https://github.com/SubtitleEdit/subtitleedit/files/11239678/Enemy.at.the.Gates.2001.2160p.copy.txt)

**Comment by darnn** [comment]
You probably had a desync and didn't realize it. That is, the number of subtitles in the original file and in the translated file changed, but in the Subtitle Edit window, they still seemed the same. However, when you closed and opened them again, they opened in their desynchronized form. The main thing I know that can cause a desync right now is using copy+paste on entire subtitles (see here https://github.com/SubtitleEdit/subtitleedit/issues/5597).
There is an indicator of whether or not this has happened. This is a screenshot of the window before it happens:
![se-split-01](https://user-images.githubusercontent.com/19672444/232280905-016128b0-f83d-4dc6-9ed0-9896c7624a0b.png)
And this is a screenshot after:
![se-split-02](https://user-images.githubusercontent.com/19672444/232280914-11312d05-8c87-4ef5-97aa-05722e6f18e7.png)

Note that "OK" on the left has changed into "count does not match".
At this point I'd go back to the earliest backups in AutoBackup that were still synched, and apply any changes I made since then myself before opening the files in translator mode again.

Oh, also, this sometimes happens when you use the undo function. SE will, for whatever reason, instead of undoing the latest change, will undo many, many of them at once, including any merging or splitting of lines, but only in the translation, not in the source, which will also create a desync. This is harder to pin down, though, and only happens every once in a while, so I couldn't tell you how to avoid it. Just keep an eye on that indicator after you use undo.

**Comment by SpasV** [comment]
Thanks, sure I'll avoid these situations.
But, the question remains: why SE doesn't "Save original subtitle" the same way as they are shown in the Translator Mode Window? It has them properly synced.

**Comment by niksedk** [comment]
@SpasV: Can you describe steps for me to re-create this? (screenshots are nice)

**Comment by SpasV** [comment]
Sorry, I'm late.
I'll post examples tomorrow. For now, I'll briefly describe the main.
**Translator Mode**.
I've seen two cases when desync happened. The common reason is saving the Original subtitles.
1. I don't know the reason for the event to happen. But, after some **text** corrections have been made in the Translated subtitles SE prompts for saving the original subtitles.
2. The second is obvious. After **timing** corrections have been made the Original subtitles need to be saved also.

After saving the Original subtitles every file copy opened is **desynced**.
The Original subtitles **are** synced when both Translated and Original are **Reopen**ed as T.srt+O.srt.

**Comment by SpasV** [comment]
Sorry, I couldn't get desync example having tried two timing corrections using the "**Split line at the cursor position**" command.
I'll try later on again.

**Comment by darnn** [comment]
This seems to have been fixed, at least from the few times I've tried, at some point in the past few months (I believe). If you're using the latest beta, split at cursor position shouldn't cause a desync.
