### ISSUE TITLE
can you add auto-translate by open ai

### ISSUE THREAD

**Issue by abasameer** [SubtitleEdit/subtitleedit#6912]
add open ai api for auto-translate

**Comment by rsmith02ct** [comment]
That would be great- would like to avoid Google Translate and attempting to cut and paste lines into say DeepL just doesn't work as it needs to work on whole sentences, not lines.

**Comment by niksedk** [comment]
SE has a DeepL plugin

**Comment by darnn** [comment]
There's no one-step solution, but what I do with any machine translation tool is export the text, and under export options select "merge all lines". This way you get a single block of text with no line breaks, but with complete sentences. I run this through the machine translation service, whatever it may be (or feed it bit by bit into ChatGPT, for instance), and then get a single block of translated text back. I then import this text and use "auto split text" in order to get back something roughly subtitle-length, and from there adjust by hand in translator mode. It's laborious, but you get the hang of it quickly (especially if you use the "move last word to next subtitle" and "fetch first word from next subtitle" shortcuts), and the translation comes out more legible than when you just use the text of individual subtitles.

**Comment by darnn** [comment]
That's what I'm saying, though, you don't have to break up the lines manually. Use File->Export->Plain text:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19672444/258de5ac-052f-4aad-9b32-9779a1aba025)
And then take that text and import it through File->Import->Plain text, breaking it up into sentences: 
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19672444/c95bbefd-46b9-441a-ac65-13e2a4e283e7)

Whisper in general does allow for auto translation into English, but you're honestly better off doing that through ChatGPT, if only because Whisper will only translate its own output, you can't correct the text before the translation step. On Whisper's GitHub page one of the developers suggested using text-to-speech on your text, saving the audio and then having Whisper recognize it so that it can be translated (which does work), but that really does feel excessive.
