### ISSUE TITLE
Unable to open a media file if it is in use by another program (new behavior in 3.6.13?)

### ISSUE THREAD

**Issue by mhudec** [SubtitleEdit/subtitleedit#6986]
Hello,

If the media file (e.g. mkv file) is already opened by another program (e.g. BS.Player), attempt to open it in SubtitleEdit results in an error message "Unable to open file as it is in use by another program: <path_to_the_media_file>" shown in a popup window. This seems to be new behavior since SubtitleEdit 3.6.13, it is not present in previous version (e.g. 3.6.12).

I often have both media player as well as SubtitleEdit opened, I watch the movie/episode and fix subtitles along the way (media player is just reading, not writing to file as far as I know, so I do not expect having it some exclusive lock, preventing SubtitleEdit to read from the same file, but that is just my assumption).

Steps to reproduce:
1.) open media file in a media player
2.) attempt to open same media file in SubtitleEdit 3.6.13

Information from error_log.txt:
```
-----------------------------------------------------------------------------
Date: 06/04/2023 00:35:20
SE: 3.6.13.0 - Microsoft Windows NT 10.0.19045.0 - 64-bit

System.IO.IOException
Message: The process cannot access the file '<path_to_the_media_file>' because it is being used by another process.
StackTrace:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Nikse.SubtitleEdit.Core.Common.FileUtil.IsFileLocked(String fileName)
```

Regards,
 Martin

**Comment by GrampaWildWilly** [comment]
Before I knew about SE (maybe a couple of years ago) I was editing subtitles for operas using a text editor.  I would play the opera in VLC, notice an error in the subtitles, change them in the text editor, then try to save the subtitle file.  I got the same error you are complaining about: can't save because other app has it locked.  I had to remove the file from the VLC playlist, save the subtitles, get the video into VLC again, skip forward to where I had been, then decide whether I liked my edit of the subtitles before proceeding.  Once I got SE I was surprised to discover that it would write an update to a subtitle file while VLC was playing it.  Of course, my corrections weren't picked up by VLC.  I had to do a Next function in VLC, which starts the playback from the beginning (since the opera was the only entry in VLC's playlist).  Then I had to skip forward to where I had been & observe whether I liked my edit.  Then I could continue from there.  At least I didn't have to completely remove the video from VLC.  Why was I not just doing this in SE?  Because the video & audio are in separate files, which is the way I want it, and SE can't deal with that.  If SE would support something like VLC's synchronous playback feature, it would be wonderful.  But it doesn't, so I have to use 2 players to edit these subtitles.

However, I always thought SE writing to the subtitle file while VLC was already playing it was a violation of operating system protocols.  If SE now honors the locked state of a file, then I say it's an improvement.  I vote against this proposed "fix."  Maybe VLC shouldn't lock something it's not updating, but it does.  So SE should honor that & I'm happy to hear that it now does.  I say the problem is not in SE but in the video player.

**Comment by niksedk** [comment]
Just to be sure... could you test latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip ?

**Comment by GrampaWildWilly** [comment]
First I got SE 3.6.13 beta 35.  I tried 2 tests.  First, I opened an opera with vtt subtitles in VLC & started it playing.  Then I opened the same vtt in SE, changed something, saved it, & it succeeded.  Then I verified that the change I had made was reflected in VLC by doing Next & the change indeed was there.  It seems VLC loads up a copy of the vtt when it starts so any changes you make don't affect the running playback.  You have to refresh what you're playing in order to get VLC to reload the vtt.  So I am not replicating mhudec's problem.  But then, I don't have the same video player he does.

Then I tried the same thing between VLC & Notepad++.  In the past, Notepad++ definitely encountered the locked file deal.  But this time, it did not, same as SE.  This tells me VLC has changed.  It no longer locks the vtt while it is simply playing the video.  It definitely used to but now it does not.

I think this points to mhudec's video player or players locking the subtitle files, & SE is indeed honoring that lock.  Which is all good.  Nik, did you add a check to SE for the file being locked?  Was that in this beta 35 or something older?  I'm pretty sure that many releases of SE ago, & a few releases of VLC ago, VLC was locking the vtt but SE was writing to it anyway.  I thought it was odd at the time but I just shrugged my shoulders & went on with things.  I just always kept it in mind that this was something SE would do.  But there's been so many changes to SE & even a few to VLC in the interim, so I suppose it's not surprising that behavior has changed.

**Comment by mhudec** [comment]
@niksedk -thank you for checking it, I have tried it with beta version (3.6.13 NEXT, beta 35), issue is not present, it opens the media file just fine alongside the media player.

@GrampaWildWilly - thank you for checking it too and I agree, honoring the file lock is a good thing, on the other hand according to the error_log.txt (and the error popup window) it complains about the media file (it is just in the very beginning of import process when it attempts to extract the subtitles embedded in the media file, if any is present there at all) and not the subtitle file (which is nonexistent at this stage yet).

Hm, I am now not sure that this is an issue anymore... I mean, I can simply close the media player, extract the subtitles and make necessary edits and save the subtitle file and then reopen the media player (so it gets the updated version of the subtitle file).

Additional information:

- I have reproduced the issue also by using VLC 3.0.18 and SubtitleEdit 3.6.13 (sorry, forgot to test another player tonight when I opened the issue), however Beta version is opening it just fine

- I usually use BS.Player version 2.78.1094 (2.78 Build 1094 from 12th December 2022) to play media files

- looking at the BS.Player process via Process Explorer (https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer), in the Handles view it says that for the media file (.mkv) the Access is 0x00120089 (READ_CONTROL|SYNCHRONIZE|FILE_GENERIC_READ) and Share Flags are RW- (meaning that other callers can open the same file for reading and writing). Doing the same for the SubtitleEdit (normal version, not the beta) process, it says that for the media file (.mkv), the Access is 0x00120089 (READ_CONTROL|SYNCHRONIZE|FILE_GENERIC_READ) and Share Flags are RWD (others can open for reading, writing and can also delete).
