### ISSUE TITLE
FEATURE REQUEST: Centering on the longest line when exporting image-based subs

### ISSUE THREAD

**Issue by aaaxx** [SubtitleEdit/subtitleedit#705]
Could you add an option to center only the longest line and left-align the shorter lines to the beginning of the longest one. In other words, the subs are left-aligned but the whole block is centered. It should also work automatically for right-to-left languages (in that case shorter lines are right-aligned).

For example:

```
——————————————————————————————————————————————
|                                            |
|                                            |
|                                            |
|                                            |
|                                            |
|                                            |
|          Don’t tell him anything.          |
|          Don’t trust him.                  |
|                                            |
——————————————————————————————————————————————

——————————————————————————————————————————————
|                                            |
|                                            |
|                                            |
|                                            |
|                                            |
|                                            |
|      أجل، في الحقيقة أنا أقوم بالعديد      |
|          .من قضايا شهادة البراءات تلك      |
|                                            |
——————————————————————————————————————————————
```

**Comment by rebawest** [comment]
This is called "justification." Instead of "Align", justification might be better to have.
Alignment is controlled with tags: AN1, AN2, AN8, etc., so maybe we don't need it in that dialogue window.
But justification could be useful. Something like this:

![image](https://cloud.githubusercontent.com/assets/6587015/7143788/b4480e2e-e2b7-11e4-8782-2276e990a710.png)

Each DropDownList in Fab Subtitler has 3 options: Left, Centered, Right.
This allows the user to export subtitles for the deaf (where you would usually use LEFT/LEFT/LEFT/LEFT), normal subtitles (CENTER/CENTER/CENTER/CENTER or LEFT), or subtitles in right-to-left-languages (RIGHT/RIGHT/RIGHT/RIGHT).

Kind regards...

**Comment by elmonta** [comment]
I did not do substitles

**Comment by niksedk** [comment]
Should be included in later versions of SE (left justify)
