### ISSUE TITLE
Problem with .tt subtitles

### ISSUE THREAD

**Issue by m0ck69** [SubtitleEdit/subtitleedit#7051]
I have two .tt subtitles. One works with SE, the other does not. Why is that?
There are here https://we.tl/t-nofkD8D52n

**Comment by niksedk** [comment]
Thx for the file :)
Should be fixed in above commit and fix included in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

"&" should be escaped in xml but sometimes it is not... SE had a half fix, but the regex `&(?!amp;)` should be better (which ChatGPT made for me)

**Comment by m0ck69** [comment]
thanks, it is fixed now.
