### ISSUE TITLE
[Suggestion]Translate Mode > Auto Repeat: make the current 200ms delay optional

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#706]
It seems to behave by design, because it also plays 200ms ahead of the start tme. However, I really think we can make this "larger play range" optional,  each time it will play a small piece of the next line, which brings a certain amount of distraction to translators.

![delay](https://cloud.githubusercontent.com/assets/494788/7105868/971168ee-e160-11e4-98c6-17675c3eca5c.jpg)

As shown in the image above, after auto repeat completed,  it now stops at the pink arrow. What I suggest is to make it stop right by the end of the line (where the orange arrow located). Or at least make it optional. Thanks a lot!

**Comment by pxj2099** [comment]
@niksedk any workaround to fix this please?

I have tested that this issue persists in latest version too. In my testing, the overshooting happens by 300msecs (not 200msecs).

The reason this bug is important is because we use Subtitle Edit to transcribe audio files. Sometimes a short word may be spoken at the start of next segment (duration less than 300msecs), which makes the transcriber type it out at the end of current segment.
