### ISSUE TITLE
can I import unformat text and convert it to format text with timings?

### ISSUE THREAD

**Issue by xkungxfu** [SubtitleEdit/subtitleedit#7067]
I have not a subtitle file. 
I only have a normal format text file and a voice file.
Can I paste or import the text and auto convert the text to subtitles with timings??

Thanks!

**Comment by darnn** [comment]
As far as I know, Subtitle Edit can't do this at the moment. The thing you want is called forced alignment, so I can only suggest you try to read up on it. There is a fork of Whisper that does this with its output, WhisperX, using something called wav2vec. You can look into that as well: 
https://github.com/m-bain/whisperX

However, to the extent that this is accurate, it will only give you the alignment with its own output, not with your text. If there are significant differences, and you'd want to go to the trouble, you could do this:
Import your text into SE as subtitles without timecodes using "import plain text". Then open the SRT file you got from WhisperX, use "make new empty translation from current subtitle", and column paste the text from the subtitles without timecodes. Now you'll have the two versions of the text side by side, and you'd be able to move it around on the "translation" side in order to fit the WhisperX output, so you could make use of its timecodes. In practice this is pretty cumbersome, though, and I wouldn't recommend it, I'd just correct the WhisperX output by hand.

**Comment by xiaopeng12138** [comment]
The forced alignment in wav2vec2 is the solution and I wish Subtitle Edit could add it.

**Comment by ext666** [comment]
I use this technique quite often and my common practice is this:
1) I use Faster-Whisper (or some other alternative) to create subtitles.
https://github.com/guillaumekln/faster-whisper
2) I clean the original template of excess text (character names, timecodes, etc.)
3) This app can compare and sync the text from the template and the subtitles from Whisper.
https://github.com/EtienneAb3d/WhisperTimeSync
4) Profit. You have synchronized subtitles with text from the original template.
