### ISSUE TITLE
Request: Add Sort by Language option

### ISSUE THREAD

**Issue by MbuguaDavid** [SubtitleEdit/subtitleedit#7096]
Is it possible to add a "sort by language" option?
If yes, this would help in scenarios where a subtitle has 2 languages and one wants to see subs for one language. 
I hope this makes sense. 

![sort by language](https://github.com/SubtitleEdit/subtitleedit/assets/92556454/eecf5fff-036b-45b3-8dad-7e8321d154a2)
Thanks!

**Comment by niksedk** [comment]
Hi David, could you attach such a subtitle?

**Comment by MbuguaDavid** [comment]
> Hi David, could you attach such a subtitle?

Sure. 
[Merged Subtitles - English and Chinese.zip](https://github.com/SubtitleEdit/subtitleedit/files/12046486/Merged.Subtitles.-.English.and.Chinese.zip)

**Comment by GrampaWildWilly** [comment]
This thought is inspired by my unexpected success over in issue #7099.  What if instead of something like this:

`1
00:00:00,033 --> 00:00:02,266
In this tutorial,
I'll show you how to add

52
00:00:00,033 --> 00:00:02,266
在本教程中，
我将向您展示如何添加`

you did something like this:

`1
00:00:00,033 --> 00:00:02,266
In this tutorial,
I'll show you how to add
在本教程中，
我将向您展示如何添加`

or maybe this:

`1
在本教程中，
我将向您展示如何添加
In this tutorial,
I'll show you how to add`

Don't have the translation in a separate subtitle.  But the translation in the same caption with the original.

**Comment by Yggdrasil-01** [comment]
This was a question I asked MbuguaDavid on his YT channel and he kindly directed me to this.

I have a srt in question, which has English and Chinese subs, already sort by "number and start time" which I got from somewhere. I've been manually splitting each line to split the languages, then deleting the Chinese and retiming the English subs to the Chinese audio. I couldn't find a way to automatically detect two forms of languages to split them, then select all and delete. 

I can't figure out how to upload a zip file, even though it says zip files are allowed. So I'll just copy and paste a few lines.

16
00:02:03,000 --> 00:02:06,000
公元1131年
In the year 1131,

17
00:02:06,208 --> 00:02:09,083
時值宋高宗紹興元年
during the Song Dynasty,

18
00:02:09,625 --> 00:02:12,833
當時中原河山已為金人統治
China was occupied by the Manchu.
