### ISSUE TITLE
When Using OCR via Google Cloud Vision API I get an error saying "Perhaps Billing is not enabled (or API key is Invalid). 

### ISSUE THREAD

**Issue by thecoachchen** [SubtitleEdit/subtitleedit#7114]
![Screenshot_1](https://github.com/SubtitleEdit/subtitleedit/assets/139764360/8c3c8c29-c0a8-4b5b-aeb4-a897e0405593)

First and foremost, thanks for this program, I love it a lot. 

I'm trying to convert a DVB Sub into a SRT using OCR via Google Cloud Vision API. 

How should I fix this issue? Says the key is invalid but I generated the API key from Google and then put it into the subtitle edit slot. I tried it again after five minutes and I get this same error. 

Enclosed is a screenshot with the problem. 

What other suggestions do you have for me?

**Comment by thecoachchen** [comment]
I selected the free version of Google cloud vision api

**Comment by thecoachchen** [comment]
Tesseract doesn't work very well with Chinese. Which is why I'm using the
google ocr. I already setup the key and I'm able to use this fine.

https://m.youtube.com/watch?v=9Yp4-bSAAVE

**Comment by thecoachchen** [comment]
I enabled billing & I still get the same error.

**Comment by AommyPatty** [comment]
Same error here

**Comment by NotaInutilis** [comment]
Got the same problem, 5 month late, and found the issue!
The error message is misleading: the problem is not billing. You have to actually activate the [Google Cloud Vision API](https://console.cloud.google.com/apis/api/vision.googleapis.com/) in your account so that it's in [the API list of your project](https://console.cloud.google.com/apis/dashboard).

**Comment by thecoachchen** [comment]
Does it actually use the Google API after you enable it like this?

**Comment by NotaInutilis** [comment]
It seems so. The API key doesn't change and the error message that still pops up from time to time is the same.

**Comment by BlohoJo** [comment]
This is beyond frustrating. I [had this problem as well](https://github.com/SubtitleEdit/subtitleedit/issues/8988), and the issue got closed as "won't fix".

I seem to be doing everything right, and yet this error pops up again and again.

There is no input or explanation from the developer as to what could be happening, he just has support for it in his application, but refuses to provide any support for the issue. I mean, it's free software, so that's up to him. I just wish I had some idea as to how to solve this.
