### ISSUE TITLE
Set column order

### ISSUE THREAD

**Issue by Hayholten** [SubtitleEdit/subtitleedit#7169]
Hi everyone,

Quick question: is it possible to set the column order?

By default, when I open SE, they're in this order:

![1](https://github.com/SubtitleEdit/subtitleedit/assets/3150194/a0cd1d01-8587-4b51-8852-04b04aeedb2a)

But for my work, I place Gap, Chars/sec and Words/min on the right:

![2](https://github.com/SubtitleEdit/subtitleedit/assets/3150194/9107d25e-803c-42eb-b55c-6e45b1415dbf)

The only small problem is that every time you restart SE, the default order is restored.

Is it possible to define the order in which the columns are displayed?

Thanks a lot ;)

**Comment by niksedk** [comment]
How is this? https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

**Comment by Hayholten** [comment]
Hello @niksedk,

Thank you very much for your reply.

I'll give it a try with the beta version. Can I only use the "SubtitleEdit.exe" (I use the portable version of SE)?

**Comment by GrampaWildWilly** [comment]
I have been using the portable version of SE for years, including many betas.  The way to upgrade to a new beta is to simply unzip the beta package into your portable directory.  That means EVERY file in the zip package, not just SubtitleEdit.exe.  Every file.  Just be sure Nik didn't accidentally include a Settings.xml in the zip file.  You should skip that file if it's in the zip file.  But I think it's been a couple of years since he made that mistake so you should be fine.  A Settings.xml file from the zip file would replace yours, thus erasing whatever customizations you may have made to the SE settings.  You don't want that.  So unzip the entire zip file into your directory & you should be good to go.
