### ISSUE TITLE
Where is the ">>Tools>Change Casing" words that oneself has added, saved?

### ISSUE THREAD

**Issue by Minherre** [SubtitleEdit/subtitleedit#7212]
Where is the ">>Tools>Change Casing" words that oneself has added earlier (YEARS AGO!), saved?

Now when adding new word(s) (3.6.13, but I haven't used Change Casing for a looong time), it seems it do fix Casing on the word one just added (and the previous [years ago] saved words), but then it seems to Reset other/next new word(s) one added some seconds ago...

So it seems it doesn't Save newly added words any longer ?!

**Comment by niksedk** [comment]
Words from `Change casing - names` are not saved:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/8e7d48b3-bf7a-4b4d-a07a-9d3664f4d5f8)

In order to save names, go to Options - Word lists:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/8fdf7e1d-90db-41da-9b82-c1cf375d7079)

**Comment by Minherre** [comment]
Thanx for reminding me!  

But perhaps then there should be a Tick-Box when one adds Names in Change Casing, so that the newly added names CAN be saved to the "en_names_user.xml" at the same time, and one don't have to do yet another Adding at ">>Options>Word List" as well, Ok ?!

(Since you had Closed this, can you please Confirm you've read this msg too, Please!)

/Cheers!
