### ISSUE TITLE
"No text found" error using Purfview's Faster-Whisper engine

### ISSUE THREAD

**Issue by spacenavy90** [SubtitleEdit/subtitleedit#7217]
"No text found" error using Purfview's Faster-Whisper engine
SE 3.6.13 NEXT beta 537

![image](https://github.com/SubtitleEdit/subtitleedit/assets/10876259/8a5f398a-be50-4181-b104-f30e461536b9)

![image](https://github.com/SubtitleEdit/subtitleedit/assets/10876259/d1b9bbbf-e9d2-4600-85de-faf9fd1c9f66)

![image](https://github.com/SubtitleEdit/subtitleedit/assets/10876259/367e51ef-aada-4154-89ad-cdfa2e5d6c56)

**Comment by Purfview** [comment]
Check what is written in the `error_log.txt` file, it's in SE folder.

**Comment by Purfview** [comment]
I think it's because of the missing libs you need to run it on CUDA.
SE downloads only .exe but not the libs. Get them there -> https://github.com/Purfview/whisper-standalone-win/releases/tag/libs

**Comment by spacenavy90** [comment]
> I think it's because of the missing libs needed to run it on CUDA. SE downloads only .exe but not the libs. Get them there -> https://github.com/Purfview/whisper-standalone-win/releases/tag/libs

This resolved my issue, thank you.
Can these libs be added with SE or at least give an option to download them within the software?
As of now there is no mention of libs being needed to use that engine within SE.

**Comment by Purfview** [comment]
Open a feature request.

**Comment by uckthis** [comment]
Just wondering if this Whisper engine is faster than Const-Me? I tried it, I didn't get any of the warnings even though I didn't download the Cuda libs, and tried to transcribe a 5-minute video and I stopped after 4 minutes as it was taking too long. Const does it in under a minute. Would adding Cuda libs help? Should I put them in Purview folder or make a new directory, or Const is actually faster than this?

Thank you.

**Comment by darnn** [comment]
This is neither here nor there, but I think the real question is, is it more accurate (or as accurate) while being faster than vanilla Whisper. Const-Me is fast, but you can't change any of the settings that affect accuracy. So if you're fine with how accurate it is and you just want speed, I would say stick with it. If not, you should really do some actual comparisons involving speed and accuracy and see for yourself.
Personally I use Const-Me for things that are under 15 minutes, say, and for everything else (when we're talking about audio that isn't in English or isn't crystal clear), I just use Kaggle with WhisperX, which has been the most accurate out of all the versions of Whisper I've tried, at least the last time I checked. It's a bit of a hassle because it creates the virtual environment from scratch every time, but it more than makes up for it in speed, and in the fact that I can do other things with my computer while it's working. Here's the commands I use, in case you want to try:
[kaggle whisperx2.txt](https://github.com/SubtitleEdit/subtitleedit/files/12327711/kaggle.whisperx2.txt)
You have to register for a Kaggle account, but it's free, and you get like 30 hours of VM time a month, which has always been more than enough for me.

**Comment by Purfview** [comment]
> Just wondering if this Whisper engine is faster than Const-Me?

Should be generally faster and better. You need GPU with CUDA support to run it on GPU.

**Comment by uckthis** [comment]
@darnn Thank you for all those helpful suggestions. I have paid so much for this machine and therefore, always am looking to run everything local. I have 24GB Vram; which should be sufficient to run any Whisper engine/model at speeds.
With Const, I can get an hour transcribed in 4-7 minutes depending. I also used Whisper Jax which transcribes an hour long video in less than 30 seconds, but it's always down on Hugging Face.

**Comment by uckthis** [comment]
@Purfview What am I doing wrong then? Where should I put libs?

**Comment by Purfview** [comment]
@uckthis To see what is going on run it in console. Place libs in the same folder where Faster-Whisper executable is or they should be in PATH.

**Comment by spacenavy90** [comment]
I notice that Faster-Whisper produces less "repeating line" errors than Const-me, thus my desire to switch.

**Comment by Purfview** [comment]
@spacenavy90 Try `r145.1` it should fix the bad failure loops.

**Comment by spacenavy90** [comment]
> @spacenavy90 Try `r145.1` it should fix the bad failure loops.

Wow that's great! Tested it on a particularly annoying video of mine and it works perfect. Thank you so much.

**Comment by Purfview** [comment]
Test if auto-download for libs works properly in the latest beta.
