### ISSUE TITLE
A small theme issue

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#7236]
It happens when not using a 100% play rate (for both default and dark themes).
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/4be53125-a4e9-4035-bc74-d88bba8aa191)

and:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/29b99041-9150-4f39-8ed5-108a60d876a0)

build 587.

**Comment by jmaraujouy** [comment]
Yes, the button has two states. One for when custom play rate is disabled, and other for when it is enabled.

The enabled state shows an inverted icon:  ![WaveformPlaybackSpeed](https://github.com/SubtitleEdit/subtitleedit/assets/117078256/d065f2d7-d2f8-4c3a-acc3-99a77b01459e)  ->  ![WaveformPlaybackSpeedSelected](https://github.com/SubtitleEdit/subtitleedit/assets/117078256/a609665c-4b0b-4359-850b-3197085e8164)


In the case of the original (Legacy) icons, they show a blue overlay when selected: ![WaveformPlaybackSpeed](https://github.com/SubtitleEdit/subtitleedit/assets/117078256/8fcc38f0-c020-43ed-94d5-40ca10117afc)  ->  ![WaveformPlaybackSpeedSelected](https://github.com/SubtitleEdit/subtitleedit/assets/117078256/032d1cd5-24ef-4f4d-b49e-20ba3164e74b)

**Comment by LeonCheung** [comment]
@jmaraujouy Hi so you mean it's expected? Hmm, imho using the inverted style seems a bit too much, maybe by replacing the bg color with some gentle color, like:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/1bc572eb-7a27-41d9-8a9c-f9d74a97d797)
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/34084174-c976-41d9-99af-bcdccfc1b1fe)

What's your opinion?

The blue theme style looks just fine with all cases. :)

**Comment by LeonCheung** [comment]
Or, if our dear dev wants to have fun with it, take this crazy idea to show if it's slower or faster than normal rate: 😆 

![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/661e2043-7c1c-4dc4-80e6-d1e49a67d4db)

**Comment by jmaraujouy** [comment]
Anything is possible. My initial plan was to have something like this:

![ezgif-2-53b8e2b0ec](https://github.com/SubtitleEdit/subtitleedit/assets/117078256/293f6173-13dd-4c88-9eee-d0dd55a01f8c)

But, _when it is enabled_, it does not give the impression that it is a pressed button. It just looks like any other icon.

**Comment by LeonCheung** [comment]
Okay, anyway, I mean the color used for the icon right now is of too high contrast (as shown in my first post) and doesn't well align with the whole theme, which even made me think that it's a sort of bug... 😂  Maybe we could improve the design a bit?

**Comment by jmaraujouy** [comment]
Whatever decision you guys adopt its fine by me. 👍🏻

I like this approach, for example: ![260658486-34084174-c976-41d9-99af-bcdccfc1b1fe](https://github.com/SubtitleEdit/subtitleedit/assets/117078256/6770008d-0e22-448e-827c-74faaaf0db24) Another possibility would be to match the video player colors: ![imagen](https://github.com/SubtitleEdit/subtitleedit/assets/117078256/37f41139-8314-4528-8f40-f7a1e31f5429)

The only thing I think it would be a mistake, would be to use two colors in the same icon, like here: ![260658101-1bc572eb-7a27-41d9-8a9c-f9d74a97d797](https://github.com/SubtitleEdit/subtitleedit/assets/117078256/00bdc954-ee89-41d0-9ca1-7430822eeba3)

That's because FluentUI icons are monochromatic & SE new themes icons are monochromatic too _(the video player buttons shows a different color when clicked, but icons are still a single color)_.

@niksedk , what do you think about this?

**Comment by niksedk** [comment]
I initially thought about a blue active color... but then orange for the default blue theme? It does not adhere to the color theme though...

Another solution could be using a state button (like the "Center" button to the left of play rate) which would then have a "blue selected rectangle", but then it would be a popup window/menu instead of a drop-down list with arrow.

The current solution is okay for me too.

Which is these three solutions do you prefer? Or is the another way?

**Comment by LeonCheung** [comment]
@niksedk I think your blue rectangle idea is better than all. Afterall, we just want to remind users a little bit whether it's played at a normal rate or not. It doesn't even quite matter even if we don't have it indicated at all.

BTW, I was always wondering why it wasn't made the same way as the zoom drop-down. 😂

**Comment by niksedk** [comment]
OK, new beta up: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

Not normal play rate (speed):
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/d2608b4e-8951-4ab9-8e4f-3e43d7e28685)

With context menu:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/e15f4729-bfdf-4176-9542-99c657123b94)

**Comment by LeonCheung** [comment]
Nice solution. I may found a small issue, pls confirm if you can repeat it:

1. Unzip beta;
2. Start SE;
3. Enable to dark theme, apply;
4. Disable dark theme, apply.

Then it looks like this until restarting:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/494788/7c3a41b5-3eab-4d20-bca0-f856d7b368f2)

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip
