### ISSUE TITLE
Croatian language file issue

### ISSUE THREAD

**Issue by diomed** [SubtitleEdit/subtitleedit#732]
@xylographe you've messed up updates of Croatian language file [probably 15 days ago] 
when you were adding some changes from your repository.

Last official version of SubtitleEdit has very different file, with lots of language fixes, 
which are now degraded. how come you didn't update file from official repo before changing it? :(

p.s. please come to [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/SubtitleEdit/subtitleedit?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge) if you wish to chat in SubtitleEdit room. :)

**Comment by xylographe** [comment]
As you can see [here](https://github.com/SubtitleEdit/subtitleedit/commit/10ecc81c67d159cdf8db481df3865430b1edf5ab#diff-85a0a3b706e17fbd5b9e42e7d70b5b0c), the *automated XML upkeep* commit effects formatting (white space) only.

See also the [hrv_OCRFixReplaceList.xml commit history](https://github.com/SubtitleEdit/subtitleedit/commits/master/Dictionaries/hrv_OCRFixReplaceList.xml).

The [patch-2](https://github.com/diomed/subtitleedit/commit/e747350e4d7bd6649035f648974f80f21e33e492) and [patch-3](https://github.com/diomed/subtitleedit/commit/085ef61ff9ed5be4ce8764ef7a7b85d2ed87cc5f) branches exist only in your SE fork ([diomed/subtitleedit](https://github.com/diomed/subtitleedit)). These commits have not been merged upstream.

**Comment by diomed** [comment]
I'm not talking about OCR. I'm well aware of those not being merged, 
since I'm checking and fixing some things that shouldn't be there.

I'm talking about https://github.com/SubtitleEdit/subtitleedit/blob/master/src/Languages/hr-HR.xml

where some of the words I've fixed and replaced, and were fine in official release, 
are now reverted back to their previous state.

**Comment by xylographe** [comment]
`U&amp;kloni` is XML syntax for `U&kloni` (the `&` character must be escaped in XML). The `&` before `k` tells Windows that `Alt K` is a keyboard shortcut for opening the menu or selecting the menu item. The `&` will not be displayed, the `k` will be underlined when you press the `Alt` key.

Looking at [the hr-HR.xml history](https://github.com/SubtitleEdit/subtitleedit/commits/master/src/Languages/hr-HR.xml) :

- The reversion of your previous changes took place in commit 32d86a135e78e53479fbc647e35469429d242a42, authored by @jozo65, not by me. GitHub doesn't show the diffs, because there are too many. You can see them [here](https://www.dropbox.com/s/5bw6ox1hv56nqva/hr-HR.diff?dl=0).

- The next commit, 230279553aaa0ce0556d90c765f784affa267cf3, is authored by me, but, doesn't introduce any relevant changes.

**Comment by diomed** [comment]
I see, so that's for shortcuts. That explains a lot.
Though, I also se 0 activity on his github profile page and 0 repositories. How is that possible then?
I'll have to change some of the mistakes all over again.  Back to square 1.

**Comment by xylographe** [comment]
Your changes are still in the repository history. You could copy [this hr-HR.xml](https://raw.githubusercontent.com/xylographe/subtitleedit/xhr0/src/Languages/hr-HR.xml), and search for line pairs marked with M (master) and D (diomed) at the start of the line.

**Comment by xylographe** [comment]
@diomed: It is possible, because commit 32d86a135e78e53479fbc647e35469429d242a42 was **committed** by *niksedk*, and not by its author, *jozo65*.
