### ISSUE TITLE
List view indenting and alignment changes/jumping

### ISSUE THREAD

**Issue by Flitskikker** [SubtitleEdit/subtitleedit#7329]
First, congrats on 4.0.0 :)

One thing I noticed on the new release build, is that the alignment of rows/columns in the subtitle list view sometimes changes/jumps, mainly on red rows/columns.

When fixing errors or when clicking around, the indentation changes in-place.

---

![image](https://github.com/SubtitleEdit/subtitleedit/assets/3516155/f0e38834-aff2-4bcd-a8f6-2a059fa03c6a)
_(see the 1's in the Duration column)_

![image](https://github.com/SubtitleEdit/subtitleedit/assets/3516155/d8da1fa8-acd5-4a54-acab-78e0edf23cc4)
_(the selected row is more to the left)_

---

A video:

https://github.com/SubtitleEdit/subtitleedit/assets/3516155/4cdcec90-73ce-4304-b574-8dbcc5adeb6a

---

Really strange, never seen this behavior before with a ListView...

**Comment by niksedk** [comment]
Hm, it does not happen here... try to look at SubtitleListView_DrawSubItem - maybe you can figure something out.
(also test with bookmark + right-to-left)

**Comment by oep42** [comment]
I see something that may be related to what is discussed above. When the mouse pointer is in the subtitle list, the selected subtitle is darker blue and has the same text size as elsewhere in the subtitle list. When the mouse pointer is above the waveform or when the focus is in a dialog box, the selected subtitle is lighter blue and has a smaller text size than elsewhere in the subtitle list. Moving the mouse pointer between those two parts of the screen, gives a jumping effect, because the smaller text is positioned a little higher than the larger text. The color of the number of the selected subtitle, is also different in those two situations. See the two images below. [SubtitleEdit 4.0.0 NEXT, beta 62.]

![Mouse pointer in subtitle list](https://github.com/SubtitleEdit/subtitleedit/assets/84353335/867747ba-b139-4544-b61f-78452cde9893)

![Mouse pointer in wave form or focus in dialog box](https://github.com/SubtitleEdit/subtitleedit/assets/84353335/68966714-13df-402d-a33b-758046a91fc2)
