### ISSUE TITLE
 Whisper Fine-tuned Models - faster-whisper

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#7332]
Since faster-whisper supports fined tuned models after conversion 
https://github.com/guillaumekln/faster-whisper#model-conversion

I was wondering if we could have this option in SE GUI. It'd be easier to convert and then use a fine-tuned model in GUI rather than CMD as many of us aren't CMD savvy.

**Comment by Purfview** [comment]
If you are not savvy then you shouldn't bother about those custom models.

**Comment by uckthis** [comment]
I'm not savvy, but I have 24GB VRAM, so I help out friends and colleagues who transcribe in foreign languages like French, German, Spanish, etc., and even though we get good results with base models, we think we can get much better accuracy with fine-tuned models for those languages, hence this thread. My apologies, I didn't mean to poke your high horse.

**Comment by Peacemanguy** [comment]
I think it wouldn't be that bad of an idea.
Having the option to import custom/official models.
You never know for how long the repo will get maintained and that way when v3/v4 etc comes in the future at least you can just clone the hf repo in the models folder and be done with it.

**Comment by darnn** [comment]
After messing with it a bit, I agree that it would be good for SE to at least scan the model folder and show anything starting with faster-whisper in the GUI, since as it stands, I have to, like, replace the tiny model with the one I want to use, and then select tiny in the GUI, instead of having the other folder just show up in the list.
