### ISSUE TITLE
Hebrew Text looks fine in Preview, but not after generating video w/ burnt-in or embed

### ISSUE THREAD

**Issue by aaamittt** [SubtitleEdit/subtitleedit#7536]
In SubtitleEdit video preview: 
![image](https://github.com/SubtitleEdit/subtitleedit/assets/89802564/d3efff53-2b84-40fa-ac29-529d9738d52b)

In the textbox:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/89802564/afaaf8b1-f922-4a9d-97bf-eb09e39c7242)

My settings: 
![image](https://github.com/SubtitleEdit/subtitleedit/assets/89802564/7d7b70f9-c803-4878-847b-7a49655d895e)
Subtitle Format: SubRip
Encoding: UTF-8 with BOM (tried other Hebrew encoding options as well, doesn't seem to make any difference)

And yet, when generating burnt-in subtitles (or embedded subs), they become out of order: 
![image](https://github.com/SubtitleEdit/subtitleedit/assets/89802564/3029c4e3-b885-4868-9d11-5886bbf06bba)

Any advise on how to fix this?

**Comment by niksedk** [comment]
The preview video player automatically uses "Fix RTL via Unicode control characters" 
(you can do "Fix RTL via Unicode control characters" manually via the Edit menu)

You can also do this in the "Generate video with burned-in subtitles":
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/e3e0fec5-6a21-4c47-9245-e4c767b6f6d7)

I really do not know much about RTL...

**Comment by frumkin-amit** [comment]
Afraid I got the same results with either or both options :(

**Comment by niksedk** [comment]
Could you attach a subtitle that gives this result + a little explanation?

**Comment by frumkin-amit** [comment]
For sure, sorry about that! Attached is the SRT file
[Into The Woods_wip-29.10,2023.txt](https://github.com/SubtitleEdit/subtitleedit/files/13197401/Into.The.Woods_wip-29.10.2023.txt)

I also attempted to generate a video with burnt-in subtitles with the "Fix RTL via Unicode control characters" (and one without), and encountered the same issue (the beginning is a bit frozen for some reason, just skip ahead a couple of seconds): 

https://github.com/SubtitleEdit/subtitleedit/assets/89802564/3f24ca6f-38fb-4c41-9b63-3c0cc2727aae

I'd like to clarify also that this seems to be happening specifically _because_ of the special characters( `-[]—` ) , though no setting I've tried made any difference. I'm starting to think I should manually flip the order via the text editor. 

Thank you again!

**Comment by darnn** [comment]
Why are you using SRT and not ASS? Not that I know for a fact this would work with ASS in SE, but at least you'd be able to take the ASS and use it with any other program that can encode video with burned-in subtitles (I use Handbrake, it's free).
Also, drop me a line at thedarnn@gmail.com, if you don't mind, since I'd like to say something about things that aren't directly related to SE.

**Comment by frumkin-amit** [comment]
Hi, I tried switching to ASS but the same issue is happening. Attaching an updated burned-in and subtitles (in txt, won't let me upload ASS or SRT files here). 

https://github.com/SubtitleEdit/subtitleedit/assets/89802564/553ddbd7-76ad-4c30-954f-bfcbe2f19eef

[Into The Woods_wip.txt](https://github.com/SubtitleEdit/subtitleedit/files/13200527/Into.The.Woods_wip.txt)

Thank you again!

**Comment by darnn** [comment]
Okay, I think I've worked out a way to get the characters where you want them, but it's not necessarily going to be easy to apply to your file:
You need to remove the Unicode control characters. Then strip all the HTML tags. Then do `Reverse RTL start/end` on all your text. Now, I don't know what it's going to look like burned in, but it at least appears as it should in the preview, including the ASS preview. Then you need to restore all the HTML tags. So, I'm not sure how you'd go about doing that, since you can't even replace them with placeholder symbols, but it's something actionable at least.
