### ISSUE TITLE
[Feature Request] Use AI to shorten lines that are too long

### ISSUE THREAD

**Issue by shootlazer** [SubtitleEdit/subtitleedit#7598]
Subtitles generated with Whisper usually contain some lines that are too long to read in time. Official subs usually get around this by removing words.

ChatGPT could be used to summarize those (without changing the meaning of the phrase)

**Comment by darnn** [comment]
FWIW, I haven't been able to do this consistently with just feeding it text manually and asking to shorten each sentence by X percent without losing any of the meaning. Try it yourself and see if there's any prompt that actually works for you, to start with.
Also, the demand for shortening itself really depends on the customer - I've only encountered it once or twice since I've started transcribing for subtitles. The rest of the time people want everything that's said, at most without exclamations and repeated words.

**Comment by shootlazer** [comment]
> FWIW, I haven't been able to do this consistently with just feeding it text manually and asking to shorten each sentence by X percent without losing any of the meaning. Try it yourself and see if there's any prompt that actually works for you, to start with. Also, the demand for shortening itself really depends on the customer - I've only encountered it once or twice since I've started transcribing for subtitles. The rest of the time people want everything that's said, at most without exclamations and repeated words.

I've been able to do this although didn't test in english. The only issue I've encountered is that if you paste a chunk of lines, it misses some until you tell it to redo it again (which could be automated too)

Just prompting something like "delete some words without changing the meaning" and then "line XXX is still too long" etc
