### ISSUE TITLE
Win11 SE403 setup doesn't start

### ISSUE THREAD

**Issue by carlvanwormer** [SubtitleEdit/subtitleedit#7785]
On 2 different (current version) Win11 systems, SE403 won't start the installer.  SE402 and SE401 work OK.  Also, portable version 401 works, but 402 and 403 portable do nothing when opened.  I don't get any event viewer notifications for the failed starts.  I don't have Controlled Folder Access enabled and I get no Windows Defender events.  Am I doing something wrong?  
Thanks,
Carl

**Comment by zalastone** [comment]
I have a problem with ffmpeg too. you should use the portable version for now

**Comment by carlvanwormer** [comment]
The 403 portable version doesn’t work for me either.  Is there something wrong with my systems, or is it a problem with the installer?

Thanks,
Carl

**Comment by GrampaWildWilly** [comment]
I've managed to get portable SE 4.0.3 to open in Windows 11 & play video.  I can't say I've done any serious work with it, but it at least opens & appears to function.  But there are some odd things I'd like to report.

I must mention that I run with the video controls undocked.  The video window is on my secondary monitor, which is my TV.  The other 3 windows are on my primary monitor.  (You might have to open the images below in their own browser tabs & magnify them to see them properly.)

![#01](https://github.com/SubtitleEdit/subtitleedit/assets/75588964/928b1a3a-34b7-4d43-801c-ae0d57c0d2bc)

Note the window border at the top & the MPV controls at the bottom.  Alt+Enter does not toggle in & out of fullscreen.  I can't get rid of the things at the top & bottom, & I can't get this to change . . . UNTIL.  Until I switch tasks so the video window is in focus.  Then I use the W11 keyboard function Win+UpArrow.  This is the shortcut for toggling window size between Maximum & Restore.  So I Win+UpArrow to restore the window out of maximum.

![#02](https://github.com/SubtitleEdit/subtitleedit/assets/75588964/0635fa4b-5081-4e2d-b2c7-84be345a3372)


Now if I use the SE shortcut Alt+Enter, it toggles in & out of fullscreen & I don't see the MPV controls at the bottom.  When I first toggle into fullscreen, the controls appear for a second or 2, then disappear, which is the way it's supposed to work.

![#03](https://github.com/SubtitleEdit/subtitleedit/assets/75588964/8180e643-4e04-41c1-bca5-320563c30d6f)

I can make the controls appear at the bottom if I press a key, for example Ctrl.  Just Ctrl by itself.  The controls remain visible until I release the key.

![#04](https://github.com/SubtitleEdit/subtitleedit/assets/75588964/4bc6c954-9fe8-47d9-a391-07c9bdbb28a5)

But this works ONLY if the video window is the window in focus.  If I switch tasks to the main SE window, Alt+Enter does nothing.  Ctrl by itself does nothing.  Used to be that these keyboard actions would affect the video window from the main SE window.

Next weirdness.  This involves SE keyboard shortcuts.  There are 2 shortcuts for setting large skip intervals.

![#05](https://github.com/SubtitleEdit/subtitleedit/assets/75588964/0fed7777-0919-41d6-9752-01e02855ac4c)

The wording there says "selected time."  I don't see any way to select a time.  So, being the tinkerer that I am, I edited Settings.XML & found the `<Shortcuts>` section.  In there, I found these lines:

    <MainVideoXLMsLeft>Control+Alt+Shift+Left</MainVideoXLMsLeft>
    <MainVideoXLMsRight>Control+Alt+Shift+Right</MainVideoXLMsRight>

But I don't see any lines that might be providing intervals for these 2 shortcuts.  Maybe there's a couple of XML tags I could add to Settings.XML to set my desired skip intervals.  But I don't know what names I'm supposed to use.  However, I believe somebody reading this knows.  Gee I wonder who that could be . . .

Next issue.  When SE opens in undocked mode, the Windows Alt+Tab task list shows 4 SE tasks: main, video, audio, controls.  If I switch tasks so that any of the 3 windows besides main has focus, main disappears from the Alt+Tab list.  Only explicitly putting focus back on main makes it reappear in the Alt+Tab list.  This may just be weirdness on the part of Windows.  Or it may be something you can change in the way SE defines itself to the operating system.  Again, I'm not the expert so . . .

Here's wishing one & all a lovely holiday season & a great New SE Year!

**Comment by carlvanwormer** [comment]
GrampaWildWilly
>  I've managed to get portable SE 4.0.3 to open in Windows 11 & play video. I can't say I've done any serious work with it, but it at least opens & appears to function.

I'm running Win11 22H2.  When I right-click on the portable version of SE403 SubtitleEdit.exe file, I can select Open or Run as administrator.  Either choice gives me the little spinning circle for a second, then nothing else.  Performing either action on the portable version of SE401 runs the program (as expected).  
Performing the same actions on the standard versions, the SubtitleEdit-4.0.1-Setup.exe and SubtitleEdit-4.0.2-Setup.exe both execute the installer, giving a properly working version of the programs, while "executing" SubtitleEdit-4.0.3-Setup.exe gives only the unsatisfying 1-second spinning circle without any other observable effects.

What version of Win11 are you running?

Thanks,
Carl

**Comment by Purfview** [comment]
> On 2 different (current version) Win11 systems, SE403 won't start the installer. SE402 and SE401 work OK. 

Firefox blocks downloading exe files, check if it's actually download and it's not 0 bytes exe file.

> I'm running Win11 22H2. When I right-click on the portable version of SE403 SubtitleEdit.exe file,

Where did you extracted it? Don't extract it to the Windows' folders.

**Comment by carlvanwormer** [comment]
All zips downloaded and extracted, so there were no download errors.  I extracted to folders in my downloads folder, so there were no permissions problems.  There were no errors generated and no events in my Application, Security, or System Event Viewer logs.

**Comment by Purfview** [comment]
Try what I wrote to you.

**Comment by carlvanwormer** [comment]
Solution!  Use 7-Zip instead of windows built-in "Extract All" method to extract the programs from the zip archives.  Your suggestion to extract to a different disk seemed "crazy", but I tried it anyway.  The Extract All defaults to "extract all" and I didn't know I could right click on the extract all to get to the browse function.  I used 7-Zip to extract the files to my D drive and the SE403 worked.  After a bunch of troubleshooting, I discovered it was the unzipper that was causing the problem/solution, even though the resultant unzips were "the same".  Winmerge reports the files to be identical.  There must be some magic attributes associated with the unzipping of the files.  Does anybody have any clues here?

**Comment by Purfview** [comment]
Told you that don't extract to Windows' folders. 😉

**Comment by GrampaWildWilly** [comment]
I'm running W11 Pro 23H2 64-bit.  I'm not all that smart about these things.  I just
unzipped the portable zip file into the same directory where I already had SE.  I've had
SE in this directory for years, going back I don't know how many releases of SE, plus
back to W7.  I only just about a month ago got this W11 computer running.  It was not an
upgrade on top of W7.  It was a new, bare computer & a clean install of W11.  All my HDDs
are from the W7 system.  I just unplugged them from the old computer & plugged them into
the new computer.  So this installation of SE is not simply a copy of the one I was
running on W7.  It IS the one I was running on W7.  But my last version of SE on W7
wasn't 4.0.3.  It might have be 3.something.  I don't remember.  All I know is I simply
plopped the new SE down on top of the old & presto, it worked.  I'm still using the
Settings.XML I've been using since forever.  This is the technique I have used for moving
to a new release of SE for years.

I'm not sure how much help this is.  An idea I have is to unzip the portable SE into a
fresh, empty directory & see if that will run.  If it does, close it, copy your
Settings.XML from your old directory into this new one, then see if that will run.  I
know there's several subdirectories of the SE directory.  I don't know how much of that
data you should or even can simply copy over to the fresh directory.  I don't do any of
the fancy stuff these guys post about here.  I don't do automatic generation of subtitles
from audio & I don't do translations.  I just do the occasional edit of an existing
captions file, & light edits at that.  The heaviest thing I do is Fix Common Errors
because certain opera companies believe a caption can't last longer than 1 second, so
I'll see 5 or 6 consecutive identical captions of 1 second duration each.  Of course,
letting SE fix that makes for a considerably smaller caption file.  Plus I deal
exclusively with vtt.  I convert the occasional srt I encounter to vtt.  I've never used
ASSA or any other format.  So I don't really exercise all the distant corners of SE so I
don't know what useful other stuff you might need to copy besides Settings.XML to get
your old configuration back in a fresh install.  I'm sure somebody else reading this
could tell you about that.

That's probably the best I can come up with.  Maybe somebody else can do better.  I wish
you luck.

**Comment by GrampaWildWilly** [comment]
I see now there's been other responses here before mine.  Interesting what you say about the built-in unzip.  I never even considered trying to use that.  Given your experience, I have a concrete reason to keep avoiding it.  I'm using an antique unzip program I've been running since about 1998.  It's a Java application.  Not a Java applet running in a browser.  A standalone Java app.  I'm currently using Java 18 with this thing but I think I started using it with Java 4.  But I also have PeaZip & that's been pretty reliable for me as well.  The Java unzipper is 32-bit so it won't handle bigger zip archives.  I use PeaZip for those.  The SE package is small enough for my Java unzipper.

In case anybody is interested, it's from an organization called RPF Software & it's called Zip Control.  It hasn't been updated in at least a decade.  I'm not sure they're still active as a going concern.  But their web site was still up last time I checked, so you could get that old but current release.  Of course, you have to install Java as well, but that's as simple as unzipping that package, which I believe is distributed as a self unzip exe.  It's a lot like ffmpeg that way.  You have to add the Java bin subdirectory to the system PATH, & that's it.  Java will be installed.

**Comment by carlvanwormer** [comment]
Is there any way to raise the "solution" to a higher level to avoid the majority of the text that has no value to the problem?
Thanks,
Carl

**Comment by Purfview** [comment]
Solution:
```Don't extract it to the Windows' folders.```

**Comment by carlvanwormer** [comment]
I just receive an email indicated that this issue had been closed with the text:
Solution:
Don't extract it to the Windows' folders.

This was not the solution of my problem because I was not extracting to my Windows folder.  The solution was too not use the built-in windows extract function (extracting to my downloads folder) but to use 7-zip to perform the extraction.

**Comment by Purfview** [comment]
> I was not extracting to my Windows folder

I didn't wrote "Windows folder", it's -> `Windows' folders`.

> extracting to my downloads folder

That doesn't say much. Folders are described by the paths.

**Comment by niksedk** [comment]
> Is there any way to raise the "solution" to a higher level to avoid the majority of the text that has no value to the problem? 

Sorry, no.

But be sure to extract all files - as in https://github.com/SubtitleEdit/subtitleedit/issues/7785#issuecomment-1869091039

And as Purfview wrote about the portable version: ```Don't extract it to the Windows' folders.```

**Comment by carlvanwormer** [comment]
I don't understand your distinction or instructions.
When I download the file, I let it go into my default Downloads folder (C:\Users\Carl\Downloads).  

1. When I select the downloaded zip archive and then right-click and select Extract, the archive is extracted into a new folder (named as the filename) in my downloads folder.  Going into this new folder and selecting the executable file doesn't do anything (my initial reported problem).  
2. When I select the downloaded zip archive and then right-click and select 7-Zip and then select the Extract to "filename", the archive is extracted to a new folder (named as the filename) in my downloads folder.  Going to this new folder and selecting the executable runs the install as expected.  

I believe the only difference between these 2 actions is the method of extraction.  Using the windows extractor doesn't result in a functional install program, while running the 7-Zip program works as expected.  The resultant files of the 2 extractions are pronounced "the same" by the WinMerge comparison program.  There must be some windows file bits that are set differently. This is a new problem for me and using the built-in windows extractor works on earlier versions of the downloads.

Am I missing something important in your references?
Am I beating a dead horse in my responses?

Thanks,
Carl

**Comment by Purfview** [comment]
> C:\Users

It's folder created by Windows, so in my book it's Windows' folder.
Try this: Extract with your "1" method to disk "D:\", if you can't select it then move it there after extraction. Check if it runs now.

**Comment by carlvanwormer** [comment]
That is what I did (selecting my D: drive with "Extract" that worked, leading me to the alternative 7-Zip.  The difference (and my confusion) is that the 7-Zip extraction to my download folder works and the windows Extract extraction to that same folder does not work.  Also, it is only giving problems on newer versions of the code (both portable and installed versions).  
I'd like to know why.  Is it some new kind of protection that Win11 is doing "for" me?

Thanks,
Carl

**Comment by Purfview** [comment]
So, as I understood you: If you extract to ` D:\` then the both methods work, if you extract to `C:\Users\Carl\Downloads` then only 7-Zip method works, is that what you meant?

**Comment by carlvanwormer** [comment]
Yes,  I think that was the results of multiple processes trying to debug the system.  I was even able to repeat the problem for the ffmpeg installation (mentioned by zalastone).
If somebody else is having similar problems, we might be able to do more testing to find out what has "broken", but the 7-Zip process will be my go-to extractor for now.

Thanks,
Carl

**Comment by GrampaWildWilly** [comment]
My take on this is that the destination of the unzip is a bit of a red herring.  I think to make SE truly portable, you need to place its directory tree some place else than any directory structure created by the Windows install.  So it belongs elsewhere than C:\Windows, C:\Documents and Settings, C:\Users, C:\Program Files, C:\Program Files (x86), and so on.  I have my SE on my C drive, but it's in C:\Subtitle Edit.  C vs D is not the point.  Just outside the Windows directories is the point.

Now, if you want to test which zip utility is doing the right thing, you should create 2 directories, let's say x:\First and x:\Second.  The drive letter is unimportant.  Just 2 new, empty directories.  Into First, unzip something (presumably the postable SE installation package) using the Windows built-in utility.  Into Second, unzip the same thing using the unzip utility of your choice, just not the built-in utility.  Compare the results.  I use Zip Control & PeaZip & I don't have problems.  Apparently, 7zip works well for you.

There are typically options on unzip utilities that control what gets unzipped.  If there are file name collisions, a typical unzip utility might unconditionally overwrite an existing file, might unconditionally preserve an existing file, might replace an existing file based on date/time stamps, might prompt you.  Perhaps the built-in utility has a default behavior that needs to be looked into.  Perhaps other utilities take more reasonable default behaviors.  In the end, you need to use the tool that best serves you & the way you work.

**Comment by Purfview** [comment]
> Yes, I think that was the results of multiple processes trying to debug the system.

Then that confirms -> `Don't extract it to the Windows' folders.`

> I'd like to know why. 

Must be the Windows' alternate streams with "zone" nonsense, when 7-zip just ignores it.
You should see those streams with `dir /r` command.

**Comment by carlvanwormer** [comment]
More confusion - beating a dead horse . . .
On the original system (my wife's video editing computer), after a reboot, I still have the repeatable problem.  I tried downloading to her M:video drive in a subfolder named Carl, I extracted using the windows Extract All (into self-named folders under Carl) for the executables for the portable and install versions of SE 401, 402, and 403. The 401 and 402 versions worked but the 403 versions did nothing when the executable file was double-clicked. 
On my main system (where I discovered the interesting behavior), something has changed and I now have no problem with all 3 versions that are downloaded to my Downloads folder and then unzipping to the self-named folders under the Downloads folder using either unzipping method.  The problem is no longer repeatable on my main computer.  I also noticed that Chrome is now complaining about the danger of the 403 version (suspicious download blocked), needing an extra acknowledgement to continue the download (which it did not do last week).
I can only guess that "the man behind the curtain" is pulling some levers on links between the various windows APIs to make my life more interesting.  
Thanks,
Carl

**Comment by Purfview** [comment]
Did you checked what is written to the alternate steams?

**Comment by carlvanwormer** [comment]
There are no alternative data streams showing up in the dir /r command issued in either folder that the unzipping is taking place.  I can see the $DATA alternate data streams if I do the dir /r command in the Downloads folder, but none are related to the files or folders we are discussing.

**Comment by Purfview** [comment]
>  I can see the $DATA alternate data streams if I do the dir /r command in the Downloads folder, but none are related to the files or folders we are discussing.

Maybe such stream is created for the extracted folder and not for the extracted files.

**Comment by carlvanwormer** [comment]
The created folders (from the two unzipping methods) do not show any stream attributes.  I don't think the streams are related to the problem.  Are there any other "man behind the curtain" levers that Windows11 might be exercising?  The fact that one of my machines has stopped duplicating the problem and has changed its Defender responses is suspicious, but I don't know where to look.  Are there any tools to view the "newly downloaded" bit that Defender uses to "detect" suspicious files?
Thanks,
Carl

**Comment by Purfview** [comment]
Dunno, I don't use Windows 11 and I disable "Defender" as soon as I touch keyboard.

Ask some forum for the Windows problems.
