### ISSUE TITLE
Best method for update portable and exe

### ISSUE THREAD

**Issue by johnfelipe** [SubtitleEdit/subtitleedit#7791]
I have portable and installable, how is best method for update to latest version?

**Comment by niksedk** [comment]
Hi @johnfelipe,

The easiest way is probably just unpacking and overwriting files. Your settings + ocr/spellcheck stuff should be kept.

I do think it's good to once in a while to start from scratch, as SE might have tweaked some settings.
If you have made your own OCR dictionaries, or added a lot of user words during spell check, you could copy these files to the new installation.

**Comment by Perkolator** [comment]
> Your settings + ocr/spellcheck stuff should be kept.

Unfortunately updating portable SE is a PITA, in order to keep your old settings and make sure that possible new/changed settings and files from a new version are properly updated, one has to: 1) run the new version separately to create a new `Settings.xml` file , 2) compare (with a proper software for this, not in file manager) the new & old portable folder trees and then compare every updated file and merge either the whole new file or just some lines/strings from the new file (e.g. Settings.xml file is the worst, if you have changed many settings, you need to go through all the lines and decide/remember which ones to keep and which ones are new from the new version), 3) after merging all; run SE and update new tesseract (and language files), if available, and then remove older tesseract folders, 4) also remember to update mpv & ffmpeg from the settings. (I hope I remembered all)

**Comment by johnfelipe** [comment]
is not possible only put portable in new folder, and export models?, i will try...

**Comment by johnfelipe** [comment]
![SNAG-0172](https://github.com/SubtitleEdit/subtitleedit/assets/428820/2397141f-d116-4448-bdeb-2189bd7f4a79)

Not working, im really need skip download of that models again, there is not option more simple in this case for portable and executable version?
