### ISSUE TITLE
Add Names to the On-Line names.xml

### ISSUE THREAD

**Issue by Minherre** [SubtitleEdit/subtitleedit#7816]
How to Add all my Hundreds of Names to the On-Line names.xml ?

At least there should be an option for users of SE to suggest more names to the list!

Certain Subs (especially almost ALL of BAE's Subs...) are totally fucked up when it comes to missing Capital first in all names, not to mention all other constant problems with BAE Subs...

**Comment by niksedk** [comment]
You can add a PR (pull request) with changes to `names.xml` or `en_names.xml` - or just post the names here.

See:
https://github.com/SubtitleEdit/subtitleedit/blob/main/Dictionaries/names.xml
https://github.com/SubtitleEdit/subtitleedit/blob/main/Dictionaries/en_names.xml

If the names conflict with other languages, then the name should be added to `en_names.xml` - otherwise the name should be added to `names.xml`.

What is `BAE`?

**Comment by Minherre** [comment]
Ok, Thanx!
Will check my lists  (any day now...  ;-)

(BAE is a Release Group, also called Warez Group)
