### ISSUE TITLE
google gemini pro translate requirement

### ISSUE THREAD

**Issue by likangkao** [SubtitleEdit/subtitleedit#7868]
Since google gemini pro is on-line now for free, can you add a new translation service from it. Thanks!

**Comment by darnn** [comment]
Implemented here, for the record: https://github.com/openai-translator/openai-translator/

**Comment by niksedk** [comment]
Sorry, I have no idea of how to get an API key... maybe later.

**Comment by darnn** [comment]
FWIW, you just go here and click "get an API key":
 https://ai.google.dev/tutorials/setup

**Comment by niksedk** [comment]
> FWIW, you just go here and click "get an API key": https://ai.google.dev/tutorials/setup

` Google AI Studio is not available in your region `

**Comment by niksedk** [comment]
> FWIW, you just go here and click "get an API key": https://ai.google.dev/tutorials/setup

Could you try latest beta? 
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.3/SubtitleEditBeta.zip

Do check the error_log.txt after trying (I still cannot call even with api key due location error)

**Comment by darnn** [comment]
Original:
[ww original.srt.txt](https://github.com/SubtitleEdit/subtitleedit/files/14076831/ww.original.srt.txt)

Translated:
[ww translated.srt.txt](https://github.com/SubtitleEdit/subtitleedit/files/14076832/ww.translated.srt.txt)

Error log:
[error_log.txt](https://github.com/SubtitleEdit/subtitleedit/files/14076834/error_log.txt)

It's also much slower than the program I linked above, not sure why, if it's all being sent and received at once. But that's neither here nor there.

While we're on the subject, could you add Hebrew to the lists of languages in the Auto-translate menu (in the ones where it's missing)?

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.3/SubtitleEditBeta.zip

**Comment by darnn** [comment]
Thank you for the Hebrew! The only issue I seem to have now (with the two files I checked) is that in about half of the translated subtitles, `<br />` will randomly appear. The translation seems to be slower the more issues Gemini has with the content, and sometimes it seems like it will outright not translate entire lines if it finds them objectionable.

Also, when I hit cancel during the translation I got the following error:
A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nikse.SubtitleEdit.Core.AutoTranslate.GeminiTranslate.<Translate>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nikse.SubtitleEdit.Forms.Translate.MergeAndSplitHelper.<MergeAndTranslateIfPossible>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Nikse.SubtitleEdit.Forms.Translate.AutoTranslate.<buttonTranslate_Click>d__32.MoveNext()

Error log:

[error_log.txt](https://github.com/SubtitleEdit/subtitleedit/files/14077398/error_log.txt)

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.3/SubtitleEditBeta.zip
Might not crash when cancelling... and `<br />` might be better too.

Also, the beta might handle mymemory better.

**Comment by darnn** [comment]
Yep, the error is gone on my end. MyMemory is the same in English and Russian, however, still codes instead of letters.

**Comment by colemar** [comment]
I see the previous 4.0.11 beta (cannot remember which one exactly) had Gemini Pro as a model choice. It didn't work though.
Now 4.0.11 beta 258 has only Flash and Flash Lite.
Gemini Pro is much much better at translating in my experience.
Could you add it to SE auto-translate?
![Image](https://github.com/user-attachments/assets/802a9fb5-3b66-45c9-96e9-db7bfe149bef)

**Comment by niksedk** [comment]
@colemar: You can just type a model name... What model name is working? `gemini-2.5-pro-preview-03-25` ?


https://cloud.google.com/vertex-ai/generative-ai/docs/learn/models

**Comment by yumeverse** [comment]
I just tested 4.0.11 beta with gemini api key and typed
gemini-2.5-pro-preview-03-25
in the model section and I am getting 404 error 
I tested preset model flash and flash light and they worked but not "gemini-2.5-pro-preview-03-25"

**Comment by colemar** [comment]
@niksedk 
```
Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Nikse.SubtitleEdit.Core.AutoTranslate.GeminiTranslate.<Translate>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nikse.SubtitleEdit.Forms.Translate.MergeAndSplitHelper.<MergeAndTranslateIfPossible>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Nikse.SubtitleEdit.Forms.Translate.AutoTranslate.<buttonTranslate_Click>d__33.MoveNext()
{
  "error": {
    "code": 404,
    "message": "models/gemini-2.5-pro-preview-03-25 is not found for API version v1, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.",
    "status": "NOT_FOUND"
  }
}
```

**Comment by niksedk** [comment]
It's a bit hard to see what models are available, what about `gemini-2.5-pro-exp-03-25` or `gemini-1.5-pro` ?

**Comment by colemar** [comment]
### What is the internal model name to give for 2.5 Pro experimental when using API version v1?

Okay, based on the typical naming conventions for Google's generative models via the API, there isn't a publicly documented model explicitly named "2.5 Pro experimental" for the stable `v1` API version.

Here's a breakdown:

1.  **Experimental Models:** Models designated as "experimental" or "preview" are usually accessed via the `v1beta` version of the API, not `v1`.
2.  **Naming Convention:** Stable models available through `v1` generally follow the pattern `gemini-<version>-pro`. For example:
    * `gemini-1.0-pro`
    * `gemini-1.5-pro` (The latest publicly available Pro model as of recent documentation)
3.  **"2.5 Pro":** There hasn't been a public announcement or release of a "Gemini 2.5 Pro" model yet.

**Possible Scenarios:**

* **Typo?** Could it be a typo for `gemini-1.5-pro`?
* **Internal Name?** Are you perhaps referring to an internal codename or a very early, non-public preview? Such names wouldn't typically be accessible via the public `v1` API.
* **Future Model?** It might refer to a future planned model, but it wouldn't have an identifier in the current `v1` API.

**Recommendation:**

For the `v1` API, you should use the identifier for the latest stable Pro model available, which is likely:

```
gemini-1.5-pro
```

If you specifically need access to an *experimental* feature or model, you would typically use the `v1beta` API endpoint and check the documentation for the correct model identifier available there (which might include suffixes like `-preview-<date>`).

Could you clarify where you encountered the name "2.5 Pro experimental"? That might help pinpoint the exact model or context you're looking for.

### On this web page I am accessing now there is "2.5 Pro (experimental)" in the upper left corner.

Ah, thank you for the clarification! Seeing "2.5 Pro (experimental)" in the upper left corner strongly suggests you are likely using a specific Google interface, probably **Google AI Studio** (formerly known as MakerSuite) or a similar internal testing environment.

Here's the important distinction:

1.  **Web Interface Display Name:** Google AI Studio often gets access to models in preview or experimental stages. The name displayed there ("2.5 Pro (experimental)") is a user-friendly label for the model you are interacting with *within that specific web tool*.
2.  **API Model Identifier:** The identifier you use when making direct calls to the API (like the `v1` or `v1beta` REST endpoints or using client libraries) can be different.

**Key Points:**

* **`v1` vs. `v1beta`:** The stable `v1` API version typically only lists generally available, stable models. Experimental models are almost always accessed via the `v1beta` API version or might *only* be available through interfaces like Google AI Studio for testing before any API access is granted.
* **No Guarantee of `v1` API Access:** Just because a model labeled "2.5 Pro (experimental)" exists in AI Studio doesn't automatically mean it has a corresponding identifier available for you to call via the public `v1` API. It might only be usable through that specific web interface, or potentially via the `v1beta` API using a specific preview identifier (which might not even be simply `gemini-2.5-pro-experimental`).

**Conclusion:**

While you are seeing "2.5 Pro (experimental)" in the web interface you're using, there is **no corresponding standard model identifier named `gemini-2.5-pro-experimental` (or similar) documented for the `v1` API version.**

* If you need to use the absolute latest *stable* Pro model via the `v1` API, you should likely still use `gemini-1.5-pro`.
* If you want to programmatically access the model labeled "2.5 Pro (experimental)", you would need to:
    1.  Check if it's available via the **`v1beta`** API.
    2.  Consult the most recent Google AI documentation for `v1beta` model identifiers to see if an identifier corresponding to this experimental model has been released for API use. It might have a specific name like `gemini-experimental` or a name with a preview tag.
    3.  Accept that it might *only* be accessible through the Google AI Studio interface for now and not yet via the public API.

![Image](https://github.com/user-attachments/assets/841ff8f5-41d5-4b6e-ad0e-9235ab11a63a)

**Comment by colemar** [comment]
Well, this works:

```
$ curl -i https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-pro-exp-03-25:generateContent?key=$GEMINI_API_KEY -H 'Content-Type: application/json' -X POST -d '{"contents":[{"parts":[{ "text":"Translate \"How do you do\" to italian language."}]}]}'

HTTP/2 200
content-type: application/json; charset=UTF-8
vary: X-Origin
vary: Referer
vary: Origin,Accept-Encoding
date: Tue, 08 Apr 2025 22:53:00 GMT
server: scaffolding on HTTPServer2
x-xss-protection: 0
x-frame-options: SAMEORIGIN
x-content-type-options: nosniff
server-timing: gfet4t7; dur=12442
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
accept-ranges: none

{
  "candidates": [
    {
      "content": {
        "parts": [
          {
            "text": "Okay, translating \"How do you do\" requires a bit of context because it's a rather formal and somewhat old-fashioned English greeting that doesn't have a *direct* equivalent phrase in modern Italian used in the same way.\n\nHere are the best options depending on the situation:\n\n1.  **For a first introduction (most common use of \"How do you do\"):**\n    *   **Piacere di conoscerla.** (Formal 'you' - used when addressing someone older, in a formal setting, or someone you don't know well) - Translates to \"Pleasure to meet you.\"\n    *   **Piacere di conoscerti.** (Informal 'you' - used with peers, younger people, or in casual settings) - Translates to \"Pleasure to meet you.\"\n    *   Often, Italians simply say: **Piacere.** (Pleasure.) - This is very common and works in both formal and informal contexts upon introduction.\n\n2.  **If you mean it more like \"How are you?\" (though \"How do you do\" isn't usually answered literally):**\n    *   **Come sta?** (Formal 'you') - \"How are you?\"\n    *   **Come stai?** (Informal 'you') - \"How are you?\"\n\n**Why a direct translation doesn't work:**\n\nA literal word-for-word translation like \"Come fa?\" (How does he/she/it do?) or \"Come fa Lei?\" (How do you do? - formal) sounds very strange and isn't used as a greeting in Italian.\n\n**In summary:**\n\nThe best functional equivalent for \"How do you do\" when meeting someone for the first time in Italian is **Piacere**, **Piacere di conoscerla** (formal), or **Piacere di conoscerti** (informal)."
          }
        ],
        "role": "model"
      },
      "finishReason": "STOP",
      "index": 0
    }
  ],
  "usageMetadata": {
    "promptTokenCount": 11,
    "candidatesTokenCount": 1110,
    "totalTokenCount": 1121,
    "promptTokensDetails": [
      {
        "modality": "TEXT",
        "tokenCount": 11
      }
    ],
    "thoughtsTokenCount": 709
  },
  "modelVersion": "gemini-2.5-pro-exp-03-25"
}
```

It takes about 13 seconds to get answer, while `https://generativelanguage.googleapis.com/v1/models/gemini-2.0-flash:generateContent?key=$GEMINI_API_KEY` is almost istantaneous.

**Comment by colemar** [comment]
```
$ curl -s https://generativelanguage.googleapis.com/v1/models?key=$GEMINI_API_KEY -H 'Content-Type: application/json' | grep '"name":'
      "name": "models/gemini-1.0-pro-vision-latest",
      "name": "models/gemini-pro-vision",
      "name": "models/gemini-1.5-pro-001",
      "name": "models/gemini-1.5-pro-002",
      "name": "models/gemini-1.5-pro",
      "name": "models/gemini-1.5-flash-001",
      "name": "models/gemini-1.5-flash-001-tuning",
      "name": "models/gemini-1.5-flash",
      "name": "models/gemini-1.5-flash-002",
      "name": "models/gemini-1.5-flash-8b",
      "name": "models/gemini-1.5-flash-8b-001",
      "name": "models/gemini-2.0-flash",
      "name": "models/gemini-2.0-flash-001",
      "name": "models/gemini-2.0-flash-lite-001",
      "name": "models/gemini-2.0-flash-lite",
      "name": "models/embedding-001",
      "name": "models/text-embedding-004",

$ curl -s https://generativelanguage.googleapis.com/v1beta/models?key=$GEMINI_API_KEY -H 'Content-Type: application/json' | grep '"name":'
      "name": "models/chat-bison-001",
      "name": "models/text-bison-001",
      "name": "models/embedding-gecko-001",
      "name": "models/gemini-1.0-pro-vision-latest",
      "name": "models/gemini-pro-vision",
      "name": "models/gemini-1.5-pro-latest",
      "name": "models/gemini-1.5-pro-001",
      "name": "models/gemini-1.5-pro-002",
      "name": "models/gemini-1.5-pro",
      "name": "models/gemini-1.5-flash-latest",
      "name": "models/gemini-1.5-flash-001",
      "name": "models/gemini-1.5-flash-001-tuning",
      "name": "models/gemini-1.5-flash",
      "name": "models/gemini-1.5-flash-002",
      "name": "models/gemini-1.5-flash-8b",
      "name": "models/gemini-1.5-flash-8b-001",
      "name": "models/gemini-1.5-flash-8b-latest",
      "name": "models/gemini-1.5-flash-8b-exp-0827",
      "name": "models/gemini-1.5-flash-8b-exp-0924",
      "name": "models/gemini-2.5-pro-exp-03-25",
      "name": "models/gemini-2.5-pro-preview-03-25",
      "name": "models/gemini-2.0-flash-exp",
      "name": "models/gemini-2.0-flash",
      "name": "models/gemini-2.0-flash-001",
      "name": "models/gemini-2.0-flash-exp-image-generation",
      "name": "models/gemini-2.0-flash-lite-001",
      "name": "models/gemini-2.0-flash-lite",
      "name": "models/gemini-2.0-flash-lite-preview-02-05",
      "name": "models/gemini-2.0-flash-lite-preview",
      "name": "models/gemini-2.0-pro-exp",
      "name": "models/gemini-2.0-pro-exp-02-05",
      "name": "models/gemini-exp-1206",
      "name": "models/gemini-2.0-flash-thinking-exp-01-21",
      "name": "models/gemini-2.0-flash-thinking-exp",
      "name": "models/gemini-2.0-flash-thinking-exp-1219",
      "name": "models/learnlm-1.5-pro-experimental",
      "name": "models/gemma-3-1b-it",
      "name": "models/gemma-3-4b-it",
      "name": "models/gemma-3-12b-it",
      "name": "models/gemma-3-27b-it",
      "name": "models/embedding-001",
      "name": "models/text-embedding-004",
      "name": "models/gemini-embedding-exp-03-07",
      "name": "models/gemini-embedding-exp",
      "name": "models/aqa",
      "name": "models/imagen-3.0-generate-002",
```

**Comment by colemar** [comment]
[gemini_v1_models.json](https://github.com/user-attachments/files/19658143/gemini_v1_models.json)

[gemini_v1beta_models.json](https://github.com/user-attachments/files/19658147/gemini_v1beta_models.json)

**Comment by niksedk** [comment]
OK, SE will now try to switch to the `v1beta` endpoint if getting a 404 http status code.

https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.11/SubtitleEditBeta.zip

Does this work for you?

I also added the `gemini-1.5-pro` model

Sounds like the flash models currently available are the best choice?

**Comment by colemar** [comment]
@niksedk 
Yes, SE 4.0.11 beta 263 auto-translation works even with model `gemini-2.5-pro-exp-03-25`.
The translated blocks of lines appear about 10 seconds apart, so the translation is slower (maybe about twice the time in respect to `gemini-2.0-flash`). I haven't looked into the quality of the translation yet.
