### ISSUE TITLE
[Feature Request] Can Batch Convert OCR be multi-threaded?

### ISSUE THREAD

**Issue by DoubleStrike** [SubtitleEdit/subtitleedit#7902]
I currently have a set of MKV files that I am running a batch convert on to do OCR on the PGS subtitles into SRT files.

When running batch convert, the processing is 1 file at a time which is unfortunate since I have a 32-thread processor and tons of RAM.  It would be nice to be able to set an option to just spin up as many threads as I want to speed up such batch processes.

I'll freely admit I am pretty new to SE, but I don't see any existing options to enable this, and repeated testing is definitely only doing a single OCR process at a time.

**Comment by GrampaWildWilly** [comment]
I have SE pinned in my Windows 11 Start Menu.  When I click the icon, SE opens.  While SE is already open, clicking SE again opens a new instance of it.  You could multithread that way, although I think that would be pretty resource-intensive.

I've never done anything with the command line interface to SE but I know there is one from reading the activity that happens in this forum.  If you're executing SE functions from the command line, you could put the commands for each of your operations into a .bat script.  Then instead of just executing the commands one after the other, START them.  That would also multi-thread them.

However, there are possible problems with this idea.  I don't know if SE could withstand such stress.  Specifically, there may be common files that each instantiation of SE would update & that could cause some rather nasty race conditions.  Someone who knows a whole lot more than I do would have to tell you whether my idea here is even feasible.

**Comment by niksedk** [comment]
Sorry, it was actually multi-threaded for a while.
I was just too much trouble - e.g. file access + ocr not really linking mt as it's alerady mt.
