### ISSUE TITLE
Please add two more layouts

### ISSUE THREAD

**Issue by TheCodeverse** [SubtitleEdit/subtitleedit#8024]
Modify on the basis of layout 1
![Screenshot_20240313_124633_1710305193e](https://github.com/SubtitleEdit/subtitleedit/assets/37426761/57bfd76d-5e1a-47ba-af2c-15d83d823382)

Add a new layout 1-1
![Screenshot_20240313_124633_1710305193_P1](https://github.com/SubtitleEdit/subtitleedit/assets/37426761/3b6e0aa2-cdd4-40d0-b258-36224477a08b)

Add another new layout 1-2
![Screenshot_20240313_124633_1710305193_P2](https://github.com/SubtitleEdit/subtitleedit/assets/37426761/9f0d5ea0-6a85-42a9-84c4-05855d3d4d08)

**Comment by noembryo** [comment]
This!!
And if only one can be implemented, then for sure 1-1.. 🙏

**Comment by noembryo** [comment]
And while we are at this, an option to hide the `Unbreak` & `Auto br` buttons will be greatly appreciated to reduce the width of this box (since I have assigned keyboard shortcuts for them)

**Comment by LeonCheung** [comment]
@TheCodeverse Not sure why ppl would possibly need a so wide textbox in the last screenshot because a typical CPL for a caption line can't be that long, but anyway, I'm think of a typical use case like that. We'll see.

I've started a similar discutiton in #7422.

TBH, I don't think it's a good idea to hide everything because that will confuse newbies. Many people still prefer buttons to shortcuts nowdays, so having more buttons can make more sense instead. Say, having a dedicated toolbar as I've proposed, and you can hide that toolbar if you are an experienced user and prefer using shortcuts.

The layout in your second screenshot is not bad, but it has some disadvantages as I mentioned in my post too.

However, replacing text buttons with well-designed icons could be something interesting to try. It might be something that devs hate yet users love. :)

**Comment by noembryo** [comment]
>TBH, I don't think it's a good idea to hide everything because that will confuse newbies. Many people still prefer buttons to shortcuts nowdays, so having more buttons can make more sense instead

I was referring to options, not defaults.
Of course these buttons should be visible by default.
But a "Show Break/Auto Br" buttons option (like "Show video controls"), will be very welcomed.. 😉 

>For me, Layout 1-1 (i.e. Screenshot 2) is what I often need

Ditto 🥳
