### ISSUE TITLE
Add a few ASSA override tag templates

### ISSUE THREAD

**Issue by niksedk** [SubtitleEdit/subtitleedit#8085]
Mostly due to https://github.com/SubtitleEdit/subtitleedit/discussions/8066 I've added a few ASSA text animation/style templates:

![317686876-ea0ad5ad-721c-4e98-8eb9-9d3325be1a23](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/5436452b-f318-436f-b9fe-7d8c46c1e19a)

These I've added:
![317687475-30b46544-75f5-4270-b4b0-31e53023464c](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/62d32e87-25b0-4828-a366-8c49f1162ecb)

```c#
    { "- Templates -", string.Empty },
    { "Font size change", "{\\t(\\fs60)}" },
    { "Move text from left to right", "{\\move(350,350,1500,350)}Move test" },
    { "Color from white to red", "{\\1c&HFFFFFF&\\t(\\1c&H0000FF&)}" },
    { "Rotate X (slow)", "{\\t(\\frx25)}" },
    { "Rotate X", "{\\t(\\frx360)}" },
    { "Rotate Y", "{\\t(\\fry360)}" },
    { "Rotate (tilt)", "{\\t(\\fr5\\fr0)}" },
    { "Fade", "{\\fad(300,300}" },
    { "Space increase (slow)", "{\\t(\\fsp4)}" },
```

Does anyone have a few more nice tricks? @LeonCheung ?

Beta link: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.4/SubtitleEditBeta.zip

**Comment by LeonCheung** [comment]
Oops, just reached this post... Quite a busy week, sorry. XD

Totally agree with this idea. Actually I did think about having templates, and it might be even cooler to allow creating/naming/storing customized templates, rather than only being listed as History. You know, everyone has his/her own handy tags to use for their daily projects, so...

I'll look into this and see what I can do. ;)
