### ISSUE TITLE
Copy/Paste - Ditto clipboard manager

### ISSUE THREAD

**Issue by uckthis** [SubtitleEdit/subtitleedit#8167]
I don't know how to explain this issue, but many a time I use Ditto clipboard manager to quickly paste speaker IDs where needed, but whenever I do it, SE deletes the subtitles text. I then have to Ctrl+Z to bring the text back and Ctrl+V to paste the speaker ID. Attaching .gif to explain. Is this a SE issue or Ditto issue? And does anyone use any other clipboard manager? 
![Animation](https://github.com/SubtitleEdit/subtitleedit/assets/28671050/4323b23e-a2b7-4a98-acb8-bf9929b4cdec)

**Comment by darnn** [comment]
As you can see, once the textbox loses focus and then regains it, the text in it is selected, as though you've pressed control+A. Therefore when the text you're pasting gets pasted, it erases everything that's already there, since it's selected. This is the same bug I described here:
https://github.com/SubtitleEdit/subtitleedit/issues/2068

Not sure about a solution, though, since Nik couldn't reproduce it. I do use something different, a text expander called Breevy (now renamed aBreevy8, though I'm still using the version from before the name change as it's more compatible with SE). Since it works by taking something I've typed and changing it into something else (i.e. if I type "org" it automatically changes it into "organization"), I don't experience this issue in these circumstances. As for the rest, I've just learned that whenever I alt+tab away from SE and then back, I need to press the home or end key (or one of the arrow keys) to unselect the text.

**Comment by uckthis** [comment]
I use Ditto as it's a standalone clipboard manager and works anywhere where you can type a text - be it a webpage or a software. It can store up to 100 clips, and once you select an item from its list, it'll go on top of the list and then Ctrl+V would reproduce it, so when SE loses the text, I just undo the last action and then click paste. This has been happening for years, but now I use it too often and hence annoying.

**Comment by GrampaWildWilly** [comment]
The maximum number of clips (Ditto's terminology) is adjustable in its Options dialog.  As for a field getting entirely selected after a task switch, & activating Ditto via its shortcut is seen by Windows as a task switch, that's just the way Windows works.  SE is only one app where this behavior can be annoying.  It happens in the system file selection dialog as well.  That can be launched from any number of apps, like Firefox, Notepad++, etc.  What you're doing is probably what has to be done.  No way out.  Everything has its price.  Nothing's free.

**Comment by LeonCheung** [comment]
Hah, guess what, this inspired me of an interesting feature idea: **Fast Insert**, which is a function like a super click board, say, having a button, context menu, and/or shortcut to pop up a preset list window, then insert anything to the cursor pos, and/or replace selected texts, such as Speaker labels, and terms, quick translations, etc. with a single click.

Back to your issue, although I can't help solving it in your way, I may suggest another trick mentioned in #7794 with help of ASSA, to add speaker labels, hoping it helps a bit.

However, adding speaker labels at the final step may break the CPL rule to multiple lines. So you may want to review everything again.... That's why I higher suggest a potential *Fast Insert* tool. Hmm, maybe have a button below the <Auto br> button? Anyway, just saying. :P

**Comment by GrampaWildWilly** [comment]
Let's say I'm in Notepad++ & I want to save a file.  I hit Ctrl+s & it gives me the usual Windows file selection dialog.

![#01](https://github.com/SubtitleEdit/subtitleedit/assets/75588964/1abe98c5-1d67-45fa-809b-fffafc38c5c1)

Here, Notepad++ is proposing the file name `new 1.txt`.  And the entire candidate file name is highlighted.

Let's say I want to insert a clip from Ditto in front of the file name you can see in that image.  So I want to create a file with the name `46new 1.txt`.  I move the cursor to the front of the candidate file name.  Then I hit my Ditto keyboard shortcut.  Ditto shows me this:

![#02](https://github.com/SubtitleEdit/subtitleedit/assets/75588964/9d5cb376-7aab-45ad-a88f-28c17286e72a)

I hit Enter on that clip at the top of the Ditto list.  That brings me back to Notepad++ & it's now proposing this file save:

![#03](https://github.com/SubtitleEdit/subtitleedit/assets/75588964/012d1128-4b69-47ad-a258-e1d7bd6eff8b)

The Ditto keyboard shortcut is presented to Windows as a task switch.  When you switch away from a file selection dialog, Windows automatically re-highlights the text entry field.  That happens at the moment you hit the Ditto keyboard shortcut.  By the time you hit Enter in Ditto, it's already too late.  The insert goes on top of the highlighted text, thus completely replacing it.

The only way out is to try again.  But at this point, the clip from Ditto will also be in the Windows system clipboard.  So once Notepad++ proposes your candidate file name, you can hit the Home key to move the cursor to the beginning of the file name, which also removes the text highlight.  Then you can do Shift+Insert & poof, your 46 will go in the expected position.  On this second attempt, Ditto does not participate.

But this isn't about Ditto.  Using the same starting point in my first image above, move the cursor so the highlighting is removed from the candidate file name.  Now switch tasks to anything at all, Task Manager, system Settings, Resource Monitor, absolutely anything at all.  Then switch back to the Notepad++ task.  What do you see?

If there is a problem anywhere, it's in Windows.  Certain types of data entry fields are treated like this.  I guess whatever you are doing in SE happens to use a field of this type.  I don't know how to program Windows.  Maybe there's a way to define the data entry field in SE with different attributes so Windows won't highlight the whole data entry field on a task switch.  To my way of thinking, this is just how it works.  Maybe some smart Windows coders could make SE work differently.

**Comment by darnn** [comment]
Yeah, the only other thing I'd say is, you can try to submit a bug report to Ditto:
https://github.com/sabrogden/Ditto/issues

And/or a feature suggestion to have the option to send a keypress of left arrow and then right arrow before pasting, so that the cursor returns to its original position. Although if the cursor is at the start of the line, it would then move to the right, so that's also not a perfect solution.

**Comment by niksedk** [comment]
I use Windows clip board manger (Win+v) - works fine.
