### ISSUE TITLE
reopening file in translator mode merges lines which I splitted in previous session.

### ISSUE THREAD

**Issue by fraternl** [SubtitleEdit/subtitleedit#8173]
I'm working on a file which has many too long lines in the original subtitle.

In the file I'm working on I've split those lines manually and corrected the timings so the 2nd part starts at the correct position.
After reopening the file all those lines are concatenated and I wind up with 4 lines per timecode at those places.

I have unchecked _"allow edit of original subtitle"_

<img width="557" alt="image" src="https://github.com/SubtitleEdit/subtitleedit/assets/8692856/8e7fa298-646f-43a5-af3e-28719f33bea0">

Is this to be expected?

To prevent it from happening again I should maybe turn on the "allow edit" and discard that original subtitle.
The original subtitle is of course not good anyhow.

**Comment by darnn** [comment]
I'm not sure what happens when you have `Allow edit of original subtitle` turned off, but you may have gotten a desync during the session in which you split them. You wouldn't have seen it then (except through the indicator in the video menu), but it can cause things to look different once you close both files and open them again. The indicator is the leftmost tab in the video menu:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19672444/dcb74edc-b3c1-4547-b125-0a40f27ce4fb)

The `OK` would change into an error message if there was a desync.

**Comment by niksedk** [comment]
Splitting lines and keeping in sync with original will not work, sorry.
