### ISSUE TITLE
question mark or exclamation mark after italic text

### ISSUE THREAD

**Issue by fraternl** [SubtitleEdit/subtitleedit#8597]
When a question mark or exclamation mark is placed after a an italic text it will often result in a bad render of most players.
A space before the question/exclamation mark could solve this.

In French there's always a space in front of a question mark. It's not wrong per se.
Personally I prefer it without. I don't know if that's because I'm used to see texts without a space in front.

But like I wrote...
My proposal is only to prevent a bad render of many players.

**Comment by uckthis** [comment]
It already does for French. Make sure to check Fix Missing Spaces in Fix common errors and it'll add a space before ? or ! 
For this to work, the subtitles have to be in French; it doesn't work for English, and rightly so.

**Comment by fraternl** [comment]
You probably haven't read what i wrote.

It's for italic text only. 
Many, if not almost all, players do not properly handle italic text.
A (normal) question mark directly after an italic text will give a bad render. The question mark will bleed into the text

A space can solve this.

**Comment by uckthis** [comment]
Do manual find & replace, then.

**Comment by fraternl** [comment]
Your answer applies to almost all features already implemented. 

In this case I need to do it last and can't use the "fix common errors" as it will undo that search & replace. 

Furthermore do I not understand why a valid request should be torpedoed if there's no negative consequences for you 

I'm already doing this search& replace and it will be something I need to think of for every subtitle with these kind of italics.

Thanks for your involvement without first even understanding what it was about.

**Comment by uckthis** [comment]
It is quite simple: Fix common errors first, and then do the search & replace - it should take no more than two clicks to add a space before a ! or a ?.

Additionally, there are grammar rules to consider. If French requires a space before a "?" or a "!", those are the rules all French users will follow. If an amendment to the code adds a space before a "?" only in italics, many French subtitlers would have to correct it manually, as they would see it as a mistake.

Your issue is specific to you, as three are no threads describing what you're describing. I don't know which player you're using, maybe trying changing to a different font or a different subtitling format.


Anyway, I was just trying to help, and it looks like you don't need any.

**Comment by fraternl** [comment]
The part you wrote about French subtitles being destroyed is nonsense. 

This can be implemented in a way that doesn't get in the way of anyone and I wouldn't want it otherwise. 

Again, I don't understand people who like to torpedo other people's feature requests merely because it doesn't benefit themselves. 

I already didn't have high hopes for this, so I'm closing it myself. 

Maybe I can one day return the benefit.
