### ISSUE TITLE
Just a question about subtitle background, it is not the issue. 

### ISSUE THREAD

**Issue by Cyberyoda1411** [SubtitleEdit/subtitleedit#8754]
When we have a video (TV show for instance), we have the names of the actors (they call it CREDITS) and other things at the beginning and the end of that video. In this case, these letters can make a mess with the subtitles, because they are on the screen at the same time. 

The first solution is to put the titles in the top position until we can put the title on the bottom. But, if the faces of the actors are too high, we can't put the subtitles over their faces. 

The only solution is to keep the subtitle on the bottom of the screen and to have some background until the CREDITS vanishes. How to do it? Is it possible? 

The obvious solution is to burn the subtitles, but I don't want to burn the subtitles, to become part of the video, and I don't to burn the COMPLETE video. And if you burn just some lines, you select them/right click/selected lines/generate video with burned-in subtitles...., you will get nothing but a short video with the selected lines to be burned. Video will be cut, you don't get a complete video with just a couple lines burned in. 

Is it possible to get the whole video, with several lines in the background, and then remove it, when the credit lines on the screen vanish?

**Comment by GrampaWildWilly** [comment]
My initial reaction is to just delete all the subtitles that occur during the credits.  But that's perhaps a bit flippant.  I will offer this:

![#01](https://github.com/user-attachments/assets/4827c1ec-0137-4838-86e0-db754551e300)

These are some of my SE settings.  The 2 significant areas are in the box outlines within that image.  First, I am following Nik's advice & using MPV as my video engine.  In addition, I have set MPV to handle preview text.  That delegates display of subtitles to MPV.  At least, that's my understanding of the check box.  Do correct me, somebody, if I'm wrong.

In the other outline box you have the color & background controls for the display of subtitles.  In my case, I always want a totally opaque black box to surround my subtitles, with the characters of the subtitles being white.  The black background box is specified in 2 parts.  The main part is the Opaque box radio button & the `One box (use shadow color)` selection in the dropdown below the radio button.  The colors are controlled from the 3 controls marked Primary, Outline, & Shadow.  You get the color picker dialog for a particular component by clicking each word.  These are my selections.  For Primary:

![#02](https://github.com/user-attachments/assets/2bf6f5a3-42da-4a3c-a910-5952a694542d)

For Outline:

![#03](https://github.com/user-attachments/assets/1fcc4f1d-c7f3-4c05-80fb-fd15182be462)

For Shadow:

![#04](https://github.com/user-attachments/assets/90a7dc6c-907c-4750-b7a0-79e8a8f748b9)

The trick I found was that I had to ramp the Alpha value up to maximum in the color picker for Shadow.

You can choose whichever colors suit you.  I'm just showing where you would choose those colors.

With this group of settings, my subtitles are always white letters on a black background.  That way, even if the content of the video is mostly white, the white subtitles will still be visible against their associated black background.

I chose this particular combination in order to immunize my subtitles against whatever colors might be in the video itself.  The subtitle color & position does not have to adapt to the whims of the video.  The subtitles are always white characters against a black background, which makes them visible no matter what the video might be doing.  I would assume this would work for credits as well, although subtitles during credits is kind of rare, isn't it?  Unless they're translations of the credits.

If I'm playing a video with subtitles outside SE, which would be in VLC, there are settings in VLC to control the same thing.  But they are settings within VLC, not within the subtitles.  I won't stray so far off topic as to go into what to do in VLC to get the same effect.

**Comment by Cyberyoda1411** [comment]
You can't delete subtitles during the CREDITS, in most TV Shows they talk from the first second. You can't leave it without titles. 

Your input is great, but my focus is not to play video in SE, but in many other players, I use GOM player. And you gave me a lot of settings that are related to SE only. 

On the other hand, it is not what I want, even if I could have the same settings from SE in some outside player. Because I don't want any background in my subtitles all the time, I want it only while the initial or the last credits are shown on video. In all other circumstances, I would like to have normal subtitles. 

I could live with burning just a particular lines of subtitles (with the background), to have that as a part of video, no problem. But when you select several lines, the whole video won't be recreated, it will be video for these several lines only, it will be cut. What I'd like to have is normal subtitles - burned subtitles (while credits are shown on video) - normal subtitles. But, the result is video with only burned subtitles, the rest is cut.

**Comment by GrampaWildWilly** [comment]
Oh right.  TV shows.  I was thinking more like movies or operas.  OK.  You're right.

I have mostly vtt subtitles here.  I can see where I can change the color of a subtitle but not its background.  This may be just a restriction in vtt.  I just popped up the context menu in the Text Box & there's an entry in the context menu for color.  But this sets only the color of the subtitle text.  I also highlighted a group of subtitles & the same context menu popped up on the set of subtitles.  Presumably, I could change the color of all the subtitles within that set.  I would have to defer to others to say whether that context menu contains anything for setting the background of an individual subtitle.  I would also hope that if that function is available for other subtitle types, that you could select a sequence of subtitles & change the background of all of them in one shot.

Just for grins & giggles, I got SE 4.0.7 beta 139 to play with this a bit.  In SE I changed the color of the subtitles for a small block of subtitles.  Playing that particular opera in SE did show the changed color.  But when I tried to use the same vtt file in VLC, it ignored the color code.  This wouldn't be the first thing I've encountered that VLC didn't handle quite right.  Maybe another media player would handle it better.  Clearly, MPV inside SE handles it better.  But this isn't something I'm likely to ever mess with for real.  I have enough trouble with color that white on black is what I have to have.  I suppose my test is a warning that whatever SE does is not necessarily transferable to an outside media player.

**Comment by RAMoynihan** [comment]
Perhaps I'm misunderstanding what you are trying to do, but it seems like you just need to pick a subtitle format that allows 'styles' and that GOM supports. You would just use one style for most of the subs and a different style for the start and end credits. The 'style' for the credit parts could include an opaque background, while the default style does not. If you save the subs in a format like .ass then GOM should be able to use them, I think.

**Comment by techguru0** [comment]
gom is not a good player

**Comment by Cyberyoda1411** [comment]
To RAM. When you say STYLE, do you think about Bold, Italic, Normal? I don't know if I can use any attributes of the subtitles for several lines only. Can I?

**Comment by Cyberyoda1411** [comment]
To techguru(). What I want to do, it doesn't have any connection with the player. You all ask what I want to do. Let me explain.

I want to know if I can have the normal subtitle lines - then the credits in the beginning of the TV show starts, and I want several lines with the background (for obvious reasons), then the rest of the subtitles to be normal. I would like to know if it can't be done, even if it would be done by burning subtitles (though I'd like to skip that). But, the burning option cuts the rest of the video, it shows only burned parts. 

About GOM player. It is an excellent player. When I want to save some video + subtitles for my use, I make small editing of the subtitles, the most important thing is that timing is OK (for the small things I don't use SE). I open the GOM player and load subtitles in it (mostly with drag and drop), and I open the subtitles in Notepad (this is the same SRT file in video and in Notepad). When I see some small subtitle mistakes in the GOM player, I go to Notepad and edit that mistake. GOM knows something has been changed because it uses the same SRT file. And asks me if I want to have that change in the video too. So, I can see what I changed in real-time, immediately. OTHER PLAYERS CAN'T DO IT. They must be restarted, then they will show edited lines. 

I use the Serbian language for subtitles, it uses EAST EUROPEAN code, and many players didn't support that, like VLC. Maybe the second best after GOM Player is POT Player, if we talk about subtitles and options related to this. Maybe VLC is THE WORST. It has the small, bigger,..., font, instead of giving me 12, 14, 18... fonts for the subtitles. VLC has many options that I don't need, but the subtitle options are very poor.

**Comment by techguru0** [comment]
@cyber why not mpc-hc or mpc-be
or mpv with a gui
also have you tried smplayer

**Comment by RAMoynihan** [comment]
> To RAM. When you say STYLE, do you think about Bold, Italic, Normal? I don't know if I can use any attributes of the subtitles for several lines only. Can I?

No, sorry, I meant a subtitle 'style'. If you select 'advance sub station alpha' as your subtitle format it adds a 'style' column to the SubtitleEdit window. I have mocked up such a situation in the attached image. You can see that the last 2 subtitles overlap in time, so they are both shown on the screen at the same time. I called one style 'credit' with a black background, while the other one, 'default', has larger font and no background.

I have circled where you select the subtitle format, where the 'style' column appears in SE, and the button you use to set the attribures (font, size, background, colour, etc) for each style.

Using this method you should be able to select all the subs which happen during the credits and set their 'styles' to 'credit' (or whatever you name it.

![SE1](https://github.com/user-attachments/assets/d9e7c878-edc0-4a68-9a48-be7c12742d09)

**Comment by Cyberyoda1411** [comment]
RAM you are a pure genius. You solve the problem. 

1. I need an advanced substation alpha subtitle format
2. I need to create a new style with a black background, besides some default format with the normal style of showing subtitles
3. Then I just select the lines that will be with the black background (while the credits are shown in the vide), and the rest will be normal, with the default style. 

You completely solved the problem. Thanks.

**Comment by RAMoynihan** [comment]
You are welcome.
