### ISSUE TITLE
Add É (capital E with acute accent) to list of French special characters

### ISSUE THREAD

**Issue by dobratzp** [SubtitleEdit/subtitleedit#8782]
Although sometimes in French the accent acute mark is omitted when used with capital letters, in many cases it is not omitted so to type words like Écoutez, need to add the capital E with acute mark to the right-click menu of French special characters.

É

Unicode: U+00C9

Workarounds:

Use keyboard shortcuts on Windows for É:
Alt + 144 (code page 437)
Alt + 0201 (code page 1252)

Browse to the Spanish section of the right-click menu and then select É.

**Comment by niksedk** [comment]
Now included in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.7/SubtitleEditBeta.zip

**Comment by GrampaWildWilly** [comment]
Hmmmm.......  I have 2 keyboards defined in Windows, ENG & FRA.  This is a feature of Windows that you'll have to look up to learn about.  Win+Spacebar swaps between them.  When I have the FRA keyboard selected, I can type the apostrophe character.  That causes no character to appear because apostrophe is an escape character on the FRA keyboard.  After apostrophe, I hold down Shift & type e, which of course is capital E.  But what appears in the text is É.  And same for the other vowels that can be both capitalized & accented.  This works in every application I've tried to use it, including SE.  Nik has apparently done something within the code to accommodate your request.  But I would have thought you would just be using the FRA keyboard & be done with it.  Doesn't that work better?  That gives you more natural keyboard sequences to generate the accented characters, like ç, ä, ù, and even ö, ü, ñ, which aren't even French.  The Right-Alt key gives several additional characters, like å®þ«»ßø¶æ©¿¡²³¤€¼½¾‘’¥×.  There's no need to remember the numerical codes for each accented character.  Have you never investigated this Windows feature?
