### ISSUE TITLE
S.E. crashes when opening a video

### ISSUE THREAD

**Issue by nounours18200** [SubtitleEdit/subtitleedit#8819]
The latest 4.08 version of Subtitle Edit crashes if I try to open the following video (that I have of course previously downloaded):

https://www.youtube.com/watch?v=T6_xXp8etko

Be aware that this video is a very old film (1931) and has been built by joining 2 parts (the main part of the film, and the last scenes) having different speed (FPS) as far as I am told.

There the video cold have 2 different FPS, and maybe this could explain the crash of S.E. ???

**Comment by GrampaWildWilly** [comment]
I downloaded that video & these are the results I got:

![#01](https://github.com/user-attachments/assets/c76f20d4-d57c-4e9b-8759-2ef506133afc)
[ffprobe.txt](https://github.com/user-attachments/files/16972137/ffprobe.txt)

Within a single video file, the bit rates can vary throughout the file.  But it is my understanding that a frame rate is constant for the duration of a video.  I can't say your speculation about frame rate is likely to be at the root of your problem.

I downloaded SE 4.0.8 beta 11 to try this out, since I had the video anyway.  Doing `Video -> Open video file...` loaded up the movie.  I skimmed through it & it seemed to play just fine.  Of course, I didn't have any subtitles, but that doesn't seem to be the issue.

This is on Windows 11 Pro 64-bit version 23H2 build 22631.4169.

Maybe you should get the latest beta.

**Comment by nounours18200** [comment]
I confirm that the problem is solved: I used the 4.0.8 but it crashed, and tomorrow it works fine ! 
The issue was maybe due to an another application that was running at the same time ??
It was not due to the hardware because the PC is a big machine (64Gb of RAM, W11 Pro 64-bit version 23H2 build 22631, etc...).

Anyway, the case can be closed.

Thank you for your support, and your excellent program !
