### ISSUE TITLE
Deepl API error 

### ISSUE THREAD

**Issue by Tolunayization** [SubtitleEdit/subtitleedit#9033]
![sub error](https://github.com/user-attachments/assets/8c4b9a58-c7ab-4da3-bcd1-4caa2f8ee605)

how can i fix this issue i try everything

**Comment by masterofthesith** [comment]
Windows update ile alakalı bir sorun gibi gözüküyor. Bugün bir update yayınlandı. Update'i geriye döndürürsen sorun %90 çözülür. Veya yeni versiyon güncellemesi bekleyeceksin.

It seems to be a problem with Windows update. An update was released today. If you roll back the update, the problem is 90% solved. Or wait for a new version update.

**Comment by niksedk** [comment]
Dupe of #9034
